### ISSUE TITLE
can't build ejabberd compile from source

### ISSUE THREAD

**Issue by ymg2006** [processone/ejabberd#1426] opened 2016-12-17 21:19 UTC
hello,i want to compile ejabberd 16.12.beta1 from source on centos 7.2 -minimal, i followed these steps :

wget https://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
rpm -Uvh erlang-solutions-1.0-1.noarch.rpm
yum install erlang
mkdir temp && cd temp
git clone git://github.com/processone/ejabberd.git ejabberd
cd ejabberd
./autogen.sh
./configure --enable-user=ejabberd --enable-hipe --enable-iconv --enable-redis --enable-zlib
make

i'm getting this error while compiling :(cmd output)

==> xmpp (compile)
Compiled src/xmpp_util.erl
Compiled src/xmpp.erl
Compiled src/xdata_codec.erl
Compiled src/pubsub_subscribe_options.erl
Compiled src/pubsub_subscribe_authorization.erl
Compiled src/pubsub_publish_options.erl
Compiled src/pubsub_get_pending.erl
Compiled src/muc_roominfo.erl
Compiled src/pubsub_node_config.erl
Compiled src/muc_request.erl
Compiled src/muc_register.erl
Compiled src/muc_roomconfig.erl
Compiled src/jid.erl
Compiled src/mam_query.erl
Compiled src/flex_offline.erl
eheap_alloc: Cannot allocate 1318267840 bytes of memory (of type "old_heap").

Crash dump is being written to: erl_crash.dump...

i have 2GByte of ram (about 500MByte is used) and 2GByte swap .
what can be the cause of this error ? is there any fix ? how to overcome that . thanks .

**Comment by zinid** [comment] 2016-12-17 21:34
The problem is in this file: https://github.com/processone/xmpp/blob/master/src/xmpp_codec.erl
Erlang requires enormous amount of memory to compile it. This is a known problem, there is a plan to generate this codec into several files, but this will not be done very soon, late January maybe.

**Comment by ymg2006** [comment] 2016-12-17 21:48
thank's alot ,but where i can inform that this issue has been resolved ? is there changelog or something ? or i have to compile and test it every time ?

**Comment by zinid** [comment] 2016-12-17 21:49
On this ticket. You're already subscribed to it by creating it.

**Comment by zinid** [comment] 2017-02-07 11:12
Fixed in https://github.com/processone/xmpp/commit/3976a85b40f85002713a93c74a0ffca664c3c062

**Closed by zinid** 2017-02-07 11:12 UTC
