### ISSUE TITLE
[dns] ejabberd request host but no xmpp service

### ISSUE THREAD

**Issue by Subnum12** [processone/ejabberd#2150] opened 2017-12-07 22:04 UTC
> What version of ejabberd are you using?

7.11

> What operating system (version) are you using?

Win2012

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Is there a way that dns is not checking for service e.g. "_xmpp-server._tcp.example.com" but "example.com" ?
`@ejabberd_s2s_out:process_closed:161 Failed to establish outbound s2s connection domain.com -> conversations.im: Stream closed by peer: This host does not serve conversations.im (host-unknown)`

As far as I can see this happens if ip of tld and xmpp server are differend.

**Comment by Subnum12** [comment] 2017-12-07 22:21
it is for sure a dns issue:
adding the ip of _xmpp-server._tcp.conversations.im in host `91.250.85.114 conversations.im` everything works!

ejabberd_s2s_out:handle_auth_success:218 (tls|<0.582.0>) Accepted outbound s2s EXTERNAL authentication domain.com -> conversations.im (91.250.85.114)

**Comment by cromain** [comment] 2018-01-03 16:20
this is not an ejabberd issue. i'm closing this thread.

**Closed by cromain** 2018-01-03 16:20 UTC

**Comment by Subnum12** [comment] 2018-01-03 17:24
What else should be responsible for this? If someone send a message to an external server (in this case conversations.im) ejabberd trys to connect to conversations.im. Therefore it asks for ip of conversations.im but it should ask for ip of xmpp server service (_xmpp-server._tcp.conversations.im).

In some cases the dns server provides differend ip's for differend services for a dedicated domain (e.g. for mail, xmpp,...). ejabberd must use the ip of the service and not the ip of the domain.

**Comment by weiss** [comment] 2018-01-03 19:56
> What else should be responsible for this?

There's no way we can tell without seeing your DNS traffic.

> it should ask for ip of xmpp server service

ejabberd is [15 years old][1] and the most popular XMPP server.  It does support SRV lookups :smile:

> should I create a new issue?

A new issue won't help, at least not without additional information.

[1]: https://pbs.twimg.com/media/DOwhwNlWsAAvndW.jpg:large

**Comment by Subnum12** [comment] 2018-01-03 21:50
Thanks for quick replay.

> There's no way we can tell without seeing your DNS traffic.

ejabberd requests IP of conversations.im, and NOT SRV record, there is no request of SVR at all - see log of DNS-Server:

`03.01.2018 21:59:10 2E0C PACKET  000000DE5EC0A210 UDP Snd 127.0.0.1     9dc7 R Q [8081   DR  NOERROR] A      (13)conversations(2)im(0)`
`UDP response info at 000000DE5EC0A210`
`   Socket = 500`
`  Remote addr 127.0.0.1, port 61038`
`  Time Query=1246272, Queued=1246272, Expire=1246275`
`  Buf length = 0x0200 (512)`
`  Msg length = 0x0032 (50)`
`  Message:`
`    XID       0x9dc7`
`    Flags     0x8180`
`      QR        1 (RESPONSE)`
`      OPCODE    0 (QUERY)`
`      AA        0`
`      TC        0`
`      RD        1`
`      RA        1`
`      Z         0`
`      CD        0`
`      AD        0`
`      RCODE     0 (NOERROR)`
`    QCOUNT    1`
`    ACOUNT    1`
`    NSCOUNT   0`
`    ARCOUNT   0`
`    QUESTION SECTION:`
`    Offset = 0x000c, RR count = 0`
`    Name      "(13)conversations(2)im(0)"`
`      QTYPE   A (1)`
`      QCLASS  1`
`    ANSWER SECTION:`
`    Offset = 0x0022, RR count = 0`
`    Name      "[C00C](13)conversations(2)im(0)"`
`      TYPE   A  (1)`
`      CLASS  1`
`      TTL    3599`
`      DLEN   4`
`      DATA   78.47.217.197`
`    AUTHORITY SECTION:`
`      empty`
`    ADDITIONAL SECTION:`
`      empty`
`03.01.2018 21:59:10 2E0C PACKET  000000DE5EC10240 UDP Rcv 127.0.0.1     bc98   Q [0001   D   NOERROR] AAAA   (13)conversations(2)im(0)`
`UDP question info at 000000DE5EC10240`
`  Socket = 500`
`  Remote addr 127.0.0.1, port 64086`
`  Time Query=1246273, Queued=0, Expire=0`
`  Buf length = 0x0fa0 (4000)`
`  Msg length = 0x0022 (34)`
`  Message:`
`    XID       0xbc98`
`    Flags     0x0100`
`      QR        0 (QUESTION)`
`      OPCODE    0 (QUERY)`
`      AA        0`
`      TC        0`
`      RD        1`
`      RA        0`
`      Z         0`
`      CD        0`
`      AD        0`
`      RCODE     0 (NOERROR)`
`    QCOUNT    1`
`    ACOUNT    0`
`    NSCOUNT   0`
`    ARCOUNT   0`
`    QUESTION SECTION:`
`    Offset = 0x000c, RR count = 0`
`    Name      "(13)conversations(2)im(0)"`
`      QTYPE   AAAA (28)`
`      QCLASS  1`
`    ANSWER SECTION:`
`      empty`
`    AUTHORITY SECTION:`
`      empty`
`    ADDITIONAL SECTION:`
`      empty`

For example, if i do a manually lookup for SVR I do see it on the DNS server as well, so if ejabberd would ask SVR it would get the correct answer:

cmd (nslookup -type=SRV _xmpp-server._tcp.conversations.im) I can see this in DNS server log:

`03.01.2018 22:04:20 2E88 PACKET  000000020BCB4160 UDP Rcv 127.0.0.1     0003   Q [0001   D   NOERROR] SRV    (12)_xmpp-server(4)_tcp(13)conversations(2)im(0)`
`UDP question info at 000000020BCB4160`
`  Socket = 504`
 ` Remote addr 127.0.0.1, port 53296`
 ` Time Query=1246582, Queued=0, Expire=0`
 ` Buf length = 0x0fa0 (4000)`
`  Msg length = 0x0034 (52)`
 ` Message:`
 `   XID       0x0003`
 `   Flags     0x0100`
 `     QR        0 (QUESTION)`
 `     OPCODE    0 (QUERY)`
 `     AA        0`
 `     TC        0`
 `     RD        1`
 `     RA        0`
 `     Z         0`
 `     CD        0`
 `     AD        0`
 `     RCODE     0 (NOERROR)`
 `   QCOUNT    1`
 `   ACOUNT    0`
 `   NSCOUNT   0`
 `   ARCOUNT   0`
 `   QUESTION SECTION:`
 `   Offset = 0x000c, RR count = 0`
 `   Name      "(12)_xmpp-server(4)_tcp(13)conversations(2)im(0)"`
 `     QTYPE   SRV (33)`
 `     QCLASS  1`
 `   ANSWER SECTION:`
 `     empty`
 `   AUTHORITY SECTION:`
 `     empty`
 `   ADDITIONAL SECTION:`
 `     empty`
`03.01.2018 22:04:20 2E88 PACKET  000000020BCB4160 UDP Snd 127.0.0.1     0003 R Q [8081   DR  NOERROR] SRV    (12)_xmpp-server(4)_tcp(13)conversations(2)im(0)`
`UDP response info at 000000020BCB4160`
`  Socket = 504`
`  Remote addr 127.0.0.1, port 53296`
`  Time Query=1246582, Queued=1246582, Expire=1246585`
`  Buf length = 0x0200 (512)`
`  Msg length = 0x006d (109)`
`  Message:`
`    XID       0x0003`
`    Flags     0x8180`
`      QR        1 (RESPONSE)`
`      OPCODE    0 (QUERY)`
`      AA        0`
`      TC        0`
`      RD        1`
`      RA        1`
`      Z         0`
`      CD        0`
`      AD        0`
`      RCODE     0 (NOERROR)`
`    QCOUNT    1`
`    ACOUNT    1`
`    NSCOUNT   0`
`    ARCOUNT   1`
`    QUESTION SECTION:`
`    Offset = 0x000c, RR count = 0`
`    Name      "(12)_xmpp-server(4)_tcp(13)conversations(2)im(0)"`
`      QTYPE   SRV (33)`
`      QCLASS  1`
`    ANSWER SECTION:`
`    Offset = 0x0034, RR count = 0`
`    Name      "[C00C](12)_xmpp-server(4)_tcp(13)conversations(2)im(0)"`
`      TYPE   SRV  (33)`
`      CLASS  1`
`      TTL    3600`
`      DLEN   29`
`      DATA   		Priority     = 1`
`		Weight       = 1`
`		Port         = 5269`
`		Target host (4)xmpp(13)conversations(2)im(0)`
`    AUTHORITY SECTION:`
`      empty`
`    ADDITIONAL SECTION:`
`    Offset = 0x005d, RR count = 0`
`    Name      "[C046](4)xmpp(13)conversations(2)im(0)"`
`      TYPE   A  (1)`
`      CLASS  1`
`      TTL    300`
`      DLEN   4`
`      DATA   91.250.85.114`

**Comment by weiss** [comment] 2018-01-04 01:16
> ejabberd requests IP of conversations.im, and NOT SRV record, there is no request of SVR at all

Hmm, I can't reproduce the issue with 17.11, and I don't see a [code path][1] that would explain this behavior.

[1]: https://github.com/processone/ejabberd/blob/17.11/src/xmpp_stream_out.erl#L860

**Comment by Subnum12** [comment] 2018-01-04 10:55
What should I tell, I have this behavior. Would it help if I give you access via teamviewer?

**Comment by Andy-2639** [comment] 2018-04-08 09:03
It seems that Erlang has a bug in Windows which prevents it resolving SVR records. I'm also affected ot this.

A solution is to manually enter the DNS Server IP addresses Erlang should use in the inetrc config file.
See solution 3 in https://www.ejabberd.im/fix-dns-srv/index.html . I entered the IPv6 and IPv4 address of my DSL-Router (which is also responsible for DHCP and DNS) and now Erlang successfully resolves SVR records.
