### ISSUE TITLE
Pubsub becomes unresponsive after 2-3 weeks uptime - 17.08

### ISSUE THREAD

**Issue by sailerinteractive** [processone/ejabberd#2026] opened 2017-10-01 20:37 UTC
> What version of ejabberd are you using?

17.08

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

From source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

The pubsub module became unresponsive two times after 2-3 weeks uptime on my production system. The server itself was still working fine, users where able to authenticate and use MUC but no pubsub notification where sent after a publish. All resources (memory, file descriptors, Erlang processes) where within limits. After a restart ejabberd resumed normally with pubsub working again. I did not see this issue before with 16.06

I could not see anything related in the logs. Any ideas what I could do to track down this issue?

**Comment by cromain** [comment] 2017-10-13 09:04
I can not reproduce this.
When you start having troubles with pubsub, can you run the following command in debug console and copy the output
```
[{sys:get_state(P), erlang:process_info(P,message_queue_len), erlang:process_info(P,current_function)}
  || {_,P,_,[M]}<-supervisor:which_children(ejabberd_gen_mod_sup), M==mod_pubsub].
```

**Comment by sailerinteractive** [comment] 2017-10-15 07:07
Thanks for the command. Will do as soon as i see the issue again!

**Comment by sailerinteractive** [comment] 2017-10-27 15:42
I just filed another bug #2071 which might be related.

**Comment by cromain** [comment] 2017-10-27 19:20
good shot, i'm not sure #2071 will make pubsub unresponsive, output of commands i sent is needed to see how pubsub is queuing first.
but in case #2071 eats your memory too much, you can just clean that table in ejabberd debug console with this safe command:
{code}
mnesia:clear_table(pubsub_last_item).
{code}

**Comment by sailerinteractive** [comment] 2017-10-30 08:03
Thanks for the quick fix for #2071! Right now i'm restarting the server ~ once per week to avoid it becoming unresponsive. With a fix for #2071 and proper monitoring for this case in place i will keep it running again and run the command you posted when this issue appears.

Could there be any other resources which are not properly freed when a node is deleted? I do see an ever increasing memory consumption of the ejabberd process but i'm not sure whether this is an issue or just the way memory management / GC works in Erlang. Is there any command which provides an overview on how / where this memory is consumed in the process?

**Comment by sailerinteractive** [comment] 2017-11-08 10:31
Just filed #2092, might be related.

**Comment by sailerinteractive** [comment] 2017-11-16 20:19
The issue just happened again. Here is the output of the command:
 
```
(ejabberd@w2gde1)1> [{sys:get_state(P), erlang:process_info(P,message_queue_len), erlang:process_info(P,current_function)} || {_,P,_,[M]}<-supervisor:which_children(ejabberd_gen_mod_sup), M==mod_pubsub].
** exception exit: {timeout,{sys,get_state,[<0.9974.2>]}}
     in function  sys:send_system_msg/2 (sys.erl, line 303)
     in call from sys:get_state/1 (sys.erl, line 112)
```
 After a restart of the node the commend goes through without any exception.

**Comment by sailerinteractive** [comment] 2017-11-16 23:24
I did some further research and found out that each time the issue appears i have the following entry in the ejabberd.log

2017-11-16 20:35:46.634 [error] emulator Error in process <0.6773.32> on node ejabberd@w2gde1 with exit value:
{function_clause,[{p1_mysql_conn,get_with_length,[<<255,189,4,35,52,48,48,48,49,68,101,97,100,108,111,99,107,32,102,111,117,110,100,32,119,104,101,110,32,116,114,121,105,110,103,32,116,111,32,103,101,116,32,108,111,99,107,59,32,116,114,121,32,114,101,115,116,97,114,116,105,110,103,32,116,114,97,110,115,97,99,116,105,111,110>>],[{file,"src/p1_mysql_conn.erl"},{line,642}]},{p1_mysql_conn,get_row,4,[{file,"src/p1_mysql_conn.erl"},{line,628}]},{p1_mysql_conn,get_rows,5,[{file,"src/p1_mysql_conn.erl"},{line,616}]},{p1_mysql_conn,get_query_response,4,[{file,"src/p1_mysql_conn.erl"},{line,500}]},{p1_mysql_conn,loop,1,[{file,"src/p1_mysql_conn.erl"},{line,359}]}]}

followed by many:
`2017-11-16 20:36:46.648 [error] <0.9974.2>@mod_pubsub:transaction_retry:3610 transaction return internal error: {timeout,{p1_fsm,sync_send_event,[<0.311.0>,{sql_cmd,{sql_transaction,#Fun<mod_pubsub.33.83428955>},-576173615950},60000]}}
`
The ASCII codes translates to: "ÿ½#40001Deadlock found when trying to get lock; try restarting transaction" - So could this actually be caused by a MySQL deadlock? 

Additionally there many error messages related to mod_privacy after the "Emulator Error"

`2017-11-16 20:36:47.023 [error] <0.1285.54>@ejabberd_hooks:safe_apply:383 Hook privacy_check_packet crashed when running mod_privacy:check_packet/4:`

Any idea what i could to do resolve this issue?

**Comment by cromain** [comment] 2017-12-06 17:02
what if you raise pool size in ejabberd.yml, adding something like
sql_pool_size: 50
(make sure mysql allows more than 50 client connections from your host)
i don't think such single issue can put driver in odd state making it stacking data, but better double check this.

**Comment by cromain** [comment] 2017-12-22 08:49
I'm closing this issue now as it's not pubsub related.
your pubsub becomes unresponsive because it stacks requests while backend is not responding and/or overloaded. this is a consequence because you're using pubsub, not the cause.
Please open a new issue if you have more errors logs on p1_mysql_conn, and check mysql status as that time. Don't forget to set sql_pool_size accordingly to your expected use also.

**Closed by cromain** 2017-12-22 08:49 UTC
Labels: Component:Pubsub, Note:Needs more info
