### ISSUE TITLE
Vcard4 support

### ISSUE THREAD

**Issue by ghost** [processone/ejabberd#3325] opened 2020-07-09 19:59 UTC
Hi!

As reported in https://github.com/tigase/beagle-im/issues/37#issue-654294277 for BeagleIM client there seems some kind of incompatibility between BeagleIM (and likely the other Tigase clients as well) and ejabberd that results in not being able to edit the user profile on ejabberd with BeagleIM. 

In BeagleIM XML log you can find this: 
`<vcard xmlns='urn:ietf:params:xml:ns:vcard-4.0'/>`

In ejabberd I've configured `mod_version: {}` which does XEP-0092, so no vcard4. 

Because Beagle/Siskin are one of the rare macOS/IOS clients, it would be good when the server-side support for those clients would be as good as possible. Editing the user profile is most likely one of the things that user want to do, like uploading avatar pics and such.

**Comment by licaon-kter** [comment] 2020-07-09 21:03
What does ejabberd.log say?

Avatars are handled via `mod_avatar`

**Comment by ingoj** [comment] 2020-07-10 05:59
Of course, mod_avatar is configured as well... 

ejabberd.log: 
```
2020-07-10 07:55:25.456 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_recv: mod_stream_mgmt:c2s_handle_recv/3
2020-07-10 07:55:25.456 [info] <0.8633.4> (tls|<0.8633.4>) Received XML on stream = <<"<iq type='get' id='34F28A5C-7C70-4707-A602-0F47803E4C6C'><vcard xmlns='urn:ietf:params:xml:ns:vcard-4.0'/></iq>">>
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_authenticated_packet: mod_client_state:c2s_authenticated_packet/2
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_authenticated_packet: mod_stream_mgmt:c2s_authenticated_packet/2
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_send_packet: mod_privacy:user_send_packet/1
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_send_packet: mod_vcard_xupdate:user_send_packet/1
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_send_packet: mod_caps:user_send_packet/1
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_send_packet: mod_mam:user_send_packet/1
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_send_packet: mod_carboncopy:user_send_packet/1
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_send_packet: mod_ping:user_send/1
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_send_packet: mod_mam:user_send_packet_strip_tag/1
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook privacy_check_packet: mod_pres_counter:check_packet/4
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook privacy_check_packet: mod_last:privacy_check_packet/4
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook privacy_check_packet: mod_privacy:check_packet/4
2020-07-10 07:55:25.457 [debug] <0.8633.4>@ejabberd_router:do_route:384 Route:
2020-07-10 07:55:25.458 [debug] <0.8633.4>@ejabberd_local:route:74 Local route:
2020-07-10 07:55:25.458 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook sm_receive_packet: mod_mam:sm_receive_packet/1
2020-07-10 07:55:25.458 [debug] <0.8633.4>@ejabberd_sm:do_route:712 Processing IQ to bare JID:
2020-07-10 07:55:25.459 [debug] <0.8633.4>@ejabberd_router:do_route:384 Route:
2020-07-10 07:55:25.459 [debug] <0.8633.4>@ejabberd_local:route:74 Local route:
2020-07-10 07:55:25.459 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook sm_receive_packet: mod_mam:sm_receive_packet/1
2020-07-10 07:55:25.460 [debug] <0.8633.4>@ejabberd_sm:do_route:719 Processing packet to full JID:
2020-07-10 07:55:25.460 [debug] <0.8633.4>@ejabberd_sm:do_route:741 Sending to process <0.8633.4>:
2020-07-10 07:55:25.460 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_info: ejabberd_sm:c2s_handle_info/2
2020-07-10 07:55:25.460 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_info: mod_offline:c2s_handle_info/2
2020-07-10 07:55:25.461 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_info: mod_pubsub:c2s_handle_info/2
2020-07-10 07:55:25.461 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_info: mod_push_keepalive:c2s_handle_info/2
2020-07-10 07:55:25.461 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_info: mod_stream_mgmt:c2s_handle_info/2
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_info: ejabberd_c2s:process_info/2
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook privacy_check_packet: mod_pres_counter:check_packet/4
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook privacy_check_packet: mod_last:privacy_check_packet/4
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook privacy_check_packet: mod_privacy:check_packet/4
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_receive_packet: mod_caps:user_receive_packet/1
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_receive_packet: mod_mam:user_receive_packet/1
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook user_receive_packet: mod_carboncopy:user_receive_packet/1
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_chat_states/1
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_pep/1
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_presence/1
2020-07-10 07:55:25.464 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_other/1
2020-07-10 07:55:25.464 [debug] <0.8633.4>@mod_client_state:filter_other:314 Won't add stanza for ij@nerdwind.de/12021558899164873646551922 to CSI queue
2020-07-10 07:55:25.464 [debug] <0.8633.4>@mod_client_state:dequeue_sender:365 Flushing packets of ij@nerdwind.de from CSI queue of ij@nerdwind.de/12021558899164873646551922
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_push:c2s_stanza/3
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_push_keepalive:c2s_stanza/3
2020-07-10 07:55:25.465 [info] <0.8633.4> (tls|<0.8633.4>) Send XML on stream = <<"<iq xml:lang='en' to='ij@nerdwind.de/12021558899164873646551922' from='ij@nerdwind.de' type='error' id='34F28A5C-7C70-4707-A602-0F47803E4C6C'><vcard xmlns='urn:ietf:params:xml:ns:vcard-4.0'/><error code='503' type='cancel'><service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xml:lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>No module is handling this query</text></error></iq>">>
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_stream_mgmt:c2s_handle_send/3
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_chat_states/1
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_pep/1
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_presence/1
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_filter_send: mod_client_state:filter_other/1
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_push:c2s_stanza/3
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_push_keepalive:c2s_stanza/3
2020-07-10 07:55:25.465 [info] <0.8633.4> (tls|<0.8633.4>) Send XML on stream = <<"<r xmlns='urn:xmpp:sm:3'/>">>
2020-07-10 07:55:25.465 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_send: mod_stream_mgmt:c2s_handle_send/3
2020-07-10 07:55:25.764 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_handle_recv: mod_stream_mgmt:c2s_handle_recv/3
2020-07-10 07:55:25.764 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_authenticated_packet: mod_client_state:c2s_authenticated_packet/2
2020-07-10 07:55:25.764 [debug] <0.8633.4>@ejabberd_hooks:safe_apply:231 Running hook c2s_authenticated_packet: mod_stream_mgmt:c2s_authenticated_packet/2
2020-07-10 07:55:25.765 [debug] <0.8633.4>@mod_stream_mgmt:check_h_attribute:479 ij@nerdwind.de/12021558899164873646551922 acknowledged 40 of 40 stanzas
2020-07-10 07:55:25.765 [info] <0.8633.4> (tls|<0.8633.4>) Received XML on stream = <<"<a xmlns='urn:xmpp:sm:3' h='40'/>">>
```

**Comment by lovetox** [comment] 2020-08-13 13:38
maybe the clients should just publish the vcard to pubsub and not depend on the server doing that for them

The XEP does not describe that, but its obvious that this is possible, and probably the better choice

**Comment by lovetox** [comment] 2022-08-01 20:09
Also probably a duplicate of https://github.com/processone/ejabberd/issues/3535

**Comment by Neustradamus** [comment] 2022-08-12 15:38
@badlop, @prefiks: Can you look?

**Closed** 2022-08-13 08:57 UTC
Labels: Kind:Feature, Component:VCard
