### ISSUE TITLE
mod_announce

### ISSUE THREAD

**Issue by heelll-boooy** [processone/ejabberd#4082] opened 2023-08-16 12:58 UTC
## Environment
- ejabberd version: 23.4
- Erlang version: `Erlang/OTP 26
- OS: Linux (Ubuntu) 22.4
- Installed from: source 
loglevel: 4
## Errors from error.log/crash.log
No errors
## Bug description
Hello
I'm installing Egaberd and everything is fine.
But iM Set MOTD
It sends the message only once and not at every login
Is there anything else I can do besides that?
Thank you

**Comment by licaon-kter** [comment] 2023-08-16 13:14
Gist of config?

Exact commands? 

Error logs?

**Comment by prefiks** [comment] 2023-08-16 13:24
I believe this works that by design, we send only one motd to a user, only when motd is updated this state will be reset.

**Comment by heelll-boooy** [comment] 2023-08-16 13:52
@licaon-kter
Gist of config?
This is my config in :
/usr/local/etc/ejabberd/ejabberd.yml
access_rules:
  announce:
    allow: admin
modules:
  mod_adhoc: {}
  mod_announce:
    access: announce

Exact commands?
im set motd from services discover

Error logs?
no error logs

**Comment by heelll-boooy** [comment] 2023-08-16 13:53
@prefiks
no 
It should be sent on every login

**Comment by badlop** [comment] 2023-08-16 16:08
> It should be sent on every login

Where did you read that? 

https://xmpp.org/extensions/xep-0133.html#set-motd says:

> is delivered to any user who logs in to the server that day (e.g., to announce service changes)

It does not imply that it should be sent several times to the same account on every login, only the first time an account logins, right?

**Comment by heelll-boooy** [comment] 2023-08-16 18:20
Hello @badlop
Thank you for your help
I quit the internet a long time ago and now I'm back to working on it
I'm sorry I was working on Ejabberd version 2.13 and this was possible
Now this is impossible
Thank you again

**Comment by Neustradamus** [comment] 2023-08-21 04:57
@heelll-boooy: version 2.13?

**Comment by heelll-boooy** [comment] 2023-08-23 08:05
@Neustradamus 
Yes

**Comment by Neustradamus** [comment] 2023-08-23 10:52
@heelll-boooy: ejabberd 2.1.3?
From 2010?, 13 years old?

**Comment by heelll-boooy** [comment] 2023-08-27 16:41
@Neustradamus yes

**Comment by badlop** [comment] 2023-08-28 18:40
Let's look at mod_announce.erl source code the first time it was committed to this repository in August 2004. This code is 19 years old:

https://github.com/processone/ejabberd/commit/d77a936b322220a67e703525ff585660ea8da670#diff-7c1b24018ecd77c08239a6c246a397ed87c6bc382fdb3a087444856407e534b6R161-R177

When a client logins to the server, `send_motd` checks if there is a MOTD to send. In that case, it **checks if that user has already received the MOTD**, in that case it does nothing. If the user didn't yet receive the MOTD, it sends the message and then **takes note that this user has already received this MOTD**. All this is only removed when the admin updates the MOTD.

If you found an ejabberd version that didn't behave like this, then it was a bug that got fixed.

**Closed** 2023-10-05 10:16 UTC
Labels: Note:Discussion
