### ISSUE TITLE
mod_http_upload_quota: Cannot open document root /var/lib/ejabberd/upload: no such file or directory

### ISSUE THREAD

**Issue by IUnderstandLetsChangeMyUsername** [processone/ejabberd#1251] opened 2016-08-16 11:48 UTC
> What version of ejabberd are you using?

16.08.

> What operating system (version) are you using?

Debian Jessie.

> How did you install ejabberd (source, package, distribution)?

Debian testing repository.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

There is one error in the `error.log`:

`2016-08-16 12:29:27.618 [error] <0.1140.0>@mod_http_upload_quota:handle_info:234 Cannot open document root /var/lib/ejabberd/upload: no such file or directory`

and the `mod_http_upload_quota` configured as such:

```
 mod_http_upload_quota:
    max_days: 92
```

`access_hard_quota` and `access_soft_quota` options are not set. This is not a proper setting or this error is some bug?

**Comment by weiss** [comment] 2016-08-16 11:56
I guess the message is correct in the sense that no `/var/lib/ejabberd/upload` directory exists; simply because nothing was uploaded so far?  In that case, everything is fine; so we should probably change that into a `[warning]` or `[info]` message.

**Comment by IUnderstandLetsChangeMyUsername** [comment] 2016-08-16 13:04
Well, there was stuff uploaded, but to another directory specified in   `mod_http_upload`'s `docroot` option, which is not `/var/lib/ejabberd/upload`.

**Comment by weiss** [comment] 2016-08-16 13:48
There was such a bug in ejabberd versions up to 16.06, but that was fixed in 16.08 (see #1025), and I can't reproduce it (I tested things again just to be sure).  The line number in your error message (234) also strongly indicates that you're not actually using the 16.08 version of `mod_http_upload_quota`.  

I'll close this issue, but feel free to reopen it if you can actually reproduce the problem with 16.08.

**Closed by weiss** 2016-08-16 13:48 UTC

**Comment by IUnderstandLetsChangeMyUsername** [comment] 2016-08-16 14:21
You're right, this was the error in the log when ejabberd ran 16.06. On 16.08 it's gone.
