### ISSUE TITLE
Room creation time is not properly set in DB

### ISSUE THREAD

**Issue by logicwonder** [processone/ejabberd#3849] opened 2022-06-17 10:02 UTC
## Environment

- ejabberd version: 22.05
- Erlang version: 12.3.1
- OS: Linux (Debian)
- Installed from: source 

## Errors from error.log/crash.log

No errors

## Bug description

After upgrated to eJabberd 22.05, on creating a new MUC room, the created_at colum in muc_room table (PostgreSQL) is always set to value "1970-01-02 00:00:00.000".
We have verified our server time in both eJabberd and PostgreSQL DB and time was found correct.

In users table created_at column has the correct time is getting stored in created_at on user registration.

**Comment by prefiks** [comment] 2022-06-17 11:07
That's by design, this field was reused to mark room hibernation time

**Comment by logicwonder** [comment] 2022-06-18 09:14
What is the significance of "1970-01-02 00:00:00.000" as hibernation time? 

And any reason why hibernation_time in rom opts was not used in this case?

[{title,<<>>},{description,<<>>},{allow_change_subj,true},{allow_query_users,true}
,{allow_private_messages,true},{allow_private_messages_from_visitors,anyone},{allow_visitor_status,t
rue},{allow_visitor_nickchange,true},{public,true},{public_list,true},{persistent,true},{moderated,true},{
...
...
,{subject,[]},{subject_author,<<>>},{hats_users,[]},{**hibernation_time,undefined**}]

Date and time of room creation is a useful metadata. Please consider retaining the meaning of created_at column if the design permits it.

**Comment by prefiks** [comment] 2022-06-20 07:26
It just sentinel value for room that are not hibernated. This was done as part of optimization for commands  that delete unused rooms, having this as separate column allowed as to fetch only rooms that were hibernated, instead of all rooms, with 100k+ rooms that really made a difference.

**Comment by mremond** [comment] 2023-07-11 12:48
I am closing the issue as it seems @prefiks explanation clarifies the behaviour.

**Closed by mremond** 2023-07-11 12:48 UTC
