### ISSUE TITLE
`ejabberdctl reload-config` doesn't consider changes of sql_pool_size

### ISSUE THREAD

**Issue by rom1dep** [processone/ejabberd#2541] opened 2018-07-21 07:32 UTC
> What version of ejabberd are you using?

ejabberd 18.06

> What operating system (version) are you using?

Erlang/OTP 19 [erts-8.3.5.4] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:true]  on Fedora release 27 (Twenty Seven)

> How did you install ejabberd (source, package, distribution)?

git@0a40ab93c85b2070111914a9ee752a127bf5411e (source)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

ejabberdctl reload-config doesn't apply changes of `sql_pool_size`

**Comment by licaon-kter** [comment] 2019-01-18 16:13
I'm seeing this issue again, BTW.

ejabberd HEAD, OTP 21.2.2, Postgresql 11

**Comment by licaon-kter** [comment] 2019-01-20 22:18
More info, on reload it logs:
```
[error] <0.3047.0>@ejabberd_hooks:safe_apply:384 Hook config_reloaded crashed when running ejabberd_rdbms:config_reloaded/0:
** Reason = {error,{case_clause,{true,p1_pgsql}},[{ejabberd_rdbms,reload_host,1,[{file,"src/ejabberd_rdbms.erl"},{line,101}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{ejabberd_hooks,safe_apply,4,[{file,"src/ejabberd_hooks.erl"},{line,381}]},{ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,330}]},{ejabberd_ctl,call_command,4,[{file,"src/ejabberd_ctl.erl"},{line,352}]},{ejabberd_ctl,try_call_command,4,[{file,"src/ejabberd_ctl.erl"},{line,321}]},{ejabberd_ctl,process2,4,[{file,"src/ejabberd_ctl.erl"},{line,271}]},{ejabberd_ctl,process,2,[{file,"src/ejabberd_ctl.erl"},{line,249}]}]}
** Arguments = []
```

**Comment by badlop** [comment] 2019-01-21 12:30
That recent crash was introduced in 1b0d481f41bdb29cc6bbaf0d410aafed5280e337

**Comment by licaon-kter** [comment] 2019-01-21 21:21
@badlop That fixes it, thanks.

**Comment by licaon-kter** [comment] 2019-03-03 17:31
Since the posts above I've migrated to new hardware/software.

Now: arm64, OTP 21.2.5, Postgresql 11.2, ejabberd HEAD

I've setup `sql_pool_size` to 8 and restarted, so I saw 8 `postgres: 11/main: ejabberd ejabberd ::1(XXXXX) idle` processes, as expected.

Then I thought that since I have 4 cores maybe it's better to lower this to 4, so I did, then `reload_config`, but I forgot to check the process count for postgres.

Later I took a look and saw 16 of those, ok strange, lower pool to 1, reload, still 16. No errors in logs.

So, what am I misunderstanding exactly?

I'll restart later when the load is lower to test what happens.

**Comment by licaon-kter** [comment] 2019-03-04 08:22
After several restarts I still don't know why there are so many processes, I guess postgres changed something in 10/11.

**Comment by badlop** [comment] 2019-03-04 17:08
With MySQL it works correctly: when lowering the **sql_pool_size** option and running **reload_config**, ejabberd closes the unnecessary ports. For example, when lowering the option from 5 to 3, I see in the logs:
```
17:59:50.686 [info] p1_mysql_conn: Received close signal, exiting.
17:59:50.686 [info] Closing connection #Port<0.14874>: ok
17:59:50.686 [info] p1_mysql_conn: Received close signal, exiting.
17:59:50.686 [info] Closing connection #Port<0.14872>: ok
```
Two ports are closed at ejabberd, and the MySQL ones get some time at TIME_WAIT and after a few seconds are finally closed.

**Comment by zinid** [comment] 2019-03-04 21:28
@badlop yeah, same here, cannot reproduce the bug.

**Comment by licaon-kter** [comment] 2019-03-05 16:23
@badlop Is the PG back-end supposed to log such nice messages like `Received close signal, exiting... Closing connection` too? I never saw one at least on loglevel 4.

**Comment by badlop** [comment] 2019-03-06 19:26
As it worked correctly with MySQL, now I've installed PostgreSQL 10.5, ejabberd git, and Erlang/OTP 20: I can reproduce the behavior you mentioned: ports are kept open even when lowering the pool size!!

With this change the ports are explicitely closed, but maybe that "fix" is hiding the real reason for ports not being closed, as @zinid mentioned it's working for him...
```diff
--- a/src/ejabberd_sql.erl
+++ b/src/ejabberd_sql.erl
@@ -431,6 +431,7 @@ handle_info(Info, StateName, State) ->
 terminate(_Reason, _StateName, State) ->
     ejabberd_sql_sup:remove_pid(State#state.host, self()),
     case State#state.db_type of
+        pgsql -> catch pgsql:terminate(State#state.db_ref);
         mysql -> catch p1_mysql_conn:stop(State#state.db_ref);
         sqlite -> catch sqlite3:close(sqlite_db(State#state.host));
         _ -> ok
```

**Comment by licaon-kter** [comment] 2019-03-06 19:45
@badlop zinid tested on mysql too, as said in the MUC

But @rom1dep had PG11 too and it works ok for him, again as said in MUC

**Comment by rom1dep** [comment] 2019-03-06 22:15
> But @rom1dep <https://github.com/rom1dep> had PG11 too and it works ok
> for him, again as said in MUC
>
I do have the leak, though:
> rom1dep: just changed to 6, reload-config, remshed → 6, htop → 6
> rom1dep: back to 4, remsh gives 4, but htop lists 6

Upscaling does create the new connections, but reducing the count
afterwards doesn't free up the resources.
If I find the time I'll test the patch, not guarantees it'll be soon!

**Comment by licaon-kter** [comment] 2019-03-06 22:54
@badlop using that patch on top or 19.02.10
* PG11 still has `sql_pool_size * 2` processes
* but it upscales and downscales on `reload_config` as expected

Sometimes on downscale will do this:
```
[error] <0.416.0> gen_server <0.416.0> terminated with reason: tcp_close
[error] <0.416.0> CRASH REPORT Process <0.416.0> with 0 neighbours exited with reason: tcp_close in gen_server:handle_common_reply/8 line 751
```

**Comment by licaon-kter** [comment] 2019-08-24 01:53
This looks fixed to me on HEAD (https://github.com/processone/ejabberd/commit/1fd75265d6c28ccae1bb3b2aa53c858984f29053), not sure which commit did it as iirc I tested https://github.com/processone/ejabberd/commit/d796dcace5059c6825288a416a946acfd4cc33b4 and that didn't. Then again there where some PG upgrades as well, current 11.5.

@rom1dep Can you confirm?

**Comment by licaon-kter** [comment] 2020-02-27 01:59
Seeing again on HEAD (47c5aba1e5623e42b40c9ad66b45b7d5da53fce7)
* PG11.7 has `sql_pool_size * 2` processes
* but it upscales and downscales on `reload_config` as expected

Note that I didn't keep track of it, just noticed it now, maybe it happens for a while.

**Comment by mremond** [comment] 2020-02-27 09:38
@licaon-kter Not sure I get what you mean.
Do you mean all is working fine now ?

Thanks !

**Comment by licaon-kter** [comment] 2020-02-27 09:47
No, it misbehaves again.

**Comment by mremond** [comment] 2020-02-27 09:49
@licaon-kter Are the error in the log the same ? Different error ?

**Comment by licaon-kter** [comment] 2020-02-27 10:14
@mremond Nothing is logged at `loglevel: 4`, just reloads as expected.

**Comment by badlop** [comment] 2021-03-18 15:21
A few days ago I committed my old small patch (https://github.com/processone/ejabberd/issues/2541#issuecomment-470242146), but Travis has confirmed what @licaon-kter mentioned (https://github.com/processone/ejabberd/issues/2541#issuecomment-470310340). So I've reverted that patch...

And noticed that this problem is in fact solved since ejabberd 19.08! Here is the good solution: https://github.com/processone/ejabberd/commit/209f5d32e198416b62ef18407dd04138a44bd4ad

**Closed** 2021-03-18 15:25 UTC
Labels: Component:Configuration, Component:Databases, Level:Starter

**Comment by licaon-kter** [comment] 2021-03-18 15:40
So this is correct?
```
$ sudo -u ejabberd grep pool ejabberd.yml
sql_pool_size: 2
$ ps aux|grep idle
postgres     945  0.0  7.8 271184 77172 ?        Ss   mar16   1:21 postgres: 11/main: ejabberd ejabberd 127.0.0.1(34121) idle
postgres     946  0.0  7.2 271176 71384 ?        Ss   mar16   1:19 postgres: 11/main: ejabberd ejabberd 127.0.0.1(51805) idle
postgres     947  0.0  0.3 269324  3756 ?        Ss   mar16   0:00 postgres: 11/main: ejabberd ejabberd 127.0.0.1(38741) idle
postgres     948  0.0  0.3 269276  3752 ?        Ss   mar16   0:00 postgres: 11/main: ejabberd ejabberd 127.0.0.1(60073) idle
$ sudo -u ejabberd ejabberdctl status
The node ejabberd@localhost is started with status: started
ejabberd 21.01.64 is running in that node
```

**Comment by prefiks** [comment] 2021-03-18 17:07
@licaon-kter

You have only one host defined? With that setup it will be 2 connection per host, so if you have two then this is expected.

**Comment by badlop** [comment] 2021-03-18 17:07
I can't reproduce that problem. With that ejabberd version, after changing sql_pool_size in ejabberd.yml and running "reload_config", the ps aux almost immediately shows that same number. I repeat this several times, both increasing and decreasing the pool size, and the processes are correctly killed or started as required.

Did you reload_config?

**Comment by prefiks** [comment] 2021-03-18 17:26
We start pool for each host separately, mostly because you can use separate server/database per host (and for old sql syntax you usually did do that) and in that case you had to have separate connection. So that was somewhat expected to work that way.

**Comment by badlop** [comment] 2021-03-18 17:31
> This is not documented, right?

It is:

> sql_pool_size
Size
A number of connections to the SQL server. By default ejabberd opens 10 connections to the database **_for each virtual host._** WARNING: for SQLite this value is 1 by default and it’s not recommended to change it due to potential race conditions.

https://docs.ejabberd.im/admin/configuration/toplevel/#sql-pool-size

**Comment by licaon-kter** [comment] 2021-03-18 17:46
I've missed that then, thanks

**Comment by badlop** [comment] 2021-03-18 17:57
Now that we are here, I guess the explanation could be improved. Maybe something like?

> Number of connections to the SQL server that ejabberd will open for each virtual host. The default value is 10 connections to the database per host.

**Comment by licaon-kter** [comment] 2021-03-18 18:27
Sounds good
