### ISSUE TITLE
Certificate installation giving error in ejabberd windows

### ISSUE THREAD

**Issue by sinsharat** [processone/ejabberd#2778] opened 2019-01-25 09:31 UTC
**Is your feature request related to a problem? Please describe.**
I have been trying to setup certificate for my windows machine.

In order to do that i tried the below steps:
1. openssl req -new -x509 -newkey rsa:1024 -days 3650 -keyout privkey.pem -out server.pem
-- used the passphrase "pass" and also tried with "ejabberd"
2. openssl rsa -in privkey.pem -out privkey.pem
3. copy privkey.pem contents at the begining of server.pem

Specified the below config in ejabberd:
certfiles:
  - "C:/ProgramData/ejabberd/conf/server.pem"
  - "C:/ProgramData/ejabberd/conf/privkey.pem" (Tried by keeping as well as removing this line)

Started ejabberd.

Getting the below error:
`2019-01-25 14:58:24.361 [warning] <0.389.0>@ejabberd_pkix:log_warnings:397 Invalid certificate in c:/ProgramData/ejabberd/conf/server.pem: at line 16: self-signed certificate
2019-01-25 14:58:24.361 [error] <0.389.0> gen_server ejabberd_pkix terminated with reason: {{nif_not_loaded,fast_tls},[{erlang,nif_error,[{nif_not_loaded,fast_tls}],[]},{fast_tls,clear_cache_nif,0,[{file,"src/fast_tls.erl"},{line,132}]},{ejabberd_pkix,commit,0,[{file,"src/ejabberd_pkix.erl"},{line,270}]},{ejabberd_pkix,handle_call,3,[{file,"src/ejabberd_pkix.erl"},{line,169}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-01-25 14:58:24.376 [error] <0.389.0> CRASH REPORT Process ejabberd_pkix with 0 neighbours crashed with reason: {{nif_not_loaded,fast_tls},[{erlang,nif_error,[{nif_not_loaded,fast_tls}],[]},{fast_tls,clear_cache_nif,0,[{file,"src/fast_tls.erl"},{line,132}]},{ejabberd_pkix,commit,0,[{file,"src/ejabberd_pkix.erl"},{line,270}]},{ejabberd_pkix,handle_call,3,[{file,"src/ejabberd_pkix.erl"},{line,169}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
2019-01-25 14:58:24.376 [error] <0.80.0>@ejabberd_hooks:safe_apply:384 Hook ejabberd_started crashed when running ejabberd_pkix:ejabberd_started/0:
** Reason = {exit,{{{nif_not_loaded,fast_tls},[{erlang,nif_error,[{nif_not_loaded,fast_tls}],[]},{fast_tls,clear_cache_nif,0,[{file,"src/fast_tls.erl"},{line,132}]},{ejabberd_pkix,commit,0,[{file,"src/ejabberd_pkix.erl"},{line,270}]},{ejabberd_pkix,handle_call,3,[{file,"src/ejabberd_pkix.erl"},{line,169}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]},{gen_server,call,[ejabberd_pkix,ejabberd_started,60000]}},[{gen_server,call,[{file,"gen_server.erl"},{line,223}],3},{ejabberd_hooks,safe_apply,[{file,"src/ejabberd_hooks.erl"},{line,380}],4},{ejabberd_hooks,run1,[{file,"src/ejabberd_hooks.erl"},{line,329}],3},{ejabberd_app,start,[{file,"src/ejabberd_app.erl"},{line,58}],2},{application_master,start_it_old,[{file,"application_master.erl"},{line,277}],4}]}
** Arguments = []
2019-01-25 14:58:24.376 [info] <0.80.0>@ejabberd_app:start:60 ejabberd 18.12 is started in the node ejabberd@localhost in 6.36s
2019-01-25 14:58:24.376 [error] <0.365.0> Supervisor ejabberd_sup had child ejabberd_pkix started with ejabberd_pkix:start_link() at <0.389.0> exit with reason {{nif_not_loaded,fast_tls},[{erlang,nif_error,[{nif_not_loaded,fast_tls}],[]},{fast_tls,clear_cache_nif,0,[{file,"src/fast_tls.erl"},{line,132}]},{ejabberd_pkix,commit,0,[{file,"src/ejabberd_pkix.erl"},{line,270}]},{ejabberd_pkix,handle_call,3,[{file,"src/ejabberd_pkix.erl"},{line,169}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,661}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,690}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]} in context child_terminated`

**Describe the solution you'd like**
Need ejabberd to validate the certificate without any issue.

**Describe alternatives you've considered**
Already specifie above.

**Additional context**

**Comment by zinid** [comment] 2019-01-25 09:38
Duplicate of #2745

**Closed by zinid** 2019-01-25 09:38 UTC

**Comment by sinsharat** [comment] 2019-01-25 09:43
@zinid i don't think this is the same issue as #2745 as its got no issue with not able to read the file. Its got something to do with classifying it as invalid certificate.
Will appriciate if you could help me with this,
Thank you.

**Comment by zinid** [comment] 2019-01-25 09:47
Yes, the only part that doesn't work for you is loading of the TLS driver. Whatever certificate you use you won't be able to start the system, you need that bugfix.

**Comment by zinid** [comment] 2019-01-25 09:48
And regarding "self-signed certificate" issue. What did you expect? You generated a  self-signed certificate and ejabberd warns you about this.

**Comment by sinsharat** [comment] 2019-01-25 09:49
@zinid ok. Thank you for the explaination.
