### ISSUE TITLE
PubSub: Owner can not purge their own nodes completely

### ISSUE THREAD

**Issue by ejbravo** [processone/ejabberd#2231] opened 2018-01-17 10:55 UTC
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

CentOS 7

> How did you install ejabberd (source, package, distribution)?

RPM package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behaviour? What was the expected result?

When the owner of a PubSub node purges it, there are some items that remain on it. Even receiving a 'result' stanza from the service which says that everything is ok.
Do you know the reason for this unexpected behaviour?

Thanks in advance

**Comment by cromain** [comment] 2018-01-18 13:37
what is pubsub configuration and backend ?

**Comment by ejbravo** [comment] 2018-01-18 15:10
The backend that I use is Mnesia and Settings that I have amended from default node configuration are:
- deliver_notifications: true
- deliver_payloads: true
- persist_items: true
- access_model: 'open'
- publish_model: 'open'
- send_last_published_item: 'never'
- notification_type: 'headline'
- notify_config: false
- notify_delete: false
- notify_retract: true
- notify_sub: true
- itemreply: 'publisher'

**Comment by ejbravo** [comment] 2018-01-22 09:53
It seems that this issue has a relationship with cluster functioning or how the service stores items. I have noticed this unexpected behaviour only happens when publishers are connected to different hosts of the same cluster. In this case, when node's owner purges it some items give back the message 'forbidden'. However, if every publisher writes their items on the same host, node's owner does not have any problem when he tries to purge it completely.

I hope this helps you to solve this issue. Thanks.

**Comment by ejbravo** [comment] 2018-01-22 15:07
More info about this issue:
I had amended on ejabberd.schema the **storage type** of table _pubsub_item_ to **disc_copies** (disc only copy)

**Comment by cromain** [comment] 2018-03-16 13:44
I assume you correctly setup your cluster using join_cluster command.
when running on cluster, what is output of following debug commands: 
mnesia:table_info(pubsub_node,all).
mnesia:table_info(pubsub_item,all).

**Comment by ejbravo** [comment] 2018-03-16 14:51
Exactly, the cluster is well configured.

The outputs that you have requested are the next ones, where I have replaced real IPs by HOST_A and HOST_B:

`mnesia:table_info(pubsub_node,all).`

[{access_mode,read_write},
 {active_replicas,['ejabberd@ip-HOST_A',
                   'ejabberd@ip-HOST_B']},
 {all_nodes,['ejabberd@ip-HOST_A',
             'ejabberd@ip-HOST_B']},
 {arity,7},
 {attributes,[nodeid,id,parents,type,owners,options]},
 {checkpoints,[]},
 {commit_work,[{index,set,
                      [{{3,ordered},
                        {ram,#Ref<0.1477980353.2045640705.256815>}}]}]},
 {cookie,{{1516105719404158031,-576460752303422799,1},
          'ejabberd@ip-HOST_B'}},
 {cstruct,{cstruct,pubsub_node,set,[],
                   ['ejabberd@ip-HOST_A','ejabberd@ip-HOST_B'],
                   [],[],0,read_write,false,
                   [{3,ordered}],
                   [],false,pubsub_node,
                   [nodeid,id,parents|...],
                   [],[],[],...}},
 {disc_copies,['ejabberd@ip-HOST_A',
               'ejabberd@ip-HOST_B']},
 {disc_only_copies,[]},
 {external_copies,[]},
 {frag_properties,[]},
 {index,[3]},
 {index_info,{index,set,
                    [{{3,ordered},{ram,#Ref<0.1477980353.2045640705.256815>}}]}},
 {load_by_force,false},
 {load_node,'ejabberd@ip-HOST_B'},
 {load_order,0},
 {load_reason,local_only},
 {local_content,false},
 {majority,false},
 {master_nodes,[]},
 {memory,1012},
 {ram_copies,[]},
 {record_name,pubsub_node},
 {record_validation,{pubsub_node,...}},
 {size,5},
 {snmp,...},
 {...}|...]

` mnesia:table_info(pubsub_item,all).`

 [{access_mode,read_write},
 {active_replicas,['ejabberd@ip-HOST_A',
                   'ejabberd@ip-HOST_B']},
 {all_nodes,['ejabberd@ip-HOST_A',
             'ejabberd@ip-HOST_B']},
 {arity,6},
 {attributes,[itemid,nodeidx,creation,modification,payload]},
 {checkpoints,[]},
 {commit_work,[{index,set,
                      [{{3,ordered},
                        {ram,#Ref<0.1477980353.2045640705.258441>}}]}]},
 {cookie,{{1516105719411351764,-576460752303422703,1},
          'ejabberd@ip-HOST_B'}},
 {cstruct,{cstruct,pubsub_item,set,[],
                   ['ejabberd@ip-HOST_A','ejabberd@ip-HOST_B'],
                   [],[],0,read_write,false,
                   [{3,ordered}],
                   [],false,pubsub_item,
                   [itemid,nodeidx,creation|...],
                   [],[],[],...}},
 {disc_copies,['ejabberd@ip-HOST_A',
               'ejabberd@ip-HOST_B']},
 {disc_only_copies,[]},
 {external_copies,[]},
 {frag_properties,[]},
 {index,[3]},
 {index_info,{index,set,
                    [{{3,ordered},{ram,#Ref<0.1477980353.2045640705.258441>}}]}},
 {load_by_force,false},
 {load_node,'ejabberd@ip-HOST_B'},
 {load_order,0},
 {load_reason,local_only},
 {local_content,false},
 {majority,false},
 {master_nodes,[]},
 {memory,924},
 {ram_copies,[]},
 {record_name,pubsub_item},
 {record_validation,{pubsub_item,...}},
 {size,5},
 {snmp,...},
 {...}|...]

**Comment by cromain** [comment] 2018-03-19 10:15
I think there is possibly something wrong around management of orphaned items.
pubsub_orphan table was added recently, and possibly after you configured your cluster. If this table is not replicated this can lead to orphaned items not being removed.
what is output of this same command for pubsub_orphan table:
mnesia:table_info(pubsub_orphan,all).

**Comment by ejbravo** [comment] 2018-03-19 11:42
Thank you. The output of that command is:

[{access_mode,read_write},
 {active_replicas,['HOST_A',
                   'HOST_B']},
 {all_nodes,['HOST_A',
             'HOST_B']},
 {arity,3},
 {attributes,[nodeid,items]},
 {checkpoints,[]},
 {commit_work,[]},
 {cookie,{{1516105719419767293,-576460752303422270,1},
          'HOST_B'}},
 {cstruct,{cstruct,pubsub_orphan,set,[],
                   ['HOST_A','HOST_B'],
                   [],[],0,read_write,false,[],[],false,pubsub_orphan,
                   [nodeid,items],
                   [],[],[],...}},
 {disc_copies,['HOST_A',
               'HOST_B']},
 {disc_only_copies,[]},
 {external_copies,[]},
 {frag_properties,[]},
 {index,[]},
 {index_info,{index,set,[]}},
 {load_by_force,false},
 {load_node,'HOST_B'},
 {load_order,0},
 {load_reason,local_only},
 {local_content,false},
 {majority,false},
 {master_nodes,[]},
 {memory,1089},
 {ram_copies,[]},
 {record_name,pubsub_orphan},
 {record_validation,{pubsub_orphan,...}},
 {size,3},
 {snmp,...},
 {...}|...]

**Comment by cromain** [comment] 2018-03-19 13:35
that's really odd as replication looks correctly enabled there. i'm investigating what else can be wrong but i'm pretty sure this is an issue with orphaned items. note: pubsub_orphan table is a dirty hack using mnesia backend, because mnesia lacks "on delete cascade" feature we are using with sql backend.

last question, what says this command (should reply true if sync is good):
{[R1,R2],_}=ejabberd_cluster:multicall(mnesia,dirty_all_keys,[pubsub_orphan]).
R1==R2.

**Comment by ejbravo** [comment] 2018-03-19 14:44
It seems that sync is OK as well, the answer is TRUE

`{[R1,R2],_}=ejabberd_cluster:multicall(mnesia,dirty_all_keys,[pubsub_orphan]).`
{[[1,4,2],[1,4,2]],[]}

`R1==R2.`
true

**Comment by cromain** [comment] 2018-03-22 14:48
I could not reproduce for now, moving to 18.04 as i'll need more investigations on this.

**Comment by cromain** [comment] 2018-03-22 15:17
the "not removed items" may have been posted by removed users.
this issue was fixed in #2129
you can check item publishers (after node_purge) using this hack, assuming purged node name is 'test' and domain is 'localhost':
{code}
> mnesia:dirty_read(pubsub_node,{<<"pubsub.localhost">>,<<"test">>}).
[{pubsub_node,{<<"pubsub.localhost">>,<<"test">>},
              1,[],<<"flat">>, …
{code}
you need to keep the Nidx, which is 2nd element of pubsub_node record, here it's integer 1. then get the remaining items of the node:
{code}
> mnesia:dirty_match_object({pubsub_item,'_',1,'_','_','_'}).
[{pubsub_item,{<<"5F1B2911178E3">>,1},
              1,
              {{1521,731409,96594},{<<"test1">>,<<"localhost">>,<<>>}},
              {{1521,731409,96594},{<<"test1">>,<<"localhost">>,<<"tablet">>}},
              …
{code}
Here you see test1@localhost published the item. Is that user still registered user in your case ?

if Yes -> I need to continue investigations
if No -> The issue is fixed by #2129

**Comment by ejbravo** [comment] 2018-03-23 09:17
I am afraid that this issue is not still solved. Let me show you my test results. Once I had purged the node "test", I checked your commands:

_Request_: `mnesia:dirty_read(pubsub_node,{<<"pubsub.localhost">>,<<"test">>}).`
_Response_: [{pubsub_node,{<<"pubsub.localhost">>,
               <<"test">>},
              3,[],<<"flat">>, (...) 

_Request_: `mnesia:dirty_match_object({pubsub_item,'_',3,'_','_','_'}).`
_Response_: [{pubsub_item,{<<"item1">>,3},
              3,
              {{1521,793333,992964},{<<"publisher1">>,<<"localhost">>,<<>>}},
              {{1521,793718,930171},{<<"publisher1">>,<<"localhost">>,<<"resource1">>}},
              (...)

After doing this I checked registered users as well, just in case, even knowing that none user had been removed. The user "publisher1" was still registered.

I would like to emphasise one of my old comments, I really think that this issue has a relationship with the cluster configuration, because I have checked hosts where publishers have been registered and I can say that cluster does not work as expected. Let me explain you an example. Forgetting "purge" operation. When a user, who has been registered in host_A of cluster, publishes one item (X) in node 'test' and time after, the same user (this time being logged in host_B of cluster) tries to update that item (X), the system responses an error message which says 'forbidden'. However, if that user is logged in host_A, will be able to update the item (X) without any problem. Moreover, if the publisher tries to remove that item logged in host_B, the result will be another error, 'item-not-found', but the item is still in node 'test' of pubsub.

I hope you can use this information in your investigations. Thanks in advance, I really appreciate your help with this issue.

**Comment by ejbravo** [comment] 2018-04-12 15:10
Hi, may I know if there is any new information on this issue? Have you been able to replicate the behaviour which is described in my last post? If you require any further information to do it, please, do not hesitate to ask me.

**Comment by cromain** [comment] 2018-04-17 12:05
i have enough infos here, i just need to get some time to dig into that problem in coming days

**Comment by cromain** [comment] 2018-04-24 13:56
this error is due to a race. only node creation and node deletion are "pure" transactions.
purge_node is "sync_dirty", this means if owner A send purge from cluster node 1, and user B publish item at same time from cluster node 2, that item can remains even if A received iq response a bit later because purge does several async operation on pubsub tables:
1- it gets all related affiliations for that node, as they contains index of related items
2- for every item, it delete the item and also rewrite the index
3- for every orphan item, it also delete them

Any publisher can publish item while 2 or 3 is running. due to its nature, purge_node should be a transaction as well.

**Comment by cromain** [comment] 2018-04-24 14:03
I could not reproduce the issue, (local machine and cluster too fast likely) but use of transaction will lock all nodes cluster wide while a purge is performed. So any publish from other node won't be executed at the same time and items index in publisher's state won't be lost in purge_node operation anymore.
The race is avoided. So i think this fix resolve that issue.

**Closed by cromain** 2018-04-24 14:03 UTC
Labels: Component:Pubsub
