### ISSUE TITLE
mod_pubsub odbc errors

### ISSUE THREAD

**Issue by sss123next** [processone/ejabberd#1633] opened 2017-03-23 16:11 UTC
> What version of ejabberd are you using?

17.03.beta-91

> What operating system (version) are you using?

Linux 4.10.1

> How did you install ejabberd (source, package, distribution)?

cave resovle -zx1 ejabberd (latest git  [ebuild](http://sss.chaoslab.ru/git/?p=sss_overlay.git;a=blob;f=net-im/ejabberd/ejabberd-scm.ebuild;h=add257fb3ecb2f38ed17202d6fb2511304a6a2b9;hb=d75f96dea025efec732ef8469ea9b3bb30e722f0))

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

```
017-03-23 18:50:09.396 [error] <0.824.0>@mod_pubsub:tree_action:3623 transaction return internal error: {aborted,{undef,[{node_pep_odbc_sql,options,[],[]},{nodetree_tree_sql,raw_to_node,2,[{file,"src/nodetree_tree_sql.erl"},{line,288}]},{nodetree_tree_sql,'-get_nodes/1-lc$^0/1-0-',2,[{file,"src/nodetree_tree_sql.erl"},{line,158}]},{nodetree_tree_sql,'-get_nodes/1-lc$^0/1-0-',2,[{file,"src/nodetree_tree_sql.erl"},{line,158}]},{mod_pubsub,tree_call,3,[{file,"src/mod_pubsub.erl"},{line,3609}]},{ejabberd_sql,execute_bloc,1,[{file,"src/ejabberd_sql.erl"},{line,495}]},{ejabberd_sql,run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,411}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]}}
2017-03-23 18:50:09.397 [error] emulator Error in process <0.824.0> on node ejabberd@localhost with exit value:
{function_clause,[{lists,foreach,[#Fun<mod_pubsub.148.110317955>,{error,{stanza_error,wait,500,<<>>,'internal-server-error',{text,<<"en">>,<<"Database failure">>},[]}}],[{file,"lists.erl"},{line,1337}]}]}

2017-03-23 18:51:01.136 [error] <0.827.0>@mod_pubsub:tree_action:3623 transaction return internal error: {aborted,{undef,[{node_pep_odbc_sql,options,[],[]},{nodetree_tree_sql,raw_to_node,2,[{file,"src/nodetree_tree_sql.erl"},{line,288}]},{nodetree_tree_sql,'-get_nodes/1-lc$^0/1-0-',2,[{file,"src/nodetree_tree_sql.erl"},{line,158}]},{nodetree_tree_sql,'-get_nodes/1-lc$^0/1-0-',2,[{file,"src/nodetree_tree_sql.erl"},{line,158}]},{mod_pubsub,tree_call,3,[{file,"src/mod_pubsub.erl"},{line,3609}]},{ejabberd_sql,execute_bloc,1,[{file,"src/ejabberd_sql.erl"},{line,495}]},{ejabberd_sql,run_sql_cmd,4,[{file,"src/ejabberd_sql.erl"},{line,411}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]}}
2017-03-23 18:51:01.137 [error] emulator Error in process <0.827.0> on node ejabberd@localhost with exit value:
{function_clause,[{lists,foreach,[#Fun<mod_pubsub.148.110317955>,{error,{stanza_error,wait,500,<<>>,'internal-server-error',{text,<<"en">>,<<"Database failure">>},[]}}],[{file,"lists.erl"},{line,1337}]}]}
```

error happened when pep node published with following response from server:
```

<iq xml:lang='ru' to='tst1@dark-alexandr.net/Gajim' from='tst1@dark-alexandr.net' type='error' id='71b0dc67-b305-4367-84f4-a929da887781'>
<pubsub xmlns='http://jabber.org/protocol/pubsub'>
<publish node='eu.siacs.conversations.axolotl.devicelist'>
<item>
<list xmlns='eu.siacs.conversations.axolotl'>
<device id='361565304'/>
</list>
</item>
</publish>
</pubsub>
<error code='403' type='auth'>
<forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</iq>

```

as result all pubsub/pep related features does not work...

i have manually removed all pubsub_ tables from db and re-run mysql.sql script to be sure what db structure are intact

i have following in ejabberd.yml:
```

default_db: sql

....

acl:
 local:
  user_regexp: ""

......

access:
  pubsub_createnode:
#    all: deny
    local: allow

.....

  mod_pubsub: 
    access_createnode: pubsub_createnode
#    ignore_pep_from_offline: false
#    last_item_cache: false
    plugins: 
      - "flat"
      - "hometree"
      - "pep"

```

**Comment by zinid** [comment] 2017-03-23 16:19
@cromain I see two problems here:
1) call to `node_pep_odbc_sql` module, not sure how this happens
2) `lists:foreach/2` is trying to iterate over `{error, stanza_error()}` term, which is wrong obviously (probably a regression after refactoring).

**Comment by sss123next** [comment] 2017-03-23 16:41
do you need more info ?

**Comment by zinid** [comment] 2017-03-23 16:53
So far no.

**Comment by cromain** [comment] 2017-03-23 17:24
It seems you were running 17.03.beta-91 with a pubsub_node table populated by a very old ejabberd (likely 2.1.x version). If you kept a dump of your old database, you can list faulty records like this:

select host,node from pubsub_node where type='pep_odbc'

1/ Such old records makes mod_pubsub call inexistent module node_pep_odbc_sql (instead of node_pep_sql). Old database must be altered, changing type 'pep' instead of 'pep_odbc', 'flat' instead of 'flat_odbc', and 'hometree' instead of 'hometree_odbc'

2/ I'm checking about the lists:foreach matches

**Comment by sss123next** [comment] 2017-03-23 17:40
yes, i have this type of records in database.
how can i update it to correct vaules ?
i am not sql expert....

**Comment by sss123next** [comment] 2017-03-23 17:53
i have updated type value in rows, error is gone, but pep still does not work

```
<!-- Out Чт 23 мар 2017 20:50:30 -->
<iq xmlns="jabber:client" type="set" id="101">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<publish node="http://jabber.org/protocol/activity">
<item id="0">
<activity xmlns="http://jabber.org/protocol/activity">
<working>
<in_a_meeting />
</working>
<text>00</text>
</activity>
</item>
</publish>
</pubsub>
</iq>

<!-- In Чт 23 мар 2017 20:50:37 -->
<iq xml:lang='ru' to='tst1@dark-alexandr.net/Gajim' from='tst1@dark-alexandr.net' type='error' id='101'>
<pubsub xmlns='http://jabber.org/protocol/pubsub'>
<publish node='http://jabber.org/protocol/activity'>
<item id='0'>
<activity xmlns='http://jabber.org/protocol/activity'>
<working>
<in_a_meeting/>
</working>
<text>00</text>
</activity>
</item>
</publish>
</pubsub>
<error code='403' type='auth'>
<forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</iq>

<!-- Out Чт 23 мар 2017 20:50:37 -->
<iq xmlns="jabber:client" type="set" id="a7d96315-9732-4697-8066-d2045b5575e4">
<pubsub xmlns="http://jabber.org/protocol/pubsub">
<publish node="eu.siacs.conversations.axolotl.devicelist">
<item>
<list xmlns="eu.siacs.conversations.axolotl">
<device id="361565304" />
</list>
</item>
</publish>
</pubsub>
</iq>


<!-- In Чт 23 мар 2017 20:50:39 -->
<iq xml:lang='ru' to='tst1@dark-alexandr.net/Gajim' from='tst1@dark-alexandr.net' type='error' id='a7d96315-9732-4697-8066-d2045b5575e4'>
<pubsub xmlns='http://jabber.org/protocol/pubsub'>
<publish node='eu.siacs.conversations.axolotl.devicelist'>
<item>
<list xmlns='eu.siacs.conversations.axolotl'>
<device id='361565304'/>
</list>
</item>
</publish>
</pubsub>
<error code='403' type='auth'>
<forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</iq>


```

**Comment by cromain** [comment] 2017-03-24 10:16
I can not reproduce your pep issue.
As you run latest ejabberd with a database generated by an old 2.1, please make sure you followed the entire upgrade process described in ejabberd documentation:
https://docs.ejabberd.im/admin/upgrade/

About function_clause on lists:foreach, this is expected to crash at that time (generated by tree_action when database backend is unknown or unsupported, this is side effect of having old 'pep_odbc' entries in pubsub_node table.

I'm closing this as i see no bug and could not reproduce pep issues. it's likely a data migration problem.

**Closed by cromain** 2017-03-24 10:16 UTC
Labels: Component:Databases, Component:Pubsub, Kind:Bug

**Comment by zinid** [comment] 2017-03-24 11:04
> About function_clause on lists:foreach, this is expected to crash at that time

I disagree, the function should have generated an internal-server error, but failed doing so because `lists:foreach/2` is used incorrectly.

**Comment by sss123next** [comment] 2017-03-24 15:36
i have executed all update scripts since 2.1 and still have this error (403 i mean), error in ejabberd.log gone after type update in pubsub_node

**Comment by sss123next** [comment] 2017-03-24 16:58
403 problem solved by manually removing all rows  in table on offline server.
