### ISSUE TITLE
How to setup mod_http_upload ?

### ISSUE THREAD

**Issue by Immakittycat** [processone/ejabberd#1736] opened 2017-05-19 08:02 UTC
> What version of ejabberd are you using?

17.03

> What operating system (version) are you using?

Windows 7

> How did you install ejabberd (source, package, distribution)?

Windows installer.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I would like to be able to transfer files through my Ejabberd server, with the receiver being offline.
Thus, I need to store the files on my server and, on connection of the receiver, send him the file.
To do so, I tried to install the "mod_http_upload" module, but I can't manage to get it to work.

Might someone help me configuring this ? You'll find my ejabberd.yml file attached to this post, whose with I get a 404 error every time I try to put something on the put_url defined there.

[ejabberd.txt](https://github.com/processone/ejabberd/files/1013527/ejabberd.txt)

**Comment by weiss** [comment] 2017-05-19 09:35
Remove the `host` option from the `mod_http_upload` configuration.

**Comment by Immakittycat** [comment] 2017-05-19 09:47
Tried it, unsuccesfully.
I still can't put the file. I also tried to use Gajim with its http_upload plugin to test the file transfer, and I always got the same "Service unavailable" error.

Any other idea ?
Thanks for your help !

**Comment by weiss** [comment] 2017-05-19 09:57
Any `[error]` messages in your ejabberd.log file?

If there aren't, could you grab the output from Gajim's XML Console while you issue the upload request?

**Comment by Immakittycat** [comment] 2017-05-19 11:31
I have no [error] messages in my ejabberd.log, only a [info] one : 

`2017-05-19 13:26:42.955 [info] <0.460.0>@mod_http_upload:create_slot:577 Got HTTP upload slot for bob@tech-ut16093cw/Gajim (file: Recherches.docx)`

On Gajim's XML console, here's what I get : 

```
<!-- Out 19/05/2017 13:26:37 -->
<iq xmlns="jabber:client" to="upload.tech-ut16093cw" type="get" id="b47bbdf8-abf1-47df-b8ba-657202bcee58">
<request xmlns="urn:xmpp:http:upload">
<filename>Recherches.docx</filename>
<size>236949</size>
<content-type>application/vnd.openxmlformats-officedocument.wordprocessingml.document</content-type>
</request>
</iq>

<!-- In 19/05/2017 13:26:37 -->
<iq xml:lang='fr' to='bob@tech-ut16093cw/Gajim' from='upload.tech-ut16093cw' type='result' id='b47bbdf8-abf1-47df-b8ba-657202bcee58'>
<slot xmlns='urn:xmpp:http:upload'>
<get>http://172.16.13.159:5443/upload/a5becd84ae2e1abf27892bea8bd80fa8b6bf3269/srpIyQlOXgqCsxvZzxYQfkJMThPATrYf9yeNZuvd/Recherches.docx</get>
<put>http://172.16.13.159:5443/upload/a5becd84ae2e1abf27892bea8bd80fa8b6bf3269/srpIyQlOXgqCsxvZzxYQfkJMThPATrYf9yeNZuvd/Recherches.docx</put>
</slot>
</iq>
```

Thanks for your help !

**Comment by weiss** [comment] 2017-05-19 11:47
So the problem is the HTTP (not the XMPP) communication.  I think the Gajim plugin prints debug output to stdout or stderr (so you'd see it if you start Gajim from a terminal).

Can you access `http://172.16.13.159:5443/upload/` from a browser?

**Comment by Immakittycat** [comment] 2017-05-19 11:58
Tried launching gajim.exe from the terminal, but it doesn't print me any error in there when I try to send the file. 
No, I cannot access the `http://172.16.13.159:5443/upload/ `page from my browsers.

**Comment by weiss** [comment] 2017-05-19 13:14
> No, I cannot access the `http://172.16.13.159:5443/upload/` page from my browsers.

What error message do you get?

**Comment by Immakittycat** [comment] 2017-05-19 13:18
"Not found" .

**Comment by weiss** [comment] 2017-05-19 13:28
Could you retry running Gajim from a terminal using the following command line?

    gajim -l gajim.plugin_system.httpupload=DEBUG

**Comment by Immakittycat** [comment] 2017-05-19 13:43
Tried it, but there's still nothing in my terminal.
The command launches Gajim but, when I'm trying to send a file, nothing gets written in the terminal.

**Comment by weiss** [comment] 2017-05-19 13:48
Could you check the following folder for a `gajim.log` file (replace `<user>` with your user name)?

    C:\Users\<user>\AppData\Roaming\Gajim

**Comment by Immakittycat** [comment] 2017-05-19 13:52
Here it is : 

```
crée le répertoire C:\Users\fblanc\AppData\Roaming\Gajim\Vcards
crée le répertoire C:\Users\fblanc\AppData\Roaming\Gajim\Avatars
crée le répertoire C:\Users\fblanc\AppData\Roaming\Gajim\Pluginsconfig
création de la base de donnée de l'historique
création de la base de donnée de cache
crée le répertoire C:\Users\fblanc\AppData\Roaming\Gajim\Certs
crée le répertoire C:\Users\fblanc\AppData\Roaming\Gajim\Localcerts
12/04/2017 14:01:25 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
12/04/2017 14:01:29 (E) gajim.c.resolver: Invalid host: _stun._udp.tech-ut16093cw
13/04/2017 08:40:25 (W) nbxmpp.dispatcher_nb: Unknown stanza: error
13/04/2017 08:44:45 (W) nbxmpp.dispatcher_nb: Unknown stanza: error
13/04/2017 08:49:05 (W) nbxmpp.dispatcher_nb: Unknown stanza: error
13/04/2017 08:53:26 (W) nbxmpp.dispatcher_nb: Unknown stanza: error
14/04/2017 09:34:07 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
18/04/2017 09:35:24 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
20/04/2017 10:12:27 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
20/04/2017 10:12:49 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.172.16.13.95
20/04/2017 10:12:52 (E) gajim.c.resolver: Invalid host: _stun._udp.172.16.13.95
04/05/2017 11:05:09 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.172.16.13.95
04/05/2017 11:05:36 (E) gajim.c.resolver: Invalid host: _stun._udp.172.16.13.95
04/05/2017 11:09:51 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.172.16.13.95
04/05/2017 11:09:54 (E) gajim.c.resolver: Invalid host: _stun._udp.172.16.13.95
19/05/2017 11:04:03 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.172.16.13.95
19/05/2017 11:04:36 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
19/05/2017 11:04:44 (E) gajim.c.resolver: Invalid host: _stun._udp.tech-ut16093cw
19/05/2017 11:13:40 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 11:13:54 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 11:16:34 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 11:16:48 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 11:17:17 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 11:19:03 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 11:25:08 (W) nbxmpp.dispatcher_nb: Unknown stanza: error
19/05/2017 13:26:17 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 13:26:58 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 13:52:49 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.172.16.13.95
19/05/2017 13:53:55 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
19/05/2017 13:53:58 (E) gajim.c.resolver: Invalid host: _stun._udp.tech-ut16093cw
19/05/2017 13:54:27 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
Logger gajim.plugin_system.httpupload level set to 10
19/05/2017 15:39:44 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
19/05/2017 15:39:48 (W) nbxmpp.dispatcher_nb: Unknown stanza: error
19/05/2017 15:39:48 (E) gajim.c.resolver: Invalid host: _stun._udp.tech-ut16093cw
19/05/2017 15:39:50 (I) gajim.plugin_system.httpupload: bob@tech-ut16093cw can do http uploads via component upload.tech-ut16093cw
Logger gajim.plugin_system.httpupload level set to 10
19/05/2017 15:40:03 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: False
19/05/2017 15:40:03 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: False
19/05/2017 15:40:03 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: False
19/05/2017 15:40:03 (E) gajim.c.resolver: Invalid host: _xmpp-client._tcp.tech-ut16093cw
19/05/2017 15:40:07 (E) gajim.c.resolver: Invalid host: _stun._udp.tech-ut16093cw
19/05/2017 15:40:10 (I) gajim.plugin_system.httpupload: bob@tech-ut16093cw can do http uploads via component upload.tech-ut16093cw
19/05/2017 15:40:10 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:40:12 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:40:12 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:40:12 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:40:16 (I) gajim.plugin_system.httpupload: Encryption is: False / OMEMO not found
19/05/2017 15:40:16 (I) gajim.plugin_system.httpupload: Detected MIME Type of file: image/png
19/05/2017 15:40:16 (I) gajim.plugin_system.httpupload: jid_to_servers of bob@tech-ut16093cw: upload.tech-ut16093cw ; connection: <nbxmpp.client_nb.NonBlockingClient object at 0x050707D0>
19/05/2017 15:40:16 (D) gajim.plugin_system.httpupload: sending httpupload slot request iq...
19/05/2017 15:40:16 (I) gajim.plugin_system.httpupload: Uploading file to 'http://172.16.13.159:5443/upload/a5becd84ae2e1abf27892bea8bd80fa8b6bf3269/yEAW2Ez7TmG1dCLPWkKmNXza7pZGCrJLcWetVKIQ/black_in_yellow.png'...
19/05/2017 15:40:16 (I) gajim.plugin_system.httpupload: Please download from 'http://172.16.13.159:5443/upload/a5becd84ae2e1abf27892bea8bd80fa8b6bf3269/yEAW2Ez7TmG1dCLPWkKmNXza7pZGCrJLcWetVKIQ/black_in_yellow.png' later...
19/05/2017 15:40:16 (D) gajim.plugin_system.httpupload: opening urllib2 upload request...
19/05/2017 15:40:16 (D) gajim.plugin_system.httpupload: upload progress: 100.00% (7627 of 7627 bytes)
19/05/2017 15:40:16 (D) gajim.plugin_system.httpupload: upload progress: 100.00% (7627 of 7627 bytes)
19/05/2017 15:40:37 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
19/05/2017 15:40:50 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:40:50 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:40:50 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:41:02 (I) gajim.plugin_system.httpupload: Encryption is: False / OMEMO not found
19/05/2017 15:41:02 (I) gajim.plugin_system.httpupload: Detected MIME Type of file: image/jpeg
19/05/2017 15:41:02 (I) gajim.plugin_system.httpupload: jid_to_servers of bob@tech-ut16093cw: upload.tech-ut16093cw ; connection: <nbxmpp.client_nb.NonBlockingClient object at 0x050707D0>
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: sending httpupload slot request iq...
19/05/2017 15:41:02 (I) gajim.plugin_system.httpupload: Uploading file to 'http://172.16.13.159:5443/upload/a5becd84ae2e1abf27892bea8bd80fa8b6bf3269/jqef91aObIl3vwDW2Q43Dap8Y2oVnyGx9ebnBhsa/calimero.jpg'...
19/05/2017 15:41:02 (I) gajim.plugin_system.httpupload: Please download from 'http://172.16.13.159:5443/upload/a5becd84ae2e1abf27892bea8bd80fa8b6bf3269/jqef91aObIl3vwDW2Q43Dap8Y2oVnyGx9ebnBhsa/calimero.jpg' later...
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: opening urllib2 upload request...
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 14.06% (8192 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 28.13% (16384 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 42.19% (24576 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 56.25% (32768 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 70.31% (40960 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 84.38% (49152 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 98.44% (57344 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 100.00% (58253 of 58253 bytes)
19/05/2017 15:41:02 (D) gajim.plugin_system.httpupload: upload progress: 100.00% (58253 of 58253 bytes)
19/05/2017 15:41:23 (E) gajim.plugin_system.httpupload: URLError
Traceback (most recent call last):
  File "C:\Users\fblanc\AppData\Roaming\Gajim\Plugins\httpupload\httpupload.py", line 494, in uploader
    transfer = urllib2.urlopen(request, timeout=30)
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
  File "C:\Python27\lib\urllib2.py", line 435, in open
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
  File "C:\Python27\lib\urllib2.py", line 473, in error
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
HTTPError: HTTP Error 503: Service Unavailable
Logger gajim.plugin_system.httpupload level set to 10
19/05/2017 15:43:57 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:43:57 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:44:05 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
19/05/2017 15:44:05 (I) gajim.plugin_system.httpupload: Account tech-ut16093cw: httpupload is_supported: True
```

**Comment by weiss** [comment] 2017-05-19 14:11
HTTPError: HTTP Error 503: Service Unavailable

There's no code in ejabberd that would return this error.  Maybe there's a (transparent) proxy in the middle; e.g., some piece of anti-virus software or whatever?

You could check whether you can reproduce it from a different system/client (e.g., with Conversations or Xabber on Android or with Monal on iOS).

**Comment by Immakittycat** [comment] 2017-05-22 08:03
I tried both Xabber and Monal but I can't manage to connect to the server using those apps, even though the phone was connected to the same local network.

**Comment by weiss** [comment] 2017-05-22 10:21
Debugging such networking issues remotely is a bit of a PITA ...

**Comment by Immakittycat** [comment] 2017-05-22 12:24
Yeah, I guess it is :/ .
Anyway, thanks for the help you provided. I'll pursue my efforts trying to make this work.
Hopefully I'll figured out what's blocking.

**Comment by anjasnewbie** [comment] 2017-05-23 03:16
I have this problem too, its 404 not found when trying to access https://domain.com:5444/upload
im using ejabberd 17.04

**Comment by anjasnewbie** [comment] 2017-05-23 03:39
here is last log 
`2017-05-23 03:36:31.449 [info] <0.518.0>@mod_http_upload:create_slot:585 Got HTTP upload slot for anjas@indonesia.umgroups.com/phone (file: ibu_kost.jpg)
2017-05-23 03:36:31.849 [info] <0.327.0>@ejabberd_listener:accept:311 (<0.842.0>) Accepted connection ::FFFF:120.188.33.199:30109 -> ::FFFF:103.215.72.80:5444
2017-05-23 03:36:31.849 [warning] <0.842.0>@ejabberd_config:prepare_opt_val:834 incorrect value '""' of option 'request_handlers', using '[]' as fallback
`

i got warning @ejabberd_config:prepare_opt_val:834 incorrect value '""' of option 'request_handlers', using '[]' as fallback

**Comment by anjasnewbie** [comment] 2017-05-23 03:39
my upload configuration 
`   port: 5444
   ip: "::"
   module: ejabberd_http
   request_handlers:
   "": mod_http_upload
   tls: true
   certfile: 'CERTFILE'`

**Comment by weiss** [comment] 2017-05-24 15:04
> Hopefully I'll figured out what's blocking.

Good luck!

I'll close this issue for the moment.  Feel free to add comments with additional info, especially if you suspect a `mod_http_upload` bug.

**Closed by weiss** 2017-05-24 15:04 UTC

**Comment by pvincent** [comment] 2017-06-23 07:07
I want to share my experience configuring the 'mod_http_upload' because it was painful according to me.
Finally I succeeded, bless this [stackoverflow](https://stackoverflow.com/questions/35578600/mod-http-upload-http-file-upload-xep-0363-using-ruby-on-rails) page.

Previously I turned the log level to 5 'debug' but did not help, no clue, it keeps failing silently.

> @mod_http_upload:create_slot:585 Got HTTP upload slot for pvincent@libre.re/7468694814666474808666 (file: logo.png)

may appear in the logfile, however there is no file created in the upload directory and nothing more.
I suspected file permission, CORs issues, the quota parameter missing, etc.... but it was related to http instead of https ! Please, for further investigation, would you mind log more relevant debug messages specially related to this http_upload module. It might help a lot.

**Comment by weiss** [comment] 2017-06-23 08:41
> would you mind log more relevant debug messages specially related to this http_upload module.

If the `put_url` doesn't point to a correctly configured listener, `mod_http_upload` won't see any HTTP(S) requests, so it's not trivial to produce helpful log output for this kind of configuration error.  For other cases, the module tries its best to log useful messages.

> Finally I succeeded, bless this [stackoverflow][1] page.

Is anything helpful mentioned there that's missing in [the official docs][2]?

[1]: https://stackoverflow.com/questions/35578600/mod-http-upload-http-file-upload-xep-0363-using-ruby-on-rails
[2]: https://docs.ejabberd.im/admin/configuration/#mod-http-upload

**Comment by pvincent** [comment] 2017-06-23 14:30
thank you for this quick reply weiss

According to me, it's a bit tricky due to :
- http/https leads to silent failure
- put_url => open a browser, it responds 'not found'
- is quota mandatory or optional ?
- a movim [issue](https://github.com/movim/movim/issues/341) : Access-Control pragma

meantime, I've decided to let NGINX as the main frontend (reverse proxy), thus SSL can't share the same certfile => ejabberd claims for a full pem certificate rather than a 'standard' nginx certificate.

I will try reproduce the same errors I did and investigate further...

**Comment by weiss** [comment] 2017-06-23 14:38
> I've decided to let NGINX as the main frontend (reverse proxy), thus I can't reuse the same certfile => ejabberd claims for a full pem certificate rather than a 'standard' nginx certificate.

According to the [Nginx docs][1], you should be able to use the PEM file for ejabberd in Nginx as well:

> If intermediate certificates should be specified in addition to a primary certificate, they should be specified in the same file in the following order: the primary certificate comes first, then the intermediate certificates. A secret key in the PEM format may be placed in the same file.

[1]: http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_certificate

**Comment by pvincent** [comment] 2017-06-23 14:42
ok, very helpful.
that may simplify my settings.
thx weiss

**Comment by pvincent** [comment] 2017-06-23 14:51
you are probably right Weiss.
I complained too quickly about the official docs.
my apologies.

**Comment by pvincent** [comment] 2017-06-26 20:04
ok I've investigated a bit further.
My mistake was related to virtual hosts (I've got 2)

`put_url: "https://bosh.@HOST@/upload"`
works

`put_url: "https://bosh.domain.tld@/upload"`
ejabberctl restart => failure

I guess the http upload module starts twice with the same put_url and crashed somehow
