### ISSUE TITLE
{'$gen_event',timeout}

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1543] opened 2017-02-14 18:38 UTC
> What version of ejabberd are you using?
17.01.109

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
src

> What did not work as expected? Are there error messages in the log? What
in live mode flooded with gen_server timeout.

18:25:43.086 [info] (<0.344.0>) Accepted connection 42.106.125.190:30468 -> 10.142.0.2:5222
(ejabberd@localhost)1> 18:26:13.086 [warning] got unexpected info: {'$gen_event',timeout}
18:26:13.086 [warning] got unexpected info: {'$gen_event',timeout}
18:26:13.086 [warning] got unexpected info: {'$gen_event',timeout}
18:26:13.086 [warning] got unexpected info: {'$gen_event',timeout}
18:26:13.086 [warning] got unexpected info: {'$gen_event',timeout}
18:26:13.086 [warning] got unexpected info: {'$gen_event',timeout}
18:26:13.086 [warning] got unexpected info: {'$gen_event',timeout}

**Comment by zinid** [comment] 2017-02-14 19:12
Duplicate of #1540

**Closed by zinid** 2017-02-14 19:12 UTC
