### ISSUE TITLE
Warnings: process_info got unexpected info 

### ISSUE THREAD

**Issue by licaon-kter** [processone/ejabberd#2521] opened 2018-07-09 20:53 UTC
> What version of ejabberd are you using?

18.06-head

> What operating system (version) are you using?

Raspbian-lastest

> How did you install ejabberd (source, package, distribution)?

head

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Warnings ( ejabberd_c2s:process_info:252 got unexpected info  ) in logs: https://gist.github.com/licaon-kter/d42f9c4c6cd553d18d4ae0387b0979fd

**Comment by zinid** [comment] 2019-06-14 13:19
This is quite reproducible using RTB for example. The problem somehow related to mod_stream_mgmt. I assign @weiss so far.

**Comment by zinid** [comment] 2019-06-25 11:40
The one with `resume` is fixed in 8b300d734b1d3ee2b2d739573dd081467485548c

**Comment by zinid** [comment] 2019-06-25 11:41
Another one is related to late arrival of the ack timer, I'll try to fix it myself because it's unrelated to mod_stream_mgmt.

**Comment by zinid** [comment] 2019-07-08 16:34
Fixed in 0545e0a797c32ce7292917bb1597a4332dacb3bf

**Closed by zinid** 2019-07-08 16:34 UTC
Labels: Kind:Bug
