### ISSUE TITLE
crash: no case clause matching fast_tls

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#1452] opened 2017-01-08 14:38 UTC
> What version of ejabberd are you using? How did you install ejabberd (source, package, distribution)?

ejabberd-16.12-windows-installer.exe

> What operating system (version) are you using?

Microsoft Windows 10 Pro x64 Version 1607 (Build 14393.576)

Connecting via SIPS (SIP over TLS) works fine.
Connecting an XMPP client via TLS (*not* start-tls) port 5223 fails. In the log the following lines appear:

> 2017-01-07 15:52:31.478 [error] <0.621.0> gen_fsm <0.621.0> in state wait_for_bind terminated with reason: no case clause matching fast_tls in ejabberd_socket:get_transport/1 line 229
> 2017-01-07 15:52:31.478 [error] <0.621.0> CRASH REPORT Process <0.621.0> with 0 neighbours exited with reason: no case clause matching fast_tls in ejabberd_socket:get_transport/1 line 229 in p1_fsm:terminate/8 line 760
> 2017-01-07 15:52:31.478 [error] <0.619.0> gen_fsm <0.619.0> in state wait_for_bind terminated with reason: no case clause matching fast_tls in ejabberd_socket:get_transport/1 line 229
> 2017-01-07 15:52:31.478 [error] <0.619.0> CRASH REPORT Process <0.619.0> with 0 neighbours exited with reason: no case clause matching fast_tls in ejabberd_socket:get_transport/1 line 229 in p1_fsm:terminate/8 line 760

Crash log is attached (personal information replaced by ***).

[crash_log.txt](https://github.com/processone/ejabberd/files/692160/crash_log.txt)

Same configuration with ejabberd 16.08 works fine.

OpenSSL 1.0.2j and 1.1.0c (each x86 and x64) is installed on the system.

**Comment by zinid** [comment] 2017-01-08 15:04
Duplicate of #1431

**Closed by zinid** 2017-01-08 15:04 UTC
