### ISSUE TITLE
Server error on fetching OMEMO encrypted message from MAM

### ISSUE THREAD

**Issue by anyuta1166** [processone/ejabberd#3719] opened 2021-11-29 20:04 UTC
## Environment

- ejabberd version: 20.07
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 11.1
- OS: Linux (Gentoo)
- Installed from: other

## Errors from error.log/crash.log

```
2021-11-29 21:57:39.131002+03:00 [error] <0.547.0>@gen_iq_handler:process_iq/4:116 Failed to process iq:
#iq{
 id = <<"Id2voOddRixv">>,type = set,lang = <<"en">>,
 from =
  #jid{
   user = <<"vamp">>,server = <<"vampik.ru">>,
   resource = <<"Conversations.c_9V">>,luser = <<"vamp">>,
   lserver = <<"vampik.ru">>,lresource = <<"Conversations.c_9V">>},
 to =
  #jid{
   user = <<"vamp">>,server = <<"vampik.ru">>,resource = <<>>,
   luser = <<"vamp">>,lserver = <<"vampik.ru">>,lresource = <<>>},
 sub_els =
  [#xmlel{
    name = <<"query">>,
    attrs =
     [{<<"xmlns">>,<<"urn:xmpp:mam:2">>},{<<"queryid">>,<<"g2b91vpj9p">>}],
    children =
     [#xmlel{
       name = <<"x">>,
       attrs = [{<<"xmlns">>,<<"jabber:x:data">>},{<<"type">>,<<"submit">>}],
       children =
        [#xmlel{
          name = <<"field">>,
          attrs = [{<<"var">>,<<"FORM_TYPE">>},{<<"type">>,<<"hidden">>}],
          children =
           [#xmlel{
             name = <<"value">>,attrs = [],
             children = [{xmlcdata,<<"urn:xmpp:mam:2">>}]}]},
         #xmlel{
          name = <<"field">>,
          attrs = [{<<"var">>,<<"with">>}],
          children =
           [#xmlel{
             name = <<"value">>,attrs = [],
             children = [{xmlcdata,<<"tvilla@messag.i.ng">>}]}]},
         #xmlel{
          name = <<"field">>,
          attrs = [{<<"var">>,<<"end">>}],
          children =
           [#xmlel{
             name = <<"value">>,attrs = [],
             children = [{xmlcdata,<<"2021-11-29T18:57:09.483Z">>}]}]}]},
      #xmlel{
       name = <<"set">>,
       attrs = [{<<"xmlns">>,<<"http://jabber.org/protocol/rsm">>}],
       children =
        [#xmlel{name = <<"before">>,attrs = [],children = []},
         #xmlel{
          name = <<"max">>,attrs = [],
          children = [{xmlcdata,<<"50">>}]}]}]}],
 meta = #{ip => {0,0,0,0,0,65535,24351,3553}}}
** exception error: no function clause matching
                  xml_compress:decode_attr(<<10,3,9,56,54,49,53,52,49,57,50,
                                             53,2,5,3,5,13,10,49,52,55,48,54,
                                             52,54,56,49,52,2,1,116,3,77,119,
                                             104,76,69,105,69,70,81,72,100,
                                             101,66,106,54,100,66,110,115,66,
                                             48,105,82,77,112,75,117,84,73,48,
                                             89,76,120,119,43,50,74,109,88,
                                             120,111,67,47,118,57,110,51,69,
                                             70,84,99,97,73,81,86,57,48,77,
                                             122,86,53,53,107,109,53,97,75,
                                             104,98,82,115,68,88,70,100,121,
                                             87,73,72,121,80,105,118,79,79,54,
                                             43,81,83,106,70,113,56,106,87,87,
                                             84,121,74,105,77,119,111,104,66,
                                             86,70,87,87,74,87,53,114,88,100,
                                             72,112,119,122,82,120,119,73,71,
                                             116,117,108,106,78,80,70,120,122,
                                             90,72,120,115,101,110,76,90,83,
                                             88,110,78,98,70,68,69,65,65,89,
                                             65,67,73,119,76,98,101,53,81,109,
                                             50,51,55,57,116,69,72,79,119,83,
                                             47,113,47,76,102,98,119,43,54,53,
                                             120,106,51,112,110,119,84,107,97,
                                             115,47,79,71,77,70,105,73,97,86,
                                             103,98,76,47,84,72,76,50,56,109,
                                             69,80,88,89,81,77,105,87,88,49,
                                             97,89,50,119,74,53,104,116,108,
                                             56,111,112,97,122,111,109,103,77,
                                             119,65,81,61,61,4,5,3,5,9,52,56,
                                             53,57,55,55,55,51,53,2,1,116,3,
                                             77,119,104,100,69,105,69,70,87,
                                             99,85,81,83,90,99,49,56,48,52,97,
                                             52,115,111,100,84,99,102,89,99,
                                             83,76,56,55,99,78,67,80,65,117,
                                             68,118,86,55,100,117,112,81,99,
                                             43,82,115,97,73,81,86,57,48,77,
                                             122,86,53,53,107,109,53,97,75,
                                             104,98,82,115,68,88,70,100,121,
                                             87,73,72,121,80,105,118,79,79,54,
                                             43,81,83,106,70,113,56,106,87,87,
                                             84,121,74,105,77,119,111,104,66,
                                             88,79,70,52,107,84,119,50,104,
                                             110,82,84,101,81,52,82,66,68,54,
                                             69,66,54,97,73,51,74,75,117,52,
                                             82,72,97,114,113,87,122,85,52,80,
                                             53,101,57,87,69,65,65,89,65,67,
                                             73,119,72,119,75,55,66,112,99,47,
                                             80,113,106,78,70,116,85,121,50,
                                             85,107,115,83,78,67,52,85,79,75,
                                             88,87,55,68,56,72,90,110,67,105,
                                             117,52,43,89,116,109,105,105,90,
                                             52,57,108,53,75,120,72,103,115,
                                             55,74,49,74,100,49,52,104,51,108,
                                             48,48,109,79,77,82,111,56,84,89,
                                             111,112,97,122,111,109,103,77,
                                             119,65,81,61,61,4,5,3,5,13,10,49,
                                             53,57,55,51,50,51,48,56,52,2,1,
                                             116,3,77,119,104,105,69,105,69,
                                             70,79,113,54,73,113,108,84,70,
                                             103,68,84,110,85,51,47,113,99,67,
                                             111,100,74,77,72,116,72,68,104,
                                             50,120,84,120,69,89,112,114,50,
                                             74,82,106,115,88,120,103,97,73,
                                             81,86,57,48,77,122,86,53,53,107,
                                             109,53,97,75,104,98,82,115,68,88,
                                             70,100,121,87,73,72,121,80,105,
                                             118,79,79,54,43,81,83,106,70,113,
                                             56,106,87,87,84,121,74,105,77,
                                             119,111,104,66,81,50,111,47,108,
                                             71,73,104,75,105,109,90,78,43,83,
                                             119,108,83,71,98,88,53,113,89,
                                             104,65,84,49,109,81,103,66,51,77,
                                             108,109,82,77,111,114,56,74,108,
                                             69,65,65,89,65,67,73,119,115,118,
                                             84,121,98,98,103,102,65,115,104,
                                             73,115,119,69,57,112,107,104,89,
                                             106,78,90,90,78,85,56,71,43,66,
                                             118,74,108,115,102,117,104,117,
                                             67,56,76,109,121,50,106,48,81,80,
                                             116,84,52,52,47,90,100,66,54,115,
                                             103,81,120,89,72,121,53,113,48,
                                             57,77,87,120,71,73,76,85,111,112,
                                             97,122,111,109,103,77,119,65,81,
                                             61,61,4,14,2,1,16,104,47,73,78,
                                             70,101,78,53,88,89,83,111,111,84,
                                             80,112,4,4,15,2,1,76,5,79,43,80,
                                             66,97,121,68,50,68,108,82,47,68,
                                             43,80,108,119,81,90,67,88,83,107,
                                             77,81,115,105,87,83,109,68,89,
                                             106,71,105,114,72,102,113,49,99,
                                             85,80,71,49,100,90,47,76,114,101,
                                             80,57,99,75,111,78,118,77,120,
                                             106,88,76,117,75,83,115,115,78,
                                             98,43,115,106,106,67,66,67,67,
                                             104,115,74,82,50,68,79,104,83,
                                             114,54,66,57,84,82,84,50,86,117,
                                             82,101,117,54,50,111,87,79,54,47,
                                             54,66,121,99,109,89,114,52,109,
                                             51,108,100,98,116,105,98,104,50,
                                             56,118,109,85,116,51,43,101,105,
                                             79,65,53,89,86,119,51,69,115,80,
                                             120,82,65,84,52,90,113,78,54,83,
                                             76,89,117,74,77,52,56,122,50,116,
                                             73,78,89,73,47,97,43,100,80,51,
                                             77,75,73,102,67,72,43,105,118,
                                             110,104,115,114,70,82,115,48,109,
                                             55,50,116,98,90,77,102,48,57,85,
                                             79,103,85,84,103,51,117,86,101,
                                             113,65,118,105,70,113,116,101,87,
                                             87,67,55,56,83,47,57,105,80,109,
                                             108,90,80,78,121,78,72,115,74,73,
                                             78,66,68,71,50,106,69,53,50,55,
                                             118,50,71,65,106,104,120,65,71,
                                             87,77,47,56,84,51,104,74,55,120,
                                             43,88,85,57,68,55,69,52,114,108,
                                             87,87,118,66,78,78,104,120,71,
                                             112,101,121,66,65,111,76,107,77,
                                             116,65,55,53,77,97,78,49,55,79,
                                             122,74,67,109,118,113,113,56,72,
                                             111,104,87,118,115,116,108,65,
                                             117,78,43,51,103,119,61,61,4,4,
                                             23,2,4,11,2,4,13,10,3,36,51,48,
                                             57,51,51,99,101,53,45,56,98,50,
                                             98,45,52,48,101,102,45,97,99,97,
                                             54,45,50,52,53,97,56,98,57,102,
                                             102,100,102,52,2,4,7,2,4,16,3,5,
                                             2,4,8,2,9,4,4>>) (src/xml_compress.erl, line 522)
   in function  xml_compress:prefix_map/3 (src/xml_compress.erl, line 536)
   in call from xml_compress:decode/4 (src/xml_compress.erl, line 573)
   in call from xml_compress:prefix_map/3 (src/xml_compress.erl, line 536)
   in call from xml_compress:decode/4 (src/xml_compress.erl, line 569)
   in call from xml_compress:prefix_map/3 (src/xml_compress.erl, line 536)
   in call from xml_compress:decode/4 (src/xml_compress.erl, line 637)
   in call from xml_compress:decode/3 (src/xml_compress.erl, line 483)
```

## Bug description

A user sent me an OMEMO encrypted message. I have message archiving enabled. Now when I try to open a chat with that user, the message history is not loaded at all and the error appears in the server log.

I had to manually delete the offending message from the "archive" table of the database, after that message history works again.

The message was sent by the Conversations client.

**Comment by licaon-kter** [comment] 2021-11-29 20:28
What was the message?

**Comment by anyuta1166** [comment] 2021-11-29 20:39
This is the message, taken from the SQL backup that I've made before manually deleting it:

[message.txt](https://github.com/processone/ejabberd/files/7620976/message.txt)

**Comment by badlop** [comment] 2021-11-30 12:57
Hi. I installed ejabberd from git, configured it to use mysql storage, enabled mod_mam, created two accounts and login to them with Conversations 2.10.1. Then configure Converstions to enable OMEMO always. I send a message from one account to the other, and it's stored in the archive mysql table.

Table exported:

```
INSERT INTO `archive` (`username`, `server_host`, `timestamp`, `peer`, `bare_peer`, `xml`, `txt`, `id`, `kind`, `nick`, `created_at`) 
VALUES
('admin',	'localhost',	1638276606438284,	'user2@localhost',	'user2@localhost',
 '<message ...<key rid=\'1082868347\'>MwohBW1ZMb...
  <payload>AO3hbQ==</payload></encrypted>...
  <body>I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo</body></message>',	'I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo',	9,	'chat',	'',	'2021-11-30 12:50:06'),...

```
That is very different to what you got:

```
INSERT INTO `archive` (`username`, `timestamp`, `peer`, `bare_peer`, `xml`, `txt`, `id`, `kind`, `nick`, `created_at`)
VALUES
('vamp', 1638195625919552, 'tvilla@messag.i.ng/Conversations.ay5p', 'tvilla@messag.i.ng',
 '$07a6d7d5-2bf7...
```

**Comment by anyuta1166** [comment] 2021-11-30 14:35
I've checked my server configuration and it seems that I have XML compression enabled. The documentation says that it is disabled by default.
```
  mod_mam:
    compress_xml: true
```
So it seems that I've encountered a bug in your custom XML (de)compression algorithm.

By the way, is it safe to disable this setting? My server is running for many years. I don't want to lose all the history.

**Comment by licaon-kter** [comment] 2021-11-30 15:24
Maybe this fixed it? https://github.com/processone/ejabberd/commit/de51ba331e3f02a734b607ad760f68e417b01568

@anyuta1166 Any chance to update your ejabberd? Or at least test?

**Comment by badlop** [comment] 2021-12-01 10:59
Aha, enabling compress_xml will produce table entries like that. As that didn't trigger a crash, I also reverted the fix that @licaon-kter mentioned, and tried to reproduce the problem. I can retrieve the MAM archive without crash.

Then I tried all this with ejabberd 21.01 (that's the oldest I can compile right now), and archiving with OMEMO + compressed xml works correctly: I can retrieve archive without crash.

Maybe it was fixed in some other commit? Or maybe it was a very specific content that triggered a bug in the compressor, that I cannot reproduce with simple text messages?

**Comment by anyuta1166** [comment] 2021-12-01 11:10
> Or maybe it was a very specific content that triggered a bug in the compressor

Looks like that. Actually I successfully received some OMEMO encrypted messages without a crash. But after that I received one more message and it caused the crash. SQL dump of that message is attached to one of my comments.

**Comment by badlop** [comment] 2021-12-01 11:56
Ok, I installed ejabberd git, configured as mentioned earlier, sent a pair of messages and inserted your SQL query (I modified sender and destination to match accounts in my server).

Then I login to the account, retrieve MAM archive and receive it, no crash in ejabberd log:

<details>

```xml
<message to='user2@localhost/tka1'
	from='user2@localhost'>
  <result id='1638195625919552'
	queryid='f27'
	xmlns='urn:xmpp:mam:2'>
    <forwarded xmlns='urn:xmpp:forward:0'>
      <message xml:lang='en'
	to='user2@localhost'
	from='admin@localhost/Conversations.ay5p'
	type='chat'
	id='07a6d7d5-2bf7-49ef-96a1-f5cff4df93d8'
	xmlns='jabber:client'>
        <archived by='user2@localhost'
	id='1638195625919552'
	xmlns='urn:xmpp:mam:tmp'/>
        <stanza-id by='user2@localhost'
	id='1638195625919552'
	xmlns='urn:xmpp:sid:0'/>
        <encrypted xmlns='eu.siacs.conversations.axolotl'>
          <header sid='861541925'>
            <key rid='485977735'>MwohBVqMJKf0nF8DDjac9nJbmaPKNGu30tMhqoHDVroRpfI0EAMYACIw6+oaW0NvGk76WkIkNgRQck7zQ4HlDyrwgXmNzALtvFyJ/DeGWy7TYiqRAx8oCZWkoQY0Mr9fQkI=</key>
            <key rid='1470646814'>MwohBa08VZd4iKW29khSykjLnBlHs35csx5tL/97JKW0iqUtEAIYASIwxO0SZmTxPfhEzxWTT9p5Xv3zjs890TQZLA5v/59nuYm1cVySf8SATt9566CNdmoOrLhV/FkMffI=</key>
            <key rid='1597323084'>MwohBdtuG5QBZLqtu+sWU5kuG8wV7iaiz0YkOouaVVMbNV1XEBQYACIwNxT7FCP+uYURgNtPhnHW0a9W0IjJx5G0rl7BSFgEEeVVnXKZyw81iBlRxfcauPzT8trmSTfQ0QI=</key>
            <iv>6/88mHIV0I7Nuk4w</iv>
          </header>
          <payload>evTC75GDB/7ACHT/9XO+pnE8RW2/R4uVlJfxIopwSTrgFrNPrUNHIkTHNd6IvoSvt/uHL4gK5t8x/eqALqEahJdoZKrrQHzU4nWdpxJ0A6F9kTI=</payload>
        </encrypted>
        <request xmlns='urn:xmpp:receipts'/>
        <markable xmlns='urn:xmpp:chat-markers:0'/>
        <origin-id id='07a6d7d5-2bf7-49ef-96a1-f5cff4df93d8'
	xmlns='urn:xmpp:sid:0'/>
        <store xmlns='urn:xmpp:hints'/>
        <encryption name='OMEMO'
	namespace='eu.siacs.conversations.axolotl'
	xmlns='urn:xmpp:eme:0'/>
        <body>I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo</body>
      </message>
      <delay from='localhost'
	stamp='2021-11-29T14:20:25.919552Z'
	xmlns='urn:xmpp:delay'/>
    </forwarded>
  </result>
</message>
```

</details>

**Comment by anyuta1166** [comment] 2021-12-01 18:18
> Ok, I installed ejabberd git, configured as mentioned earlier, sent a pair of messages and inserted your SQL query (I modified sender and destination to match accounts in my server).
> 
> Then I login to the account, retrieve MAM archive, no crash in ejabberd log, I receive the archive correctly:

I misidentified the message that caused the crash. I've double checked now and 
this is the message that causes a crash for me:

[test.sql.txt](https://github.com/processone/ejabberd/files/7636258/test.sql.txt)

**Comment by badlop** [comment] 2021-12-02 12:09
Ok, inserting that new SQL element, the crash is reproducible. As you mentioned, the compressed XML cannot be decoded, basically it has an unexpected content halfway in the string when attempting to decode an attribute: it expects 1:8, but has 10:8.

This feature was implemented in 0b31aa490ba19b85c164fcd463131979ff2ac1c7, and xml_compress.erl has no changes since 2019, so I guess you don't benefit of upgrading ejabberd.

It would be nice to know what original message triggered the bug. You know the contact and the date ('2021-11-29 08:49:16'), can you ask him what messages he sent? Trying to reproduce the problem...

**Comment by anyuta1166** [comment] 2021-12-02 14:02
> It would be nice to know what original message triggered the bug.

You mean message text? I've found it but I guess original message is useless because it was encrypted.

Original message (contact sent me a file):
```
aesgcm://jabber.vampik.ru:5443/upload/messag.i.ng/75a7d1ffed702a1b9b30fcf6781c92490b84623c/cB14ldIAaKYTAOl2HXdewngciSXOTwU24HkdqPbT/MJM85YsrQO-spiRai5_99A.jpg#48a80cc4a7a4019dd0f87e422965957d0a9ec20e4d0197e5247a7651a31be5425bc5d11326520e3a39f9fce1|0
```

**Comment by badlop** [comment] 2021-12-02 18:42
I'm unable to produce a problematic message. Tried sending a file using Conversations 2.10.1 with OMEMO encryption, MAM, SQL storage and compress_xml enabled... fetching MAM doesn't crash.

You could tell that contact to send you again that file, or any other, hoping to find a way to produce problematic messages to test the encoding code. Otherwise, I'm out of ideas.

**Closed** 2022-03-15 10:09 UTC
Labels: Note:Cannot reproduce
