### ISSUE TITLE
Message archive isn't sync between two nodes.

### ISSUE THREAD

**Issue by catap** [processone/ejabberd#4325] opened 2024-12-05 23:01 UTC
## Environment

- ejabberd version: 24.10
- Erlang version: `Erlang (SMP,ASYNC_THREADS) (BEAM) emulator version 14.2.5.3`
- OS: OpenBSD 7.6
- Installed from: distro package

## Configuration (only if needed):

```yaml
modules:
  ...
  mod_mam:
    assume_mam_usage: true
    default: always
  mod_offline:
    access_max_user_messages: max_user_offline_messages
...
```

## Errors from error.log/crash.log

No errors

## Bug description

I run small jabber with two nodes and use two different clients (Monal on phone, and Dino on laptop), and just discovered that some messages from a user from the same jabber server available only on Monal, and some on Dino.

`ejabberdctl mnesia_table_info archive_msg` has a bit different output on nodes, differences are:
mx1:
```
...
 {load_reason,{active_remote,'ejabberd@mx2.catap.net'}},
...
 {memory,6396293},
...
 {size,2408},
...
```
vs mx2:
```
...
 {load_reason,initial},
...
 {memory,6402889},
...
 {size,2419},
...
```
Interesting that restart of ejabberd on mx1 leads to sync it. And after restart both one-by-one the only differences is:
```
...
 {load_node,'ejabberd@mx1.catap.net'},
...
 {load_reason,{active_remote,'ejabberd@mx1.catap.net'}},
...
```
vs
```
...
 {load_node,'ejabberd@mx2.catap.net'},
...
 {load_reason,{active_remote,'ejabberd@mx2.catap.net'}},
...
```
everything else is the same.

**Comment by weiss** [comment] 2024-12-06 12:47
Using Mnesia for MAM storage is discouraged, see the warning in the [example config file][1] and in your [log file][2] during startup.  The warning only mentions the 2G limit, but the problem is more generally that Mnesia isn't designed for persistent storage of data: Think of it as Redis rather than SQL.  Using it to store non-trivial amounts of data can easily lead to issues, even more so with replication across nodes (even more so with replication across countries, as you mentioned in chat).

Therefore, if you need storage clustering, you'd have to look into the solutions available for the supported SQL backends.

I'll close this issue as there's nothing we could do about it (this isn't an actual ejabberd bug).  Sorry.

[1]: https://github.com/processone/ejabberd/blob/24.10/ejabberd.yml.example#L183-L186
[2]: https://github.com/processone/ejabberd/blob/24.10/src/mod_mam.erl#L123-L128

**Closed by weiss** 2024-12-06 12:47 UTC

**Comment by catap** [comment] 2024-12-06 13:20
Holger, thanks for your explanation.

I think that it should be made clear at least, because now it works out of the box, but after a while it is broken.

**Comment by weiss** [comment] 2024-12-06 13:30
Yes, a clear warning in the docs would probably be good.

Even better would be moving to SQLite and deprecating Mnesia altogether, at least in my book 😄

**Comment by mremond** [comment] 2024-12-09 08:28
Well, I think Mnesia has its use, but not for MAM.

**Comment by catap** [comment] 2024-12-09 15:07
@mremond, I think that the issue that it is using for MAM out of the box. Swithing to sqlite makes sense, indeed. But here the catch: debuging MAM isn't easy task, and cluster from two ejabberd works out of the box, but with default sqlite for MAM it will.. let say partial on each node.
