### ISSUE TITLE
failed to build with libressl

### ISSUE THREAD

**Issue by sss123next** [processone/ejabberd#2147] opened 2017-12-07 00:05 UTC
> What version of ejabberd are you using?

344a2611f2974f6ad0c1e5573f0470c416651b20

> What operating system (version) are you using?
Linux 4.9.x x86_64

> How did you install ejabberd (source, package, distribution)?
http://sss.chaoslab.ru/git/?p=sss_overlay.git;a=blob;f=net-im/ejabberd/ejabberd-scm.ebuild;h=2a7148c457501624691a9250ab4eab54406c5edc;hb=HEAD

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Output from installing net-im/ejabberd-scm:0::sss-repo to ::installed replacing scm:0::installed:

```
>>> Running ebuild phase killold as root:root...
>>> Starting builtin_killold
>>> Done builtin_killold
>>> Completed ebuild phase killold
>>> Running ebuild phases init saveenv as portage:portage...
>>> Starting builtin_init
>>> Done builtin_init
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases init saveenv
>>> Running ebuild phases loadenv setup saveenv as root:root...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting pkg_setup
>>> Done pkg_setup
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv setup saveenv
>>> Running ebuild phases loadenv unpack saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_unpack
 * git-r3: git protocol is completely unsecure and may render the ebuild
 * easily susceptible to MITM attacks (even if used only as fallback). Please
 * use https instead.
 * Fetching git://github.com/processone/ejabberd.git ...
 * [URI: git://github.com/processone/ejabberd.git]
git fetch git://github.com/processone/ejabberd.git +HEAD:refs/git-r3/HEAD
git symbolic-ref refs/git-r3/net-im/ejabberd/0/__main__ refs/git-r3/HEAD
 * Checking out git://github.com/processone/ejabberd.git to /var/tmp/paludis/net-im-ejabberd-scm/work/ejabberd-scm ...
git checkout --quiet refs/git-r3/HEAD
GIT update -->
   repository:               git://github.com/processone/ejabberd.git
   at the commit:            344a2611f2974f6ad0c1e5573f0470c416651b20
>>> Done src_unpack
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv unpack saveenv
>>> Running ebuild phases loadenv prepare saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_prepare
>>> Done src_prepare
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv prepare saveenv
>>> Running ebuild phases loadenv configure saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_configure
./configure --prefix=/usr --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 --docdir=/usr/share/doc/ejabberd-scm/html --libdir=/usr/lib64/erlang/lib/ --disable-tools --enable-odbc --enable-mysql --disable-pgsql --disable-pam --enable-zlib --disable-riak --disable-redis --enable-json --enable-iconv --disable-elixir --disable-debug --disable-latest-deps --enable-user=jabber --build=x86_64-pc-linux-gnu
configure: WARNING: unrecognized options: --enable-json
configure: loading site script /usr/share/config.site
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a sed that does not truncate output... /bin/sed
checking for x86_64-pc-linux-gnu-erl... no
checking for erl... /usr/bin/erl
checking for x86_64-pc-linux-gnu-erlc... no
checking for erlc... /usr/bin/erlc
checking for x86_64-pc-linux-gnu-epmd... no
checking for epmd... /usr/bin/epmd
checking for erl... /usr/bin/erl
checking for erlc... /usr/bin/erlc
checking Erlang/OTP version... ok
checking for Erlang/OTP root directory... /usr/lib64/erlang
checking for escript... /usr/lib64/erlang/bin/escript
checking for make... make
allow this system user to start ejabberd: jabber
checking whether Erlang is using deprecated types... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating vars.config
config.status: creating src/ejabberd.app.src
configure: WARNING: unrecognized options: --enable-json
==> rel (get-deps)
==> ejabberd-scm (get-deps)
Pulling lager from {git,"https://github.com/erlang-lager/lager",{tag,"3.4.2"}}
Cloning into 'lager'...
Pulling p1_utils from {git,"https://github.com/processone/p1_utils",
                           {tag,"1.0.10"}}
Cloning into 'p1_utils'...
Pulling cache_tab from {git,"https://github.com/processone/cache_tab",
                            {tag,"1.0.12"}}
Cloning into 'cache_tab'...
Pulling fast_tls from {git,"https://github.com/processone/fast_tls",
                           {tag,"1.0.17"}}
Cloning into 'fast_tls'...
Pulling stringprep from {git,"https://github.com/processone/stringprep",
                             {tag,"1.0.10"}}
Cloning into 'stringprep'...
Pulling fast_xml from {git,"https://github.com/processone/fast_xml","f22a56d"}
Cloning into 'fast_xml'...
Pulling xmpp from {git,"https://github.com/processone/xmpp","320e00a"}
Cloning into 'xmpp'...
Pulling fast_yaml from {git,"https://github.com/processone/fast_yaml",
                            {tag,"1.0.12"}}
Cloning into 'fast_yaml'...
Pulling jiffy from {git,"https://github.com/davisp/jiffy",{tag,"0.14.8"}}
Cloning into 'jiffy'...
Pulling p1_oauth2 from {git,"https://github.com/processone/p1_oauth2",
                            {tag,"0.6.2"}}
Cloning into 'p1_oauth2'...
Pulling luerl from {git,"https://github.com/rvirding/luerl",{tag,"v0.2"}}
Cloning into 'luerl'...
Pulling jose from {git,"git://github.com/potatosalad/erlang-jose.git",
                       {tag,"1.8.4"}}
Cloning into 'jose'...
Pulling fs from {git,"https://github.com/synrc/fs.git",{tag,"2.12.0"}}
Cloning into 'fs'...
Pulling p1_mysql from {git,"https://github.com/processone/p1_mysql",
                           {tag,"1.0.4"}}
Cloning into 'p1_mysql'...
Pulling ezlib from {git,"https://github.com/processone/ezlib",{tag,"1.0.3"}}
Cloning into 'ezlib'...
Pulling eimp from {git,"https://github.com/processone/eimp.git",{tag,"1.0.2"}}
Cloning into 'eimp'...
Pulling iconv from {git,"https://github.com/processone/iconv",{tag,"1.0.6"}}
Cloning into 'iconv'...
==> lager (get-deps)
Pulling goldrush from {git,"https://github.com/DeadZen/goldrush.git",
                           {tag,"0.1.9"}}
Cloning into 'goldrush'...
==> goldrush (get-deps)
==> p1_utils (get-deps)
==> cache_tab (get-deps)
==> fast_tls (get-deps)
==> stringprep (get-deps)
==> fast_xml (get-deps)
==> xmpp (get-deps)
==> fast_yaml (get-deps)
==> jiffy (get-deps)
WARN:  Missing plugins: [rebar3_hex]
==> p1_oauth2 (get-deps)
==> luerl (get-deps)
==> jose (get-deps)
Pulling base64url from {git,"git://github.com/dvv/base64url.git",
                            {branch,"master"}}
Cloning into 'base64url'...
==> base64url (get-deps)
WARN:  Missing plugins: [pc,rebar3_hex]
==> fs (get-deps)
==> p1_mysql (get-deps)
==> ezlib (get-deps)
==> eimp (get-deps)
==> iconv (get-deps)
>>> Done src_configure
>>> Starting builtin_saveenv
>>> Done builtin_saveenv
>>> Completed ebuild phases loadenv configure saveenv
>>> Running ebuild phases loadenv compile saveenv as portage:portage...
>>> Starting builtin_loadenv
>>> Done builtin_loadenv
>>> Starting src_compile
rm -rf deps/.got
rm -rf deps/.built
mkdir -p deps
/usr/lib64/erlang/bin/escript rebar get-deps && :> deps/.got
make -j16
==> goldrush (get-deps)
==> lager (get-deps)
==> p1_utils (get-deps)
==> cache_tab (get-deps)
==> fast_tls (get-deps)
==> stringprep (get-deps)
==> fast_xml (get-deps)
==> xmpp (get-deps)
==> fast_yaml (get-deps)
==> jiffy (get-deps)
WARN:  Missing plugins: [rebar3_hex]
==> p1_oauth2 (get-deps)
==> luerl (get-deps)
==> base64url (get-deps)
==> jose (get-deps)
WARN:  Missing plugins: [pc,rebar3_hex]
==> fs (get-deps)
==> p1_mysql (get-deps)
==> ezlib (get-deps)
==> eimp (get-deps)
==> iconv (get-deps)
==> rel (get-deps)
==> ejabberd-scm (get-deps)
/usr/lib64/erlang/bin/escript rebar compile && :> deps/.built
==> goldrush (compile)
Compiled src/glc_lib.erl
Compiled src/glc_ops.erl
Compiled src/glc_run.erl
Compiled src/gr_app.erl
Compiled src/gr_context.erl
Compiled src/glc.erl
Compiled src/gr_counter_sup.erl
Compiled src/glc_code.erl
Compiled src/gr_manager.erl
Compiled src/gr_manager_sup.erl
Compiled src/gr_param_sup.erl
Compiled src/gr_counter.erl
Compiled src/gr_sup.erl
Compiled src/gre.erl
Compiled src/gr_param.erl
==> lager (compile)
Compiled src/lager_util.erl
Compiled src/lager_transform.erl
Compiled src/lager_app.erl
Compiled src/lager.erl
Compiled src/lager_backend_throttle.erl
Compiled src/lager_config.erl
Compiled src/lager_common_test_backend.erl
Compiled src/lager_console_backend.erl
Compiled src/error_logger_lager_h.erl
Compiled src/lager_crash_log.erl
Compiled src/lager_default_formatter.erl
Compiled src/lager_handler_watcher.erl
Compiled src/lager_handler_watcher_sup.erl
Compiled src/lager_manager_killer.erl
Compiled src/lager_msg.erl
Compiled src/lager_file_backend.erl
Compiled src/lager_sup.erl
Compiled src/lager_format.erl
Compiled src/lager_stdlib.erl
Compiled src/lager_trunc_io.erl
==> p1_utils (compile)
Compiled src/p1_server.erl
Compiled src/p1_file_queue.erl
Compiled src/p1_fsm.erl
Compiled src/p1_nif_utils.erl
Compiled src/p1_http.erl
Compiled src/p1_queue.erl
Compiled src/p1_options.erl
Compiled src/p1_utils.erl
Compiled src/p1_time_compat.erl
Compiled src/p1_edoc_layout.erl
Compiled src/p1_utils_sup.erl
Compiled src/treap.erl
==> cache_tab (compile)
Compiled src/cache_tab_sup.erl
Compiled src/cache_tab_app.erl
Compiled src/ets_cache_options.erl
Compiled src/cache_tab.erl
/var/tmp/paludis/net-im-ejabberd-scm/work/ejabberd-scm/deps/cache_tab/src/ets_cache.erl:508: Warning: crypto:rand_uniform/2 is deprecated and will be removed in a future release; use rand:uniform/1
Compiled src/ets_cache.erl
Compiling c_src/ets_cache.c
==> fast_tls (compile)
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether make sets $(MAKE)... yes
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for ANSI C header files... (cached) yes
checking for erl... /usr/lib64/erlang/erts-9.1/bin/erl
checking for erlc... /usr/lib64/erlang/erts-9.1/bin/erlc
checking for SSL_free in -lssl... yes
checking for SHA1_Init in -lcrypto... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/err.h usability... yes
checking openssl/err.h presence... yes
checking for openssl/err.h... yes
checking openssl/sha.h usability... yes
checking openssl/sha.h presence... yes
checking for openssl/sha.h... yes
checking openssl/opensslv.h usability... yes
checking openssl/opensslv.h presence... yes
checking for openssl/opensslv.h... yes
configure: creating ./config.status
config.status: creating vars.config
Compiled src/fast_tls_app.erl
Compiled src/fast_tls_sup.erl
Compiled src/p1_sha.erl
Compiled src/fast_tls.erl
Compiling c_src/fast_tls.c
c_src/fast_tls.c:318:30: warning: incompatible pointer types passing 'void *(size_t, const char *, int)' (aka 'void *(unsigned long, const char *, int)') to parameter of type 'void *(*)(size_t)' (aka 'void *(*)(unsigned long)') [-Wincompatible-pointer-types]
    CRYPTO_set_mem_functions(our_alloc, our_realloc, our_free);
                             ^~~~~~~~~
/usr/include/openssl/crypto.h:412:38: note: passing argument to parameter 'm' here
int CRYPTO_set_mem_functions(void *(*m)(size_t), void *(*r)(void *, size_t), void (*f)(void *));
                                     ^
c_src/fast_tls.c:318:41: warning: incompatible pointer types passing 'void *(void *, size_t, const char *, int)' (aka 'void *(void *, unsigned long, const char *, int)') to parameter of type 'void *(*)(void *, size_t)' (aka 'void *(*)(void *, unsigned long)') [-Wincompatible-pointer-types]
    CRYPTO_set_mem_functions(our_alloc, our_realloc, our_free);
                                        ^~~~~~~~~~~
/usr/include/openssl/crypto.h:412:58: note: passing argument to parameter 'r' here
int CRYPTO_set_mem_functions(void *(*m)(size_t), void *(*r)(void *, size_t), void (*f)(void *));
                                                         ^
c_src/fast_tls.c:318:54: warning: incompatible pointer types passing 'void (void *, const char *, int)' to parameter of type 'void (*)(void *)' [-Wincompatible-pointer-types]
    CRYPTO_set_mem_functions(our_alloc, our_realloc, our_free);
                                                     ^~~~~~~~
/usr/include/openssl/crypto.h:412:85: note: passing argument to parameter 'f' here
int CRYPTO_set_mem_functions(void *(*m)(size_t), void *(*r)(void *, size_t), void (*f)(void *));
                                                                                    ^
c_src/fast_tls.c:351:5: warning: implicit declaration of function 'OPENSSL_cleanup' is invalid in C99 [-Wimplicit-function-declaration]
    OPENSSL_cleanup();
    ^
c_src/fast_tls.c:471:9: warning: implicit declaration of function 'DH_set0_pqg' is invalid in C99 [-Wimplicit-function-declaration]
        DH_set0_pqg(dh, dh_p, NULL, dh_g);
        ^
5 warnings generated.
Compiling c_src/hashmap.c
Compiling c_src/p1_sha.c
==> stringprep (compile)
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether make sets $(MAKE)... yes
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for ANSI C header files... (cached) yes
checking for erl... /usr/lib64/erlang/erts-9.1/bin/erl
checking for erlc... /usr/lib64/erlang/erts-9.1/bin/erlc
configure: creating ./config.status
config.status: creating vars.config
Compiled src/stringprep_sup.erl
Compiled src/stringprep.erl
Compiled src/stringprep_app.erl
Compiling c_src/stringprep.cpp
==> fast_xml (compile)
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether make sets $(MAKE)... yes
checking for an ANSI C-conforming const... yes
checking how to run the C preprocessor... cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for ANSI C header files... (cached) yes
checking for erl... /usr/lib64/erlang/erts-9.1/bin/erl
checking for erlc... /usr/lib64/erlang/erts-9.1/bin/erlc
checking expat.h usability... yes
checking expat.h presence... yes
checking for expat.h... yes
checking for library containing XML_ParserCreate... -lexpat
configure: creating ./config.status
config.status: creating vars.config
Compiled src/fxml_gen_pt.erl
Compiled src/fast_xml.erl
Compiled src/fxml_stream.erl
Compiled src/fxml_sup.erl
Compiled src/fxml.erl
Compiled src/fxmlrpc.erl
Compiled src/fxmlrpc_codec.erl
Compiled src/fxml_gen.erl
Compiling c_src/fxml.c
Compiling c_src/fxml_stream.c
==> xmpp (compile)
Compiled src/jid.erl
Compiled src/flex_offline.erl
Compiled src/mam_query.erl
Compiled src/muc_register.erl
Compiled src/muc_request.erl
Compiled src/p1_mucsub.erl
Compiled src/muc_roominfo.erl
Compiled src/pubsub_get_pending.erl
Compiled src/muc_roomconfig.erl
Compiled src/pubsub_meta_data.erl
Compiled src/pubsub_publish_options.erl
Compiled src/pubsub_subscribe_authorization.erl
Compiled src/rfc3921.erl
Compiled src/pubsub_subscribe_options.erl
Compiled src/rfc6121.erl
Compiled src/pubsub_node_config.erl
Compiled src/xdata_codec.erl
Compiled src/xep0004.erl
Compiled src/xep0012.erl
Compiled src/xep0013.erl
Compiled src/xep0022.erl
Compiled src/xep0023.erl
Compiled src/xep0016.erl
Compiled src/xep0033.erl
Compiled src/xep0039.erl
Compiled src/xep0030.erl
Compiled src/xep0048.erl
Compiled src/xep0049.erl
Compiled src/xep0050.erl
Compiled src/xep0045.erl
Compiled src/xep0055.erl
Compiled src/xep0059.erl
Compiled src/rfc6120.erl
Compiled src/xep0065.erl
Compiled src/xep0066.erl
Compiled src/xep0077.erl
Compiled src/xep0078.erl
Compiled src/xep0054.erl
Compiled src/xep0060.erl
Compiled src/xep0085.erl
Compiled src/xep0092.erl
Compiled src/xep0084.erl
Compiled src/xep0114.erl
Compiled src/xep0115.erl
Compiled src/xep0153.erl
Compiled src/xep0131.erl
Compiled src/xep0172.erl
Compiled src/xep0158.erl
Compiled src/xep0184.erl
Compiled src/xep0191.erl
Compiled src/xep0199.erl
Compiled src/xep0138.erl
Compiled src/xep0202.erl
Compiled src/xep0203.erl
Compiled src/xep0221.erl
Compiled src/xep0231.erl
Compiled src/xep0220.erl
Compiled src/xep0249.erl
Compiled src/xep0264.erl
Compiled src/xep0279.erl
Compiled src/xep0280.erl
Compiled src/xep0198.erl
Compiled src/xep0297.erl
Compiled src/xep0334.erl
Compiled src/xep0352.erl
Compiled src/xep0356.erl
Compiled src/xep0355.erl
Compiled src/xep0359.erl
Compiled src/xep0357.erl
Compiled src/xep0369.erl
Compiled src/xep0313.erl
Compiled src/xep0363.erl
Compiled src/xmpp_codec_external.erl
Compiled src/xmpp_tr.erl
Compiled src/xmpp_uri.erl
Compiled src/xmpp.erl
Compiled src/xmpp_util.erl
/var/tmp/paludis/net-im-ejabberd-scm/work/ejabberd-scm/deps/xmpp/xmpp_codec: function get_mod/2+2690:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_test_tail2,{f,871},[{x,5},0]}
  Error:       {no_bsm_context,{x,5}}:

Compiling /var/tmp/paludis/net-im-ejabberd-scm/work/ejabberd-scm/deps/xmpp/src/xmpp_codec.erl failed:
ERROR: compile failed while processing /var/tmp/paludis/net-im-ejabberd-scm/work/ejabberd-scm/deps/xmpp: rebar_abort
make: *** [Makefile:100: deps/.built] Error 1


```

**Comment by zinid** [comment] 2017-12-07 06:01
This is like 5th duplicate of #2032

**Closed by zinid** 2017-12-07 06:01 UTC

**Comment by zinid** [comment] 2017-12-07 06:02
http://lmgtfy.com/?q=ejabberd+Internal+consistency+check+failed+-+please+report+this+bug

**Comment by sss123next** [comment] 2017-12-07 08:23
you wrong, this is not my case.
i have erlang 20.0 and this problem.

**Comment by prefiks** [comment] 2017-12-07 09:12
Those fast_tls warnings are fixed by commit a2b2154d11280becbf3077e62f7b5621d52b54fd, but you still need to get a hold of fixed erlang version for issue #2032

**Comment by sss123next** [comment] 2017-12-07 09:23
ok, i can use --enable-latest-deps
now with --enable-latest-deps and erlang 20.0 i have this:

```
Compiled src/ejabberd_acme.erl
src/ejabberd_auth_riak.erl:109: unknown type specifier 'H'
src/ejabberd_auth_riak.erl:35: function export/1 undefined
Compiling src/ejabberd_auth_riak.erl failed:
ERROR: compile failed while processing /var/tmp/paludis/net-im-ejabberd-scm/work/ejabberd-scm: rebar_abort
```

should i creat separated ticket for this ?

**Comment by zinid** [comment] 2017-12-07 09:24
Disable riak, if you don't need it.

**Comment by zinid** [comment] 2017-12-07 09:26
> i have erlang 20.0 and this problem

You only thinks so

**Comment by sss123next** [comment] 2017-12-07 09:41
```
/configure --prefix=/usr --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 --docdir=/usr/share/doc/ejabberd-scm/html --libdir=/usr/lib64/erlang/lib/ --disable-tools --enable-odbc --enable-mysql --disable-pgsql --disable-pam --enable-zlib **--disable-riak** --disable-redis --enable-json --enable-iconv --disable-elixir --disable-debug --enable-latest-deps --enable-user=jabber --build=x86_64-pc-linux-gnu
.......
Compiled src/ejabberd_acme.erl
src/ejabberd_auth_riak.erl:109: unknown type specifier 'H'
src/ejabberd_auth_riak.erl:35: function export/1 undefined
Compiling src/ejabberd_auth_riak.erl failed:
ERROR: compile failed while processing /var/tmp/paludis/net-im-ejabberd-scm/work/ejabberd-scm: rebar_abort
make: *** [Makefile:100: deps/.built] Error 1

```

```
erl
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:6:6] [async-threads:10]

Eshell V9.0  (abort with ^G)
1> erlang:system_info(otp_release).
"20"


```

**Comment by prefiks** [comment] 2017-12-07 09:44
i am guessing you are using ejabberd_sql_pt.erl from old version, please try doing make clean and try again

**Comment by sss123next** [comment] 2017-12-07 09:46
it's fresh clone from git repo each time.
maybe repo got damaged somehow, i will try to reclone it ...

**Comment by prefiks** [comment] 2017-12-07 09:49
It may be also that it uses that file from system installed version of ejabberd? I did push commit d8ace67a50a2ee68c679dc6d1e33ed8818c5df66 which should make compiling sql_pt as early as possible.

**Comment by zinid** [comment] 2017-12-07 10:09
> src/ejabberd_auth_riak.erl:109: unknown type specifier 'H'
> src/ejabberd_auth_riak.erl:35: function export/1 undefined
> Compiling src/ejabberd_auth_riak.erl failed:

That's completely different problem.

**Comment by sss123next** [comment] 2017-12-07 10:53
so...
yes...
it was collision with installed version.
i have removed installed version and latest git commit compiled just fine.
