### ISSUE TITLE
[warning] got unexpected info: item, { user, server }

### ISSUE THREAD

**Issue by coolfeature** [processone/ejabberd#1651] opened 2017-04-04 05:11 UTC
> What version of ejabberd are you using?

ejabberd-17.03.beta

> What operating system (version) are you using?

linux

> How did you install ejabberd (source, package, distribution)?

rpm package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I am writing a custom module and I am seeing a warning like the one below for every user in the shared roster group:

[warning] <0.508.0>@ejabberd_c2s:process_info:247 got unexpected info: {item,{<<"someuser">>,<<"server.com">>,<<>>},both}

**Comment by cromain** [comment] 2017-04-04 09:12
you are routing this tuple {item,_,_} to user c2s process likely calling ejabberd_sm:route
but you do not register a corresponding c2s_handle_info hook handler.

**Comment by coolfeature** [comment] 2017-04-04 09:26
I am not using ejabberd_sm:route route explicitly. I only have one hook registered i.e. ejabberd_hooks:add(user_receive_packet, Host, ?MODULE, on_user_receive_packet, 50) and the mod is stateless. I am not using erlang message passing anywhere.

**Comment by motohastam** [comment] 2017-06-19 10:50
I too got this warning while adding a user to shared roster using API call, so the response of the API is also 400 Bad Request.

**Comment by badlop** [comment] 2017-06-19 17:16
The problem is easy to reproduce: create a group, add as member and existing account, set as displayed that same group, then login to that account. The routing of that Item tuple was introduced in https://github.com/processone/ejabberd/commit/b88fa6f6174a2472fb438a8717a69d8affb212b6 and benefited from some feature that nowadays ejabberd doesn't support.

**Comment by zinid** [comment] 2017-08-18 08:37
I close this one as a duplicate of #1846

**Closed by zinid** 2017-08-18 08:37 UTC
