### ISSUE TITLE
Recipe for target 'deps/.built' failed when building from source

### ISSUE THREAD

**Issue by saribe0** [processone/ejabberd#2049] opened 2017-10-12 15:10 UTC
> What version of ejabberd are you using?

17.09 from source

> What operating system (version) are you using?

Ubuntu 16.04.2

> How did you install ejabberd (source, package, distribution)?

Source downloaded about 10 minutes ago.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I installed all the library dependencies, downloaded the source (git clone from master) and ran `./autogen.sh` and `./configure` and then `.make`

While compiling, I received the following error:
![screen shot 2017-10-12 at 11 09 38 am](https://user-images.githubusercontent.com/6515393/31503526-e28e86be-af3d-11e7-9e50-24178b82f2d5.png)

I'm not sure if theres any other info I should upload with this (logs, etc) so just let me know if I'm missing something.

**Comment by zinid** [comment] 2017-10-12 15:13
Duplicate of #2032

**Closed by zinid** 2017-10-12 15:13 UTC
