### ISSUE TITLE
ejabberd error, SSL_CTX_new failed

### ISSUE THREAD

**Issue by gabrix73** [processone/ejabberd#2804] opened 2019-02-22 15:12 UTC
My ejabberd running on a Debian stable VPS complaints giving this error in logs:

> 2019-02-22 15:22:26.295 [error] <0.1228.0> CRASH REPORT Process <0.1228.0> with 0 neighbours exited with reason: no match of right hand value {error,<<"SSL_CTX_new failed">>} in ejabberd_socket:starttls/3 line 153 in p1_fsm:terminate/8 line 760
> 2019-02-22 15:22:26.295 [error] <0.865.0> Supervisor ejabberd_s2s_in_sup had child undefined started with {ejabberd_s2s_in,start_link,undefined} at <0.1228.0> exit with reason no match of right hand value {error,<<"SSL_CTX_new failed">>} in ejabberd_socket:starttls/3 line 153 in context child_terminated

And this happens when clients (or servers) tries to connect to any of the configured starttls ports (5222,5269) and tls port (5280) whit this error in log files:

> 2019-02-22 15:21:41.865 [info] <0.977.0>@ejabberd_listener:accept:333 (#Port<0.24493>) Accepted connection 1.2.3.4:64086 -> 172.31.1.100:5222
> 2019-02-22 15:21:42.003 [error] <0.1221.0> gen_fsm <0.1221.0> in state wait_for_feature_request terminated with reason: no match of right hand value {error,<<"SSL_CTX_new failed">>} in ejabberd_socket:starttls/3 line 153

I run ejabberd since two years now.
My servers always got A+ from IM Observatory for security and encryption.
Yet when I try to connect with gajim, the client tells me to be careful because I'm connecting using an unencrypted connection.
These are days that I try to understand what is happening but I do not come to the end.
This for c2s starttls required 5222 port:

```
listen: 
  - 
    port: 5222
    ip: "172.31.1.100"
    module: ejabberd_c2s
    transport: tcp
    certfile: "/etc/ejabberd/ejabberd.pem"
    dhfile: "/etc/ejabberd/dh4096.pem"
    ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:!CAMELLIA128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM"
    starttls: true
    starttls_required: true
    protocol_options:
      - "no_sslv2"
      - "no_sslv3"
      - "no_tlsv1"
      - "no_tlsv1.1"
      - "no_compression"
      - "cipher_server_preference"
    ciphers: 'TLS_CIPHERS'    
    tls: false
    tls_compression: false
    stream_management: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
    zlib: false
    resend_on_timeout: if_offline
```

This for s2s required_trusted 5269 port:

```
  - 
    port: 5269
    ip: "172.31.1.100"
    module: ejabberd_s2s_in
    transport: tcp
s2s_use_starttls: required_trusted
s2s_certfile: "/etc/ejabberd/ejabberd.pem"
s2s_dhfile: "/etc/ejabberd/dh4096.pem"
s2s_protocol_options:
  - "no_sslv2"
  - "no_sslv3"
  - "no_tlsv1"
  - "no_tlsv1.1"
  - "no_compression"
  - "cipher_server_preference"
s2s_ciphers: "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:!CAMELLIA128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM"   
s2s_tls_compression: false
s2s_access: s2s
```

and this for https 5280 port:

```
`    port: 5280
    ip: "172.31.1.100"
    module: ejabberd_http
    request_handlers:
      "/pub/archive": mod_http_fileserver
      "/api": mod_http_api
      "/bosh": mod_bosh
      "/ws": ejabberd_http_ws
    web_admin: true
    http_bind: true
    http_poll: true
    register: false
    captcha: false
    tls: true
    certfile: "/etc/ejabberd/ejabberd.pem"
```

This is just what I would like to get to, but do not consider it for the moment.
The strange thing is that ejabberd gives me error even using a default configuration like the one found in the directory /usr/share/doc/ejabberd/examples/" where the only variables edited by me is the variable (hosts) where there is my jabber.domain.name.
My CA is letsencrypt.
The hostname on ejabberd is regularly a type A record in the dns.
Ejabberd runs on debian stretch and is 16.09-4 version.
What else to add ...
Now I can not think of anything else, I hope I was clear enough to explain my problem.
Thanks for your attention and have a good day.

**Comment by licaon-kter** [comment] 2019-02-22 15:31
Could you take a look at the clean config template? https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example

You have a lot of things that are already default or plain duplicated (eg. you have `ciphers:` twice?)

**Comment by licaon-kter** [comment] 2019-02-22 15:37
/duplicate https://github.com/processone/ejabberd/issues/2102

**Comment by gabrix73** [comment] 2019-02-22 17:10
I have upgraded ejabberd to version 18.12.1-2~bpo9+1.
These the actual logs for connecting clients:

> 2019-02-22 18:01:49.640 [info] <0.1376.0>@ejabberd_listener:accept:238 (<0.1629.0>) Accepted connection 2.2.2.2:44924 -> 172.31.1.100:5222
> 2019-02-22 18:01:50.321 [warning] <0.1629.0>@ejabberd_c2s:process_terminated:285 (tls|<0.1629.0>) Failed to secure c2s connection: TLS failed: Failed to find a certificate matching the domain in SNI extension: error:1412E0E2:SSL routines:ssl_parse_clienthello_tlsext:clienthello tlsext

And that's what i have in configuration file:
> certfiles:
>    - "/etc/letsencrypt/live/jabber.tcpreset.net/fullchain.pem"
>    - "/etc/letsencrypt/live/jabber.tcpreset.net/privkey.pem"

I have changed permissions root:ejabberd for etc/letsencrypt/live/jabber.mydomain.name/ dir and for files *.pem inside it ans still no luck.

**Comment by gabrix73** [comment] 2019-02-22 17:36
I solved by grouping all the letsencrypt certificates (in this order: chain.pem, cert.pem, privkey.pem) into a single file owned by root and the ejabberd group in the ejabberd directory, the old way.
But I'm interested in the ACME talk and how I can automate it all.

**Comment by zinid** [comment] 2019-02-25 11:35
I think the issue is resolved, so I close it.
ACME is a different topic.

**Closed by zinid** 2019-02-25 11:35 UTC
