### ISSUE TITLE
crash on request_handlers /admin (v. 20.02)

### ISSUE THREAD

**Issue by Subnum12** [processone/ejabberd#3186] opened 2020-03-14 10:23 UTC
## Environment

- ejabberd version: 20.02
- C:\Program Files\ejabberd-20.02\bin
- OS: Windows Server 2016

## Log:
```[error] <0.580.0>@ejabberd_http:apply_custom_headers:860 CRASH REPORT Process <0.580.0> with 0 neighbours crashed with reason: bad argument in call to maps:from_list([html]) in ejabberd_http:apply_custom_headers/2 line 860
[error] <0.565.0>@ejabberd_http:apply_custom_headers:860 Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.580.0> exit with reason bad argument in call to maps:from_list([html]) in ejabberd_http:apply_custom_headers/2 line 860 in context child_terminated
[error] <0.581.0>@ejabberd_http:apply_custom_headers:860 CRASH REPORT Process <0.581.0> with 0 neighbours crashed with reason: bad argument in call to maps:from_list([html]) in ejabberd_http:apply_custom_headers/2 line 860
[error] <0.565.0>@ejabberd_http:apply_custom_headers:860 Supervisor ejabberd_http_sup had child undefined started with {ejabberd_http,start_link,undefined} at <0.581.0> exit with reason bad argument in call to maps:from_list([html]) in ejabberd_http:apply_custom_headers/2 line 860 in context child_terminated
```

## crash.log
```=CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.580.0>
    registered_name: []
    exception error: bad argument: [{maps,from_list,[[html]],[]},{ejabberd_http,apply_custom_headers,2,[{file,"src/ejabberd_http.erl"},{line,860}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,495}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,287}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,212}]},{ejabberd_http,init,3,[{file,"src/ejabberd_http.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.105.0>]
    message_queue_len: 0
    messages: []
    links: [<0.565.0>,#Port<0.35>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 4185
    stack_size: 27
    reductions: 13998
  neighbours:
=SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     {badarg,[{maps,from_list,[[html]],[]},{ejabberd_http,apply_custom_headers,2,[{file,"src/ejabberd_http.erl"},{line,860}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,495}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,287}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,212}]},{ejabberd_http,init,3,[{file,"src/ejabberd_http.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,<0.580.0>},{id,undefined},{mfargs,{ejabberd_http,start_link,undefined}},{restart_type,temporary},{shutdown,5000},{child_type,worker}]

=CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/3
    pid: <0.581.0>
    registered_name: []
    exception error: bad argument: [{maps,from_list,[[html]],[]},{ejabberd_http,apply_custom_headers,2,[{file,"src/ejabberd_http.erl"},{line,860}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,495}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,287}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,212}]},{ejabberd_http,init,3,[{file,"src/ejabberd_http.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
    ancestors: [ejabberd_http_sup,ejabberd_sup,<0.105.0>]
    message_queue_len: 0
    messages: []
    links: [<0.565.0>,#Port<0.36>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 6772
    stack_size: 27
    reductions: 11184
  neighbours:
=SUPERVISOR REPORT====
     Supervisor: {local,ejabberd_http_sup}
     Context:    child_terminated
     Reason:     {badarg,[{maps,from_list,[[html]],[]},{ejabberd_http,apply_custom_headers,2,[{file,"src/ejabberd_http.erl"},{line,860}]},{ejabberd_http,process_request,1,[{file,"src/ejabberd_http.erl"},{line,495}]},{ejabberd_http,process_header,2,[{file,"src/ejabberd_http.erl"},{line,287}]},{ejabberd_http,parse_headers,1,[{file,"src/ejabberd_http.erl"},{line,212}]},{ejabberd_http,init,3,[{file,"src/ejabberd_http.erl"},{line,142}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]}
     Offender:   [{pid,<0.581.0>},{id,undefined},{mfargs,{ejabberd_http,start_link,undefined}},{restart_type,temporary},{shutdown,5000},{child_type,worker}]
```
## Bug description

Error appears once http://localhost:5280/admin is being accessed 

same issue:
https://stackoverflow.com/q/60673359/10367395

**Comment by aiomaster** [comment] 2020-03-14 23:50
I can confirm that this problem is present in the current docker version ejabberd/ecs:20.02, also.
I want to add that I use a nginx to proxy requests for `xmpp.mydomain.foo` with this nginx setting `proxy_set_header Host mydomain.foo`  to get the admin interface working on `https://xmpp.mydomain.foo/admin` for the xmpp domain `mydomain.foo` since #2989.
But now it isn't working at all, cause of the error described above and I don't know if my proxy setup matters.

**Comment by badlop** [comment] 2020-03-16 11:11
>    exception error: bad argument: [{maps,from_list,[[html]],[]},{ejabberd_htt

Yes, that problem was introduced in ejabberd 20.02, and it's fixed in a recent git commit, specifically in 00abf5d. There isn't yet any release with the fix.

**Closed by badlop** 2020-03-16 11:11 UTC

**Comment by Neustradamus** [comment] 2020-04-07 17:49
It is possible to create a 20.03.1?
Linked to:
- https://github.com/processone/ejabberd/issues/3200
