### ISSUE TITLE
Private messaging for subscribers not working in case of persistent muc room

### ISSUE THREAD

**Issue by gsojitra** [processone/ejabberd#1495] opened 2017-01-27 11:21 UTC
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

Cent OS 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

For persistent rooms, once server is restarted subscribers of rooms are not allowed to send private message to room.
For temporary rooms, subscribers are allowed to send private messages.Behavior is not consistent between two types of room for subscribers of room.

Expected behavior is that subscribers should be allowed to send private messages then for persistent room ,it should be fixed.

Possible fix:

```
--- a/ejabberd-16.09/src/mod_muc_room.erl
+++ b/ejabberd-16.09/src/mod_muc_room.erl
@@ -4400,17 +4400,18 @@ set_opts([{Opt, Val} | Opts], StateData) ->
                StateData#state{config =
                                    (StateData#state.config)#config{allow_subscription = Val}};
            subscribers ->
-               Subscribers = lists:foldl(
-                               fun({JID, Nick, Nodes}, Acc) ->
+               {Subscribers, Nicks} = lists:foldl(
+                               fun({JID, Nick, Nodes}, {SubAcc, NickAcc}) ->
                                        BareJID = jid:remove_resource(JID),
-                                       ?DICT:store(
+                                       {?DICT:store(
                                           jid:tolower(BareJID),
                                           #subscriber{jid = BareJID,
                                                       nick = Nick,
                                                       nodes = Nodes},
-                                          Acc)
-                               end, ?DICT:new(), Val),
-               StateData#state{subscribers = Subscribers};
+                                          SubAcc),?DICT:store(Nick, [jid:tolower(BareJID)], NickAcc)}
+                               end, {?DICT:new(), ?DICT:new()}, Val),
+
+               StateData#state{subscribers = Subscribers, subscriber_nicks = Nicks};
            affiliations ->
                StateData#state{affiliations = (?DICT):from_list(Val)};
            subject -> StateData#state{subject = Val};
```

**Comment by badlop** [comment] 2017-01-30 18:42
> For persistent rooms, once server is restarted subscribers of rooms are not allowed to send private message to room.

I tried to reproduce that problem, but it worked correctly for me. I installed ejabberd 16.09, joined a room, made it persistent. Another user subscribed to it, and was able to send private messages to the existing participant. Then I restarted ejabberd, logged in both users, the first joined it. The second was still able to send private messages, like this, which are received by the destination user:
```
<message id='402:184585'
	type='chat'
	to='sala1@conference.localhost/userfirst'>
  <body>something1</body>
</message>
```

**Comment by gsojitra** [comment] 2017-01-31 13:33
I tried this scenario using below steps:

1. Create persistent room with user1.
2. Subscribe two user subsriber1 and subcriber2.
3. Now send private message from subscriber1 to subscriber2
```
<message id='402:184585'
	type='chat'
	to='sala1@conference.localhost/subscriber2'>
  <body>something1</body>
</message>
```
4. Subscriber2 will receive private message from subscriber2
5. Now restart ejabberd server
6. Directly try to send private message from subscriber1 to subscriber2.It will fail with error "recipient is not in the conference room"

Please try above steps and you will be able to reproduce it.

Problem is that while loading persistent room options from database(mnesia/sql) , subscriber_nicks dictionary is not assigned.Only subcribers dictionary is assigned.That is the reason we are getting this error.

**Comment by badlop** [comment] 2017-01-31 18:19
Right, with those detailed instructions the problem is reproducible, and your fix is perfect. Thanks! Patch committed.

**Closed by badlop** 2017-01-31 18:19 UTC
Labels: Component:Muc, Kind:Bug

**Comment by gsojitra** [comment] 2017-02-01 12:10
Thanks for your quick response.
