### ISSUE TITLE
[error] <0.171.0> External eimp process (pid=X) has terminated unexpectedly, restarting in a few seconds

### ISSUE THREAD

**Issue by zarere** [processone/ejabberd#2027] opened 2017-10-02 15:08 UTC
> What version of ejabberd are you using?

17.09-1

> What operating system (version) are you using?
armv6-raspberry pi

> How did you install ejabberd (source, package, distribution)?
package -arch linux

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
to work without any errors

**Comment by zinid** [comment] 2017-10-02 15:27
Duplicate of #2016

**Closed by zinid** 2017-10-02 15:27 UTC
