### ISSUE TITLE
@@INSTALLDIR@@ in systemd script

### ISSUE THREAD

**Issue by mbirth** [processone/ejabberd#2737] opened 2018-12-26 16:17 UTC
After installing from `ejabberd-18.12.1-linux-aarch64.run` (also happened with previous versions), the systemd script in `bin/ejabberd.service` contains the lines:

```
ExecStart=/bin/sh -c '/opt/ejabberd-18.12.1/bin/ejabberdctl start && @@INSTALLDIR@@/bin/ejabberdctl started'
ExecStop=/bin/sh -c '/opt/ejabberd-18.12.1/bin/ejabberdctl stop && @@INSTALLDIR@@/bin/ejabberdctl stopped'
```

It seems the placeholder `@@INSTALLDIR@@` is only replaced once per line.

**Comment by badlop** [comment] 2018-12-27 14:44
For reference, _ejabberd-18.12.1-linux-x64.run_ works correctly, I see _bin/ejabberd.service_ has:
```
ExecStart=/bin/sh -c '/home/badlop/ejabberd-18.12.1/bin/ejabberdctl start && /home/badlop/ejabberd-18.12.1/bin/ejabberdctl started'
ExecStop=/bin/sh -c '/home/badlop/ejabberd-18.12.1/bin/ejabberdctl stop && /home/badlop/ejabberd-18.12.1/bin/ejabberdctl stopped'
```

**Comment by cromain** [comment] 2018-12-31 09:34
odd, @mbirth what system are you using ?

**Comment by cromain** [comment] 2018-12-31 09:36
BTW, bitrock does the substitution at install time, i don't think it uses system tools like sed... it's surprising to see different behaviours.

**Comment by mbirth** [comment] 2018-12-31 09:57
@cromain It's Ubuntu 18.10 arm64 on a Raspberry Pi 3B+.

**Comment by cromain** [comment] 2018-12-31 12:58
ah ok, so it's not bitrock installer but out own self-extractable code.
I know what the problem is and just pushed fix on packaging system.

**Closed by cromain** 2018-12-31 12:58 UTC
Labels: Component:Installers
