### ISSUE TITLE
Ejabberd doesn't respond to connections for all versions after 16.3.0

### ISSUE THREAD

**Issue by johnhamelink** [processone/ejabberd#1213] opened 2016-07-25 16:23 UTC
Hi there,

I spoke to @mremond about this issue a few days ago on #ejabberd in the Elixir Slack team. At that point, all I knew was that connections to the Ejabberd instance were failing, but the server was only producing the following output:

```
18:05:19.344 [info] (#Port<0.9052>) Accepted connection 10.0.2.55:58069 -> 10.0.1.224:5222
18:05:31.910 [info] (#Port<0.9059>) Accepted connection 10.0.2.55:58072 -> 10.0.1.224:5222
18:07:42.530 [info] (#Port<0.9114>) Accepted connection 10.0.1.220:8378 -> 10.0.1.224:5280
18:07:42.530 [info] started: {gen_tcp,#Port<0.9114>}
18:07:42.552 [info] (#Port<0.9115>) Accepted connection 10.0.2.55:64676 -> 10.0.1.224:5280
18:07:42.552 [info] started: {gen_tcp,#Port<0.9115>}
18:12:32.451 [info] [APNS] #PID<0.2024.0> successfully opened connection to feedback service
18:12:32.453 [info] [APNS] #PID<0.2024.0> closed feedback connection, reconnecting in 1200s
18:12:32.466 [info] [APNS] #PID<0.2016.0> successfully opened connection to feedback service
18:12:32.468 [info] [APNS] #PID<0.2016.0> closed feedback connection, reconnecting in 1200s
18:12:42.533 [info] (#Port<0.9243>) Accepted connection 10.0.1.220:8462 -> 10.0.1.224:5280
18:12:42.533 [info] started: {gen_tcp,#Port<0.9243>}
18:12:42.555 [info] (#Port<0.9244>) Accepted connection 10.0.2.55:64768 -> 10.0.1.224:5280
18:12:42.556 [info] started: {gen_tcp,#Port<0.9244>}
```

Now I've found that reverting to 16.3.0 solves the problem, and that I must've introduced this specific bug as part of an upgrade.

> What version of ejabberd are you using?
> Any version after 16.3.0
> 
> What operating system (version) are you using?
> Ubuntu on AWS
> 
> How did you install ejabberd (source, package, distribution)?
> Using the hex.pm package to add ejabberd as an application dependency to my project.
> 
> What did not work as expected? Are there error messages in the log? What was the unexpected behavior? What was the expected result?

```
$ ncat 127.0.0.1 5222
<?xml version="1.0"?>
<stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="localhost" xml:lang="en" xmlns:xml="http://www.w3.org/XML/1998/namespace">
```

Running that should result in an XML response. Instead it results in Connection Failed (Broken Pipe). Reverting to versions prior to 16.3.0 resolves the problem and the server responds as expected.

**Comment by mremond** [comment] 2016-07-25 16:43
I cannot reproduce the issue (at least on OSX).

I created an app with ejabberd 16.6 as dependency, from scratch, exactly as described here:
https://docs.ejabberd.im/developer/elixir/#embedding-ejabberd-in-an-elixir-application

I started ejabberd with downloaded config file (exactly as described in doc).

Then, I can netcat and receive content properly:

```
$ netcat 127.0.0.1 5222
<?xml version="1.0"?>
<stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="localhost" xml:lang="en" xmlns:xml="http://www.w3.org/XML/1998/namespace">

<?xml version='1.0'?><stream:stream xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' id='11679023174952697425' from='localhost' version='1.0' xml:lang='en'><stream:features><c xmlns='http://jabber.org/protocol/caps' hash='sha-1' node='http://www.process-one.net/en/ejabberd/' ver='AnudLoQ6YzangFOMngKxYf3sht0='/><register xmlns='http://jabber.org/features/iq-register'/><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>DIGEST-MD5</mechanism><mechanism>X-OAUTH2</mechanism><mechanism>SCRAM-SHA-1</mechanism></mechanisms></stream:features></stream:stream>
```

(extra line break added to separate content received from server).

**Comment by johnhamelink** [comment] 2016-07-25 18:23
@mremond Can I share my source code with you?

**Comment by mremond** [comment] 2016-07-26 07:26
I think the best approach to troubleshot is:

1. To disable all your modules and enable then one by one until you find the one causing issue.
2. Add debug printout to that module to see how it could interact in a bad way with the rest of ejabberd.

**Comment by meteorzxt** [comment] 2016-07-29 23:50
I think I have met the same bug as yours twice after I upgrade ejabberd to 16.06. But I haven't got any info owing to the production environment. I haven't the time to debug it, just restart ejabberd to recover it for users.

**Comment by cromain** [comment] 2017-07-31 14:40
closing this thread as we can not reproduce.

**Closed by cromain** 2017-07-31 14:40 UTC
Labels: Component:Elixir, Note:Cannot reproduce, Note:Needs more info
