### ISSUE TITLE
Add support for urn:xmpp:mam:2

### ISSUE THREAD

**Issue by marcphilipp** [processone/ejabberd#1762] opened 2017-06-06 13:15 UTC
> What version of ejabberd are you using?

16.09

> What operating system (version) are you using?

CentOS Linux release 7.2.1511

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

XEP-0313 (MAM) was updated earlier this year and, among other additions, uses a new namespace (urn:xmpp:mam:2). Several client libraries (e.g. Strophe.JS) already support it.

Are there any plans for ejabberd to add support for the latest version of the XEP?

**Comment by weiss** [comment] 2017-06-12 14:48
Yes, I have such plans :-)

**Comment by marcphilipp** [comment] 2017-06-12 14:59
Glad to hear that! 😁 

Will it make it into the next release? 😇

**Comment by weiss** [comment] 2017-06-12 15:07
> Will it make it into the next release?

I just work on these things in my spare time, so I don't give any timeframes.  So, unless others want to implement this, the answer is "no idea".

**Comment by marcphilipp** [comment] 2017-06-12 15:46
Fair enough. 🙂

**Comment by omichelsen** [comment] 2017-07-21 17:51
I did some digging, and it seems the `urn:xmpp:mam:0` namespace was introduced in XEP-0313 [version 0.3](https://xmpp.org/extensions/attic/xep-0313-0.3.html). It got bumped to `:1` in [version 0.4.1](https://xmpp.org/extensions/attic/xep-0313-0.4.1.html) and finally to `:2` in [version 0.6](https://xmpp.org/extensions/attic/xep-0313-0.6.html).

I don't see anything major/breaking in the [revision history](https://xmpp.org/extensions/xep-0313.html#appendix-revs) between these versions. Would it be a big issue to simply update the namespace?

We are using Strophe with a plugin setting the latest namespace. ejabberd denies this because of version mismatch, but if we manually "downgrade" the namespace in our plugin, everything works fine. It might not be an exhaustive test, but it leads me to believe that there are no breaking issues in upgrading the namespace version?

**Comment by weiss** [comment] 2017-07-21 17:57
By announcing `:2` support the server guarantees that all live messages are tagged with a stanza ID.  So we can't just bump the namespace, no.  We need to fix #1344, first.

**Comment by zinid** [comment] 2017-07-21 18:17
For the record, for those awaiting, initial PR: #1881

**Comment by zinid** [comment] 2017-12-30 07:31
The issue is actually resolved a few months ago, I close it.

**Closed by zinid** 2017-12-30 07:31 UTC
Labels: Component:MAM, Kind:Enhancement

**Comment by jovanpreet** [comment] 2018-04-11 10:41
In which version it gets fixed??

**Comment by weiss** [comment] 2018-04-11 10:44
> In which version it gets fixed??

`urn:xmpp:mam:2` is supported since ejabberd 17.11.

**Comment by jovanpreet** [comment] 2018-04-11 10:50
Thanks
