### ISSUE TITLE
19.08 Web admin config issues: Host not served

### ISSUE THREAD

**Issue by Emilio-Gonzalez** [processone/ejabberd#3033] opened 2019-09-24 16:03 UTC
## Environment

- ejabberd version: 19.08
- OS: Linux (CentOS)
- Installed from: official rpm

## Bug description

Same configuration as in 19.05 (it works ok in this version) but now I can´t access Web Admin in 19.08.
It says **Host not served**

Any new config is needed?
As default config It doesn't work neither.

**Comment by zinid** [comment] 2019-09-24 16:08
Duplicate of #2989

**Closed by zinid** 2019-09-24 16:08 UTC
Labels: Kind:Bug
