### ISSUE TITLE
www Documentation messed up

### ISSUE THREAD

**Issue by wwags** [processone/ejabberd#1645] opened 2017-03-28 11:23 UTC
Large parts of descriptive text in the documentation https://docs.ejabberd.im are somehow identified as code and formatted accordingly, i.e. monospaced font, black background, attempted syntax highlighting.

This is extremly hard to read.

**Comment by cromain** [comment] 2017-03-30 14:28
thanks reporting this. examples on https://docs.ejabberd.im/admin/configuration/

**Comment by f055** [comment] 2017-03-30 14:53
This should be fixed now and updated online, but if you spot this issue again anywhere, please let me know with link to the specific section.

**Comment by wwags** [comment] 2017-03-30 18:55
Hi Marek,


looks a lot better now. Thanks. There are still some paragraphs remaining, though.

It’s in mod_pubsub and in mod_shared_roster_ldap

Some are indeed hard to identify. 

Ticket’s already closed, that’s why mail.


Best,

Andreas

**Comment by badlop** [comment] 2017-03-30 19:10
Ah, right, three paragraphs in
https://docs.ejabberd.im/admin/configuration/#mod-pubsub
And apparently other three in:
https://docs.ejabberd.im/admin/configuration/#mod-shared-roster-ldap

**Comment by wwags** [comment] 2017-03-30 19:13
what’s it caused by? (out of curiousity...)

**Comment by f055** [comment] 2017-03-31 10:56
I pushed more updates online. The paragraphs in code should be fixed.

@wwags the cause of the issue is somewhat Markdown. Our docs source is mostly written in MD, and its syntax is delicate in terms of new lines and indentation. This particular issue was caused by indentation in the source that looked good when reading the source (ie. paragraph after paragraph was indented to align vertically), but resulted in paragraphs to be incorrectly treated as code, as they were unnecessarily indented.

**Closed** 2017-04-06 08:57 UTC
Labels: Kind:Documentation
