### ISSUE TITLE
No systemd service file in 22.05 rpm package

### ISSUE THREAD

**Issue by nerijus** [processone/ejabberd#3816] opened 2022-05-17 14:43 UTC
ejabberd-21.07-0.x86_64.rpm has systemd service file `/opt/ejabberd-21.07/bin/ejabberd.service`, but ejabberd-22.05-1.x86_64.rpm no longer has it. I see it was changed in https://github.com/processone/ejabberd/pull/3781 and apparently systemd service file is generated by `ejabberd-2x.xx-1-linux-x64.run` file. It would  be nice to have it back in rpm package as well.

**Comment by weiss** [comment] 2022-05-18 08:01
The idea was to have the RPM package install the service unit in the proper location.  Seems it's missing from the package indeed, I'll look into it.

**Comment by weiss** [comment] 2022-05-18 08:32
You could test this updated package if you like:

https://ejabberd.messaging.one/download/package/ejabberd-22.05-2.x86_64.rpm

You'd enable and start the systemd service like this:

```
sudo systemctl --now enable ejabberd
```

**Comment by jeroenhabets** [comment] 2022-05-22 09:32
P.S. I just installed ejabberd_22.05-2_amd64.deb and also noticed the ejabberd.service was gone. (I created it manually using the template).

**Comment by weiss** [comment] 2022-05-22 15:31
> I just installed ejabberd_22.05-2_amd64.deb and also noticed the ejabberd.service was gone.

That would be another, unrelated bug.  I wouldn't have expected that, as I tested several installations of the DEB package.  Would've expected the systemd service to be auto-started on installation.

I'll see whether I can reproduce the problem, but won't be able to test things before Wednesday.

**Comment by jeroenhabets** [comment] 2022-05-22 16:14
@weiss perhaps because I had manually created a softlink in /etc/systemd/system (systemd.service -> /opt/ejabberd-21.12/bin/systemd.service). I do not want to cause you to waste your time trying to reproduce it.

**Comment by weiss** [comment] 2022-05-25 11:33
Ah, yes, I guess you just need to remove that softlink, then.

To double-check, I've installed [ejabberd_22.05-2_amd64.deb][1] on a fresh Debian system and ended up with a `/lib/systemd/system/ejabberd.service` unit.  `systemctl status ejabberd` is happy.

I'll close this issue, please open a new one if you still run into problems.

[1]: https://github.com/processone/ejabberd/releases/download/22.05/ejabberd_22.05-2_amd64.deb

**Closed by weiss** 2022-05-25 11:33 UTC
Labels: Packaging:RPM, Download:GitHub Releases
