### ISSUE TITLE
ejabberd http-bind repeating rid error

### ISSUE THREAD

**Issue by vijayaa** [processone/ejabberd#1593] opened 2017-03-06 05:40 UTC
> What version of ejabberd are you using?
ejabberd 17.01

> What operating system (version) are you using?
centos 7.0.1406

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
We have a system setup where we use Stophe to connect to ejabberd over
BOSH running through HA-Proxy. When our clients are idle, they seem to
be hitting the timeout (@ 1.1 * 60 seconds), which aborts the
outstanding long-poll. The library then appears to make the next
long-poll using the same rid. ejabberd shows repeating RID and returns error.

> was the unexpected behavior? What was the expected result?

**Comment by zinid** [comment] 2017-03-06 05:42
Please don't create duplicated issues.
I close this one as it's a duplicate of #1576

**Closed by zinid** 2017-03-06 05:42 UTC
