### ISSUE TITLE
Ejabberd and flash: serving crossdomain.xml

### ISSUE THREAD

**Issue by bp91** [processone/ejabberd#2519] opened 2018-07-09 16:00 UTC
> What version of ejabberd are you using?

18.04

> What operating system (version) are you using?

Centos 7

> How did you install ejabberd (source, package, distribution)?

rpm

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Hi guys, I would like to serve the **crossdomain.xml** file in order to allow flash connection to ejabberd.
I did this:
I've created the **crossdomain.xml** into **/opt/ejabberd/conf/**:

```
<?xml version="1.0"?>
<!DOCTYPE cross-domain-policy SYSTEM "http://www.macromedia.com/xml/dtds/cross-domain-policy.dtd">
<cross-domain-policy>
        <site-control permitted-cross-domain-policies="all"/>
        <allow-access-from domain="*" to-ports="5222,5223,7070,7443" secure="true"/>
</cross-domain-policy>
```
The I've added into the ejabberd.yml file:

```
listen:
  -
    port: 5222
    ip: "::"
    module: ejabberd_c2s
    request_handlers:
      "/pub/archive": mod_http_fileserver
    starttls: true
    max_stanza_size: 65536
    shaper: c2s_shaper
    access: c2s
-
    port: 5280
    ip: "::"
    module: ejabberd_http
    request_handlers:
      "/websocket": ejabberd_http_ws
      "/api": mod_http_api
      "/oauth": ejabberd_oauth
      "/http-bind": mod_bosh
      "/pub/archive": mod_http_fileserver
    web_admin: false
    http_bind: true
    captcha: false
...
modules:
 ...
  mod_http_fileserver:
    docroot: "/opt/ejabberd/conf"
    accesslog: "/opt/ejabberd-18.04/logs/access.log"
    content_types:
      ".xml": "text/x-cross-domain-policy"
```
But It seems not working. Any idea? Thanks for the support

**Comment by zinid** [comment] 2018-07-13 10:34
I don't think putting that file on ejabberd will help, because flash doesn't use standard XML: it inserts nulls (0x0) between stanzas so this will be no valid XML. At least that's how it behaved years ago, maybe the situation has been changed.

**Comment by zinid** [comment] 2018-07-14 05:35
I close the issue as this is not a bug.

**Closed by zinid** 2018-07-14 05:35 UTC
