### ISSUE TITLE
Error installing with RPM

### ISSUE THREAD

**Issue by btv** [processone/ejabberd#634] opened 2015-07-02 22:02 UTC
I've got a Centos6.6 machine, and when I try to install the RPM I get this error:

```
rpm -Uvh ejabberd-15.06-0.x86_64.rpm 
Preparing...                ########################################### [100%]
   1:ejabberd               ########################################### [100%]
error: unpacking of archive failed on file /opt/ejabberd-15.06/lib/kernel: cpio: rename failed - Is a directory
```

I'm happy to help test to get this resolved. Thank you for making pre-built RPM's to BTW.

**Comment by cromain** [comment] 2015-07-03 07:06
I can not reproduce this, testing on Centos7.
in our installer, kernel is a symlink to kernel-3.2. maybe your filesystem prevent use of symlink ?

**Comment by SJReese** [comment] 2015-07-20 13:49
Greetings:

I am seeing the same issue with a fresh install of CentOS 6. If kernel should be a symlink to kernel-3.2, then I think that the issue is that a directory named kernel already exists in the /opt/ejabberd-15.06/lib folder and that is preventing the symlink from being created. Here's what the /opt/ejabberd-15.06/lib folder looks like after the install fails:

sreese@im01:/opt$ ll /opt/ejabberd-15.06/lib/
total 40
drwxr-xr-x.  6 root root 4096 Jul 20 09:32 asn1-3.0.4
drwxr-xr-x.  3 root root 4096 Jul 20 09:32 cean-2.1
drwxr-xr-x.  3 root root 4096 Jul 20 09:32 compiler-5.0.4
drwxr-xr-x.  4 root root 4096 Jul 20 09:32 crypto-3.5
drwxr-xr-x.  6 root root 4096 Jul 20 09:32 ejabberd-15.06
drwxr-xr-x.  3 root root 4096 Jul 20 09:32 erts-6.4
drwxr-xr-x. 11 root root 4096 Jul 20 09:32 hipe-3.11.3
drwxr-xr-x.  7 root root 4096 Jul 20 09:32 inets-5.10.6
drwxr-xr-x.  2 root root 4096 Jul 20 09:32 kernel
lrwxrwxrwx.  1 root root   10 Jul 20 09:32 kernel;55acf866 -> kernel-3.2
drwxr-xr-x.  2 root root 4096 Jul 20 09:32 stdlib

cpio is creating the symlink with a temporary name and then trying to rename it to kernel, which fails because there is already a directory named kernel.

**Comment by mremond** [comment] 2015-07-20 14:10
Thanks for the report. Any idea why a library kernel would already existing in that directory ? Is that a reinstall ?

**Comment by SJReese** [comment] 2015-07-20 14:20
It's a completely fresh install on a newly installed and patched CentOS 6 install. If I remove the /opt/ejabberd-15.06 and /opt/bitrock folders after the failed install, it does the same thing, so the rpm is creating the /opt/ejabberd-15.06/lib/kernel folder somewhere in the process prior to trying to create the symlink from kernel-3.2 to kernel.

I looked to see if the spec file that the rpm was created from was available for download, but I didn't find it anywhere. I am getting ready to crack open the rpm file and look at the installation script so I might be able to give you a little more information once I've done that.

**Comment by SJReese** [comment] 2015-07-20 14:51
It looks like the file archives in the rpm file are somehow duplicated. If I extract the file archives with the command 'rpm2cpio ejabberd-15.06-0.x86_64.rpm | cpio -imd', I get a whole slew of errors stating that file was not created because a newer or same age version alread exists for files in /opt/ejabberd-15.06/lib/kernel.  There are 167 duplicates, some in lib/kernel and some in lib/stdlib. Somehow the cpio archive has duplicate copies of the files and the error that's generated extracting them causes rpm to abort.

**Comment by SJReese** [comment] 2015-07-20 15:02
If I had to guess, I would say that when the rpm is being created, cpio is seeing the original files for kernel and stdlib in their original folders (kernel-3.2 and stdlib-2.4) and through their symlinks (kernel and stdlib) and adding them into the archive twice.

When I package in rpm, usually just add the files in the files section and create any symlinks that are needed in the install section. That might work around this problem.

**Comment by btv** [comment] 2015-07-20 22:48
Scott, thank you for putting in all that time and effort.

**Comment by Gvaska** [comment] 2015-08-11 12:28
Any progress on this issue? Thanks.

**Comment by Mezzano** [comment] 2015-08-20 13:36
Hello, the error is still there. Where can I find previous rpm?

**Comment by michaelansel** [comment] 2015-09-24 21:35
Any chance of open sourcing the spec file for this so I can take a shot at fixing it? (or see if just rebuilding on SL6 fixes the problem)

**Comment by mremond** [comment] 2015-09-25 07:04
We do not use a spec file, we are using a tool to generate installer and packages.

**Comment by cromain** [comment] 2015-10-22 13:51
issue is fixed and will be included in 15.10

**Comment by rom1dep** [comment] 2016-06-07 15:13
It appears that the error is back on 16.04:

```
Running Transaction
  Installing : ejabberd-16.04-0.x86_64                                                                                                                               1/1 
Error unpacking rpm package ejabberd-16.04-0.x86_64
error: unpacking of archive failed on file /opt/ejabberd-16.04/lib/kernel: cpio: rename
```

**Comment by pravinchandar** [comment] 2016-06-09 05:20
Yes, the error has crept in 16.04.

**Comment by cromain** [comment] 2016-06-17 13:51
Indeed, this error was reinjected by mistake when upgrading erlang to 18.3. This is now fixed for further installers.

**Closed by cromain** 2016-06-17 13:51 UTC
Labels: Component:Installers

**Comment by RobertLarsen** [comment] 2016-06-21 10:11
This is with the current archive from https://www.process-one.net/en/ejabberd/downloads

```
$ cat /etc/redhat-release && md5sum ejabberd-16.04-0.x86_64.rpm && sudo yum -y install ejabberd-16.04-0.x86_64.rpm | tail
CentOS release 6.5 (Final)
dcf496d73fac9e977915e5758038d9a6  ejabberd-16.04-0.x86_64.rpm
Error unpacking rpm package ejabberd-16.04-0.x86_64
Transaction Test Succeeded
Running Transaction
  Installing : ejabberd-16.04-0.x86_64                                      1/1 
error: unpacking of archive failed on file /opt/ejabberd-16.04/lib/kernel: cpio: rename
  Verifying  : ejabberd-16.04-0.x86_64                                      1/1 

Failed:
  ejabberd.x86_64 0:16.04-0                                                     

Complete!
```
