### ISSUE TITLE
subscription="none" attribute missing

### ISSUE THREAD

**Issue by darix** [processone/ejabberd#1853] opened 2017-07-11 09:40 UTC
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

openSUSE Leap 42.3

> How did you install ejabberd (source, package, distribution)?

my distro package.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

roster elements without a subscription throw an error in irssi-xmpp. @weiss tracked it down to a missing subscription="none" in:

```
<item ask='subscribe' name='Alice' jid='alice@example.com'/>
```

**Comment by zinid** [comment] 2017-07-11 09:57
Duplicate of #1590

**Closed by zinid** 2017-07-11 09:57 UTC
