### ISSUE TITLE
Can't login in web interface

### ISSUE THREAD

**Issue by Aravinthu** [processone/ejabberd#1263] opened 2016-08-23 05:07 UTC
> What version of ejabberd are you using?

ejabberd-16.08

> What operating system (version) are you using?

Ubuntu 14.04.5 x64

> How did you install ejabberd (source, package, distribution)?

using Linux x86 64-bits Installer (ejabberd-16.08-linux-x86_64-installer.run)

> What did not work as expected?

can't loginto admin interface

> Are there error messages in the log? 

[warning] <0.494.0>@ejabberd_web_admin:process:246 Access of <<"admin@mydomain.com">> from <<"115.135.152.186">> failed with error: <<"inexistent-account">>

> What was the unexpected behavior?

i created login,host,password during installation, after the installation i can't login using admin interface (http://mydomain.com/5280/admin)

> What was the expected result?

**must be able to login**
```
----------------------------------------------------------------------------
Please specify the directory where ejabberd will be installed.

Installation Directory [/opt/ejabberd-16.08]: 

----------------------------------------------------------------------------
ejabberd server domain

Please enter the desired ejabberd domain name. The domain is the visible 
attribute that is added to the username to form the Jabber Identifier (for 
example: user@example.net). This computer must be known on the network with this 
address name.

ejabberd server domain [mydomain.com]: 

----------------------------------------------------------------------------
Administrator username

Please enter the administrator username for the current ejabberd installation. A 
Jabber account with this username will be created and granted administrative 
privileges. Don't use blankspaces in the username. 

Administrator username [admin]: admin

----------------------------------------------------------------------------
Administrator password

Please provide a password for the administrator user (at least 5 characters).

Administrator password [********] : 123456
Retype password [********] : 123456
----------------------------------------------------------------------------
Cluster

Will this node be part of a cluster ? (Please note ejabberd clustering is 
intended for advanced users).

Cluster [y/N]: n


----------------------------------------------------------------------------
Setup is now ready to begin installing ejabberd on your computer.

Do you want to continue? [Y/n]: y

----------------------------------------------------------------------------
Please wait while Setup installs ejabberd on your computer.

 Installing
 0% ______________ 50% ______________ 100%
 ########################################
```

**Comment by badlop** [comment] 2016-08-23 10:25
Yes, it's a known bug in ejabberd 16.08. The problem is that "ejabberdctl register" doesn't work, so the installer cannot create your admin account in ejabberd.

A temporary solution: you can create that account in ejabberd using a Jabber client. After you create it, you can use it to login in the ejabberd web admin.

**Comment by cromain** [comment] 2016-09-06 08:20
fixed by #1231

**Closed by cromain** 2016-09-06 08:20 UTC
Labels: Component:API

**Comment by PavelPikat** [comment] 2016-12-06 10:38
Still doesn't work in 16.12-beta-1

**Comment by badlop** [comment] 2016-12-06 18:55
After installation, see if logs/install.log has something like this:
```
* Creating administrator user
User admin@localhost successfully registered
```

Start ejabberd and check if the account exists. Can you login to ejabberd? Is the account reported here?
```
$ ejabberdctl registered_users mydomain.com
admin
```

**Comment by nataliavalgepea** [comment] 2016-12-06 19:18
I had to manually force-change admin's password via ejabberdctl in order to login. The logs were keep on telling "bad password" even though it's 100% correct password and I even installed ejabberd 2 times and entered the same password.

**Comment by PavelPikat** [comment] 2016-12-06 19:19
I had to manually force-change admin's password via ejabberdctl in order to login. The logs were keep on telling "bad password" even though it's 100% correct password and I even installed ejabberd 2 times and entered the same password.

**Comment by badlop** [comment] 2016-12-06 20:22
And the install.log said that the account was successfully created?

Maybe the installer sets an undesired password, shorter or missing characters. Did you try providing in the installer a simple/dummy password like 123345?

**Comment by PavelPikat** [comment] 2016-12-07 09:41
I have now installed ejabberd again and it does not produce any logs after installation. There is no logs folder.

**Comment by PavelPikat** [comment] 2016-12-07 09:44
I also noticed that the 3rd installation ignored the admin password I entered (12345) - I could not log in with that password. However I could login with the password I had before uninstalling and installing again. I guess it doesn't wipe the database on uninstall/install and doesn't re-create the admin user.

**Comment by badlop** [comment] 2016-12-07 12:36
Right, the uninstalling process just removes the ejabberd binaries and scripts, it keeps the config, logs and database. That's up to you to remove.

**Comment by shubham1172** [comment] 2018-12-29 05:09
I was facing the same issue. Apparently, you have to use `admin@domain-name` as the username!
