### ISSUE TITLE
Save complex data to PostgreSQL as JSON(B) instead of Erlang terms

### ISSUE THREAD

**Issue by michalrus** [processone/ejabberd#2570] opened 2018-08-15 14:58 UTC
> What version of ejabberd are you using?

17.07.

> What operating system (version) are you using?

NixOS 17.09.

> How did you install ejabberd (source, package, distribution)?

Package.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Currently, Ejabberd saves `muc_room.opts` as:

```
[{title,<<>>},
 {description,<<>>},
 {allow_change_subj,true},
 {allow_query_users,true},
 {allow_private_messages,true},
 {allow_private_messages_from_visitors,anyone},
 {allow_visitor_status,true},
 {allow_visitor_nickchange,false},
 {public,false},
 {public_list,false},
 {persistent,true},
 {moderated,true},
 {members_by_default,false},
 {members_only,true},
 {allow_user_invites,true},
 {password_protected,false},
 {captcha_protected,false},
 {password,<<>>},
 {anonymous,false},
 {logging,false},
 {max_users,30},
 {allow_voice_requests,true},
 {allow_subscription,false},
 {mam,true},
 {presence_broadcast,[moderator,participant,visitor]},
 {voice_request_min_interval,1800},
 {vcard,<<>>},
 {captcha_whitelist,[]},
 {affiliations,[{{<<"6001f61d-bb28-4779-971d-46e7d18f84c3">>,<<"chat">>,
                  <<>>},
                 {owner,<<>>}},
                {{<<"9808c69d-c63a-4d2f-8d4b-741e834e2baa">>,<<"chat">>,
                  <<>>},
                 {member,<<"asdjknkjnasd">>}},
                {{<<"9808c69d-c63a-4d2f-8d4b-741e834e2bab">>,<<"chat">>,
                  <<>>},
                 {member,<<"sakjdnkjnasd">>}},
                {{<<"someone">>,<<"chat">>,<<>>},
                 {member,<<"dnkjnasd">>}}]},
 {subject,<<>>},
 {subject_author,<<>>},
 {subscribers,[]}]
```

… which is basically unprocessable either by PostgreSQL triggers or external code having access to the DB.

My simple use case is to return all rooms the user is affiliated with. This is impossible to do efficiently…

If it was saved in JSON by Ejabberd, I could:
* either add a JSONB index to that column and ask directly,
* or create an INSERT/UPDATE/DELETE trigger that would extract the information I’m interested in to another table for *very* quick reads.

**Comment by zinid** [comment] 2018-08-15 15:26
This is somewhat a duplicate of #1785 although my view is just use dedicated columns instead of JSON.

**Closed by zinid** 2018-08-15 15:26 UTC

**Comment by michalrus** [comment] 2018-08-16 09:04
Kk.
