### ISSUE TITLE
How to question XMPP

### ISSUE THREAD

**Issue by nOmi7** [processone/ejabberd#1497] opened 2017-01-27 15:40 UTC
> What version of ejabberd are you using?
17.01.45

> What operating system (version) are you using?
deb

> How did you install ejabberd (source, package, distribution)?
source

new deps/xmpp project has spec file which then is used to generate the xmpp_codec.erl
%% Created automatically by XML generator (fxml_gen.erl)
%% Source: xmpp_codec.spec

We have few custom stanzas and i would like to include them for encoding and decoding.
for this 
1) I need any pointers on how to best write the spec for stanza in xmpp_codec.spec
2) once written how and what to execute to generate the xmpp_codec.erl file.

there is no enough doc for https://github.com/processone/xmpp
Please help 

Merci.

**Comment by zinid** [comment] 2017-01-27 15:54
This is a duplicate of https://github.com/processone/xmpp/issues/6

**Closed by zinid** 2017-01-27 15:54 UTC
