### ISSUE TITLE
Prepared statements errors

### ISSUE THREAD

**Issue by sschimmel** [processone/ejabberd#3090] opened 2019-11-21 14:44 UTC
## Environment

- ejabberd version: 19.09
- Erlang version: Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:10] [kernel-poll:false]
- OS: Linux (Ubuntu)
- Installed from: official deb/rpm
- Database: PostgreSQL

## Errors from error.log

```
2019-11-21 14:32:11.950 [error] <0.550.0>@ejabberd_sql:sql_query_internal:590 PREPARE failed for SQL query at {mod_muc_sql,151}: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"42P05">>},{message,<<"prepared statement \"Q31669562\" already exists">>},{file,<<"prepare.c">>},{line,473},{routine,<<"StorePreparedStatement">>}]
...
2019-11-21 14:32:14.268 [error] <0.554.0>@ejabberd_sql:check_error:1195 SQL query 'Q30103238' at {mod_shared_roster_sql,60} failed: [{severity,'ERROR'},{86,<<"ERROR">>},{code,<<"26000">>},{message,<<"prepared statement \"Q30103238\" does not exist">>},{file,<<"prepare.c">>},{line,512},{routine,<<"FetchPreparedStatement">>}]
```
There are many more errors the same as these two.

## Bug description
In the error.log I see multiple errors about prepared statements. They seem to occur for many different modules. I have given the database user for ejabberd all permissions except for being a superuser. Creating users, sending messages etc. does work.

I've ran the sql from this file (https://github.com/processone/ejabberd/blob/master/sql/pg.sql) after I created the database. That ran without any errors.

There is data in the database so database communication does work.

**Comment by alexeyshch** [comment] 2019-11-25 14:11
Are you connecting directly to PostgreSQL, or via a pooler like PgBouncer?

**Comment by sschimmel** [comment] 2019-11-26 12:23
Through a connection pool. It's a managed service from DigitalOcean and they use PgBouncer. I've tried transaction and session based pooling methods. Both with the same result.

**Comment by alexeyshch** [comment] 2019-11-26 17:05
Duplicate of #1316.  There is an option now available in `master` to disable prepared statements:
```
sql_prepared_statements: false
```

**Closed by alexeyshch** 2019-11-26 17:05 UTC
