### ISSUE TITLE
ejabberdctl: change_room_option:  captcha_protected: throws exception

### ISSUE THREAD

**Issue by dirkmoors** [processone/ejabberd#607] opened 2015-06-18 09:47 UTC
While testing an ejabberdctl command, I've noticed the following exception
(ejabberd master branch, commit 1cf2dfe63afe0994988e756dfbb82524f50f6af8)

First, I've prepared (and checked) a room:
```
ejabberd@7a8095050707:~$ ejabberdctl create_room testroom conference example.com
ejabberd@7a8095050707:~$ ejabberdctl muc_online_rooms global
testroom@conference
ejabberd@7a8095050707:~$ ejabberdctl get_room_options testroom conference
title	
description	
allow_change_subj	true
allow_query_users	true
allow_private_messages	true
allow_private_messages_from_visitors	anyone
allow_visitor_status	true
allow_visitor_nickchange	true
public	true
public_list	true
persistent	true
moderated	true
captcha_protected	false
members_by_default	true
members_only	false
allow_user_invites	false
password_protected	false
password	
anonymous	true
allow_voice_requests	true
voice_request_min_interval	1800
max_users	200
logging	false
vcard	
captcha_whitelist	{0,nil}
```

Then, I've tried to change the room option:
```
ejabberd@7a8095050707:~$ ejabberdctl change_room_option testroom conference captcha_protected false
Problem 'error {case_clause,captcha_protected}' occurred executing the command.
Stacktrace: [{mod_muc_admin,change_option,3,
                            [{file,"src/mod_muc_admin.erl"},{line,785}]},
             {mod_muc_admin,change_room_option,3,
                            [{file,"src/mod_muc_admin.erl"},{line,769}]},
             {mod_muc_admin,change_room_option,4,
                            [{file,"src/mod_muc_admin.erl"},{line,752}]},
             {ejabberd_commands,execute_command2,2,
                                [{file,"src/ejabberd_commands.erl"},
                                 {line,320}]},
             {ejabberd_ctl,call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,292}]},
             {ejabberd_ctl,try_call_command,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,268}]},
             {ejabberd_ctl,process2,3,
                           [{file,"src/ejabberd_ctl.erl"},{line,217}]},
             {ejabberd_ctl,process,1,
                           [{file,"src/ejabberd_ctl.erl"},{line,202}]}]
```

**Comment by badlop** [comment] 2015-06-18 11:09
Duplicate of #604

**Closed by badlop** 2015-06-18 11:09 UTC
Labels: Component:Muc
