### ISSUE TITLE
Ejabberd 17.07 ignore protocol_options: - "no_sslv3"

### ISSUE THREAD

**Issue by teilva** [processone/ejabberd#1867] opened 2017-07-14 21:59 UTC
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

FreeBSD 10

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When testing the server, it is shown that the SSL v3 protocol is available, with an explicit prohibition.
On version 16, everything worked fine.

**Comment by zinid** [comment] 2017-07-16 05:17
Duplicate of #1863

**Closed by zinid** 2017-07-16 05:17 UTC
