### ISSUE TITLE
Crash after password reset

### ISSUE THREAD

**Issue by aidecoe** [processone/ejabberd#1295] opened 2016-09-14 06:24 UTC
> What version of ejabberd are you using?

16.04

> What operating system (version) are you using?

Gentoo.

> How did you install ejabberd (source, package, distribution)?

Source package from main Gentoo repository.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

User's password has been reset to a new one and he tried to login and send a message. The issue happened just once. The user's client is ChatSecure 3.2.3.

Here follows `error.log`:

```
2016-07-25 09:54:58.191 [error] <0.14099.0> gen_fsm <0.14099.0> in state wait_for_feature_request terminated with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
2016-07-25 09:54:58.203 [error] <0.14099.0> CRASH REPORT Process <0.14099.0> with 0 neighbours exited with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
2016-07-25 09:55:19.004 [error] <0.14104.0> gen_fsm <0.14104.0> in state wait_for_feature_request terminated with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
2016-07-25 09:55:19.004 [error] <0.14104.0> CRASH REPORT Process <0.14104.0> with 0 neighbours exited with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
2016-07-25 09:55:35.818 [error] <0.14106.0> gen_fsm <0.14106.0> in state wait_for_feature_request terminated with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
2016-07-25 09:55:35.818 [error] <0.14106.0> CRASH REPORT Process <0.14106.0> with 0 neighbours exited with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
2016-07-25 09:56:04.584 [error] <0.14111.0> gen_fsm <0.14111.0> in state wait_for_feature_request terminated with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
2016-07-25 09:56:04.584 [error] <0.14111.0> CRASH REPORT Process <0.14111.0> with 0 neighbours exited with reason: bad argument in call to crypto:sha_mac_n(error, <<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>, 20) in scram:hi/3 line 73
```

Here follows `crash.log`:

```
2016-07-25 09:54:58 =ERROR REPORT====
** State machine <0.14099.0> terminating 
** Last event in was {xmlstreamelement,{xmlel,<<"auth">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>},{<<"mechanism">>,<<"PLAIN">>}],[{xmlcdata,<<"AGluZ21hcgBtbjJPYjRXdQo=">>}]}}
** When State == wait_for_feature_request
**      Data  == {state,{socket_state,fast_tls,{tlssock,#Port<0.24158>,#Port<0.24159>},<0.14098.0>},ejabberd_socket,#Ref<0.0.1.80345>,false,<<"3098880215536298503">>,{sasl_state,<<"jabber">>,<<"jabber.zwiebeltoralf.de">>,<<>>,#Fun<ejabberd_c2s.2.2197914>,#Fun<ejabberd_c2s.3.2197914>,#Fun<ejabberd_c2s.4.2197914>,undefined,undefined},c2s,c2s_shaper,false,true,true,true,[verify_none,compression_none,{protocol_options,<<"no_compression|no_tlsv1_1|no_tlsv1|no_sslv3|no_sslv2">>},{ciphers,<<"ECDHE-RSA-AES256-SHA:ECDH:DH:!CAMELLIA128:!AES128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM">>},{certfile,<<"/etc/ssl/ejabberd/ejabberd.pem">>},{dhfile,<<"/etc/ssl/ejabberd/dhparams.pem">>}],false,undefined,<<>>,<<"jabber.zwiebeltoralf.de">>,<<>>,{{1469,433297,19},<0.14099.0>},{pres_t,0},{pres_f,0},{pres_a,0},undefined,undefined,{userlist,none,[],false},unknown,unknown,{{10754,33032,19008,36248,37924,59838,43962,46706},61422},[],active,[],inactive,undefined,undefined,1000,undefined,300,300,false,0,0,true,<<>>}
** Reason for termination = 
** {badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]}
2016-07-25 09:54:58 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.14099.0>
    registered_name: []
    exception exit: {{badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.495.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.24159>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7008
  neighbours:
2016-07-25 09:55:19 =ERROR REPORT====
** State machine <0.14104.0> terminating 
** Last event in was {xmlstreamelement,{xmlel,<<"auth">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>},{<<"mechanism">>,<<"PLAIN">>}],[{xmlcdata,<<"AGluZ21hcgBtbjJPYjRXdQo=">>}]}}
** When State == wait_for_feature_request
**      Data  == {state,{socket_state,fast_tls,{tlssock,#Port<0.24160>,#Port<0.24161>},<0.14103.0>},ejabberd_socket,#Ref<0.0.1.80365>,false,<<"12934727037708130250">>,{sasl_state,<<"jabber">>,<<"jabber.zwiebeltoralf.de">>,<<>>,#Fun<ejabberd_c2s.2.2197914>,#Fun<ejabberd_c2s.3.2197914>,#Fun<ejabberd_c2s.4.2197914>,undefined,undefined},c2s,c2s_shaper,false,true,true,true,[verify_none,compression_none,{protocol_options,<<"no_compression|no_tlsv1_1|no_tlsv1|no_sslv3|no_sslv2">>},{ciphers,<<"ECDHE-RSA-AES256-SHA:ECDH:DH:!CAMELLIA128:!AES128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM">>},{certfile,<<"/etc/ssl/ejabberd/ejabberd.pem">>},{dhfile,<<"/etc/ssl/ejabberd/dhparams.pem">>}],false,undefined,<<>>,<<"jabber.zwiebeltoralf.de">>,<<>>,{{1469,433318,20},<0.14104.0>},{pres_t,0},{pres_f,0},{pres_a,0},undefined,undefined,{userlist,none,[],false},unknown,unknown,{{10754,33032,19008,36248,37924,59838,43962,46706},61432},[],active,[],inactive,undefined,undefined,1000,undefined,300,300,false,0,0,true,<<>>}
** Reason for termination = 
** {badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]}
2016-07-25 09:55:19 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.14104.0>
    registered_name: []
    exception exit: {{badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.495.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.24161>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7008
  neighbours:
2016-07-25 09:55:35 =ERROR REPORT====
** State machine <0.14106.0> terminating 
** Last event in was {xmlstreamelement,{xmlel,<<"auth">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>},{<<"mechanism">>,<<"PLAIN">>}],[{xmlcdata,<<"AGluZ21hcgBtbjJPYjRXdQo=">>}]}}
** When State == wait_for_feature_request
**      Data  == {state,{socket_state,fast_tls,{tlssock,#Port<0.24162>,#Port<0.24163>},<0.14105.0>},ejabberd_socket,#Ref<0.0.1.80382>,false,<<"7699501695650291719">>,{sasl_state,<<"jabber">>,<<"jabber.zwiebeltoralf.de">>,<<>>,#Fun<ejabberd_c2s.2.2197914>,#Fun<ejabberd_c2s.3.2197914>,#Fun<ejabberd_c2s.4.2197914>,undefined,undefined},c2s,c2s_shaper,false,true,true,true,[verify_none,compression_none,{protocol_options,<<"no_compression|no_tlsv1_1|no_tlsv1|no_sslv3|no_sslv2">>},{ciphers,<<"ECDHE-RSA-AES256-SHA:ECDH:DH:!CAMELLIA128:!AES128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM">>},{certfile,<<"/etc/ssl/ejabberd/ejabberd.pem">>},{dhfile,<<"/etc/ssl/ejabberd/dhparams.pem">>}],false,undefined,<<>>,<<"jabber.zwiebeltoralf.de">>,<<>>,{{1469,433335,21},<0.14106.0>},{pres_t,0},{pres_f,0},{pres_a,0},undefined,undefined,{userlist,none,[],false},unknown,unknown,{{10754,33032,19008,36248,37924,59838,43962,46706},61443},[],active,[],inactive,undefined,undefined,1000,undefined,300,300,false,0,0,true,<<>>}
** Reason for termination = 
** {badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]}
2016-07-25 09:55:35 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.14106.0>
    registered_name: []
    exception exit: {{badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.495.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.24163>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7008
  neighbours:
2016-07-25 09:56:04 =ERROR REPORT====
** State machine <0.14111.0> terminating 
** Last event in was {xmlstreamelement,{xmlel,<<"auth">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>},{<<"mechanism">>,<<"PLAIN">>}],[{xmlcdata,<<"AGluZ21hcgBtbjJPYjRXdQo=">>}]}}
** When State == wait_for_feature_request
**      Data  == {state,{socket_state,fast_tls,{tlssock,#Port<0.24164>,#Port<0.24165>},<0.14110.0>},ejabberd_socket,#Ref<0.0.1.80407>,false,<<"14443379310566582543">>,{sasl_state,<<"jabber">>,<<"jabber.zwiebeltoralf.de">>,<<>>,#Fun<ejabberd_c2s.2.2197914>,#Fun<ejabberd_c2s.3.2197914>,#Fun<ejabberd_c2s.4.2197914>,undefined,undefined},c2s,c2s_shaper,false,true,true,true,[verify_none,compression_none,{protocol_options,<<"no_compression|no_tlsv1_1|no_tlsv1|no_sslv3|no_sslv2">>},{ciphers,<<"ECDHE-RSA-AES256-SHA:ECDH:DH:!CAMELLIA128:!AES128:!3DES:!MD5:!RC4:!aNULL:!NULL:!EXPORT:!LOW:!MEDIUM">>},{certfile,<<"/etc/ssl/ejabberd/ejabberd.pem">>},{dhfile,<<"/etc/ssl/ejabberd/dhparams.pem">>}],false,undefined,<<>>,<<"jabber.zwiebeltoralf.de">>,<<>>,{{1469,433364,22},<0.14111.0>},{pres_t,0},{pres_f,0},{pres_a,0},undefined,undefined,{userlist,none,[],false},unknown,unknown,{{10754,33032,19008,36248,37924,59838,43962,46706},61454},[],active,[],inactive,undefined,undefined,1000,undefined,300,300,false,0,0,true,<<>>}
** Reason for termination = 
** {badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]}
2016-07-25 09:56:04 =CRASH REPORT====
  crasher:
    initial call: gen:init_it/6
    pid: <0.14111.0>
    registered_name: []
    exception exit: {{badarg,[{crypto,sha_mac_n,[error,<<79,103,224,133,46,244,34,23,98,95,199,199,141,33,206,62,0,0,0,1>>,20],[]},{scram,hi,3,[{file,"src/scram.erl"},{line,73}]},{ejabberd_auth_mnesia,is_password_scram_valid,2,[{file,"src/ejabberd_auth_mnesia.erl"},{line,467}]},{ejabberd_auth,check_password_loop,2,[{file,"src/ejabberd_auth.erl"},{line,160}]},{cyrsasl_plain,mech_step,2,[{file,"src/cyrsasl_plain.erl"},{line,48}]},{cyrsasl,server_step,2,[{file,"src/cyrsasl.erl"},{line,194}]},{ejabberd_c2s,wait_for_feature_request,2,[{file,"src/ejabberd_c2s.erl"},{line,748}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
    ancestors: [<0.495.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.24165>]
    dictionary: [{'$internal_queue_len',0}]
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 7008
  neighbours:
```

Attachments:
- [ejabberd.yml](https://bugs.gentoo.org/attachment.cgi?id=442662)

**Comment by zinid** [comment] 2016-12-29 12:31
Seems like the issue happens when PLAIN authentication is applied to a scrammed password.
This is a minor issue, but should be fixed.

**Comment by aidecoe** [comment] 2017-01-25 21:44
Has the issue been fixed in newer releases?

**Comment by zinid** [comment] 2017-01-26 06:51
Ha, no.
The issue is unassigned and everyone forgot about it probably.
By the way, did you report the issue to ChatSecure? Because this is also a client issue.

**Comment by toralf** [comment] 2017-01-26 22:07
Hhm, I didn't not report it to ChatSecure (and in fact, I never managed to get ChatSecure up and running at a Samsung S5 Neo - I gave up it eventually)

**Comment by zinid** [comment] 2017-02-11 07:29
After some investigation, I found that the password contains a control character (`\n`) and SASLprep doesn't allow such characters. So, basically, the problem is a duplicate of #996. I don't know why that issue is closed, this is definitely a problem in ejabberd (it should not raise crash reports).

**Comment by zinid** [comment] 2017-02-12 07:18
Fixed

**Closed by zinid** 2017-02-12 07:18 UTC
Labels: Component:Authentication, Kind:Bug
