### ISSUE TITLE
Failed RPC connection when try join_cluster

### ISSUE THREAD

**Issue by vcarro** [processone/ejabberd#2105] opened 2017-11-15 11:50 UTC
> What version of ejabberd are you using?

17.09

> What operating system (version) are you using?

Debian wheezy
Erlang version 17.5.3

> How did you install ejabberd (source, package, distribution)?

source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

We updated ejabberd from 17.08 to 17.09 2 cluster nodes. We left_cluster in node1, updated ejabberd and join cluster again to node2 -> was ok.
Then we did the same in the other node, left_cluster in node2, updated ejabberd and join cluster again to node1. -> this was not ok and said:

nodo2:~# ejabberdctl join_cluster ejabberd@nodo1
Failed RPC connection to the node ejabberd@nodo2: timeout

  The message said timeout in the local host.

  We tried step by step:

  Run ejabberd in node2 -> ok
  ejabberdctl --node ejabberd@node2 debug

(ejabberd@node2)1> node().
ejabberd@node2
(ejabberd@node2)2> Minode = ejabberd@node1.
ejabberd@node1
(ejabberd@node2)3> net_adm:ping(Minode).      
pong
(ejabberd@node2)4> application:stop(ejabberd).
ok
(ejabberd@node2)5> application:stop(mnesia).  
ok
(ejabberd@node2)6> mnesia:delete_schema([node()]).
ok
(ejabberd@node2)7> application:start(mnesia).
ok
(ejabberd@node2)8> mnesia:change_config(extra_db_nodes, [Minode]).
  
The latest command never finish and in the log (with log level at 5) do not show anything. Latest message is:

2017-11-15 12:35:41.613 [info] <0.7.0> Application mnesia started on node ejabberd@node2

Any clue of which could be the problem?

**Comment by cromain** [comment] 2017-11-16 14:09
your post is confusing. is it node1 or nodo1 ? i assume this was a typo.
Failed RPC connection to the node ejabberd@nodo2: timeout -> this means node name could be resolved but tcp connection could not be done, likely firewall or ethernet config trouble.
if you use firewall, check FIREWALL_WINDOW in ejabberdctl.cfg

about your manual steps blocking at extra_db_nodes, is ejabberd running on ejabberd@node1 ? It MUST be running in order to rpc and duplicate mnesia schema.

**Comment by vcarro** [comment] 2017-11-16 14:51
Thanks for your reply. Yes it was a mistake when translate the data from Spanish to English. We do not have any firewall, node1 and node2 resolves correctly and the two machines are in the same network. The cluster was working until We updated the ejabberd servers.

I put the manual steps of join_cluster command because We tried to clarified in which step the command stop. When we tried this manual steps, ejabberd is running in node1 and node2 and We attached a debug session to this ejabberd running in node2 and run the commands 1 by 1.

Which could be the reason because mnesia:change_config(extra_db_nodes, [Minode]) never finish?

**Comment by cromain** [comment] 2017-11-17 09:51
No idea for now. I guess your local mnesia copy have issue. We need to ensure you get a clean environment.
1. have node1 running correctly
2. get a clean installation of node2, copy cookie file and node1's config, and remove all previous mnesia database 'rm -Rf database/*'
3. start node2, then call join_cluster again.

**Comment by cromain** [comment] 2017-12-20 13:44
I'm closing this issue, it's likely a duplicate of #2079 and i'll work on it.

**Closed by cromain** 2017-12-20 13:44 UTC
