### ISSUE TITLE
xep-357

### ISSUE THREAD

**Issue by hasil86** [processone/ejabberd#1379] opened 2016-11-11 08:18 UTC
> What version of ejabberd are you using?

ejabberd-16.09

> What operating system (version) are you using?

UBUNTU 14.04
> How did you install ejabberd (source, package, distribution)?
INSTALLER

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
Is mod_push or oshiya module is working ejabberd offical release or not.

If working i need some configuration details.

**Comment by weiss** [comment] 2016-11-11 09:53
> Is mod_push or oshiya module is working ejabberd offical release or not.

See the [README][1] file of royneary/mod_push:

> for now an [ejabberd branch][2] with mod_push-specific modifications is needed

[1]: https://github.com/royneary/mod_push/blob/master/README.md
[2]: https://github.com/royneary/ejabberd/tree/mod_push_adjustments

**Comment by devurandom** [comment] 2017-02-09 20:24
Has that branch been merged already? Are there any plans to get XEP-0357 support into ejabberd mainline? it would be great to have such support in ejabberd, since afaik iOS cannot be supported in a useful way otherwise.

**Comment by zinid** [comment] 2017-02-09 20:55
I'm strongly against merging, because the code is of a very poor quality.

**Comment by devurandom** [comment] 2017-02-11 09:03
Are there any plans to get XEP-0357 support into ejabberd?

**Comment by zinid** [comment] 2017-02-11 10:11
Yes, but not in 17.02.
In 17.03 likely.

**Comment by devurandom** [comment] 2017-02-12 16:08
Thanks for the info!

Would it be possible to reopen this issue until XEP-0357 support is integrated in ejabberd, so people like me, who would like to use it, but don't want to patch the source, get notified of its availability?

**Comment by zinid** [comment] 2017-02-12 16:19
@devurandom sure, here you are ;)

**Comment by urzds** [comment] 2017-04-04 09:31
In case anyone else wonders: This did not make it into [17.03](https://blog.process-one.net/ejabberd-17-03/) (possibly because 17.02 was skipped entirely).

**Comment by MattRiddell** [comment] 2017-05-24 14:58
So is there a path forward for this to be supported or any way to do it?

**Comment by weiss** [comment] 2017-05-24 15:01
I think the two options are: (1) Pay someone to implement it, or (2) wait until someone does it anyway.

**Comment by MattRiddell** [comment] 2017-05-24 18:47
Is there any bounty board or something that I could post an offer on?

**Comment by zinid** [comment] 2017-05-24 19:12
I see some problems with the XEP, from [XEP-0357](https://xmpp.org/extensions/xep-0357.html):
> Last Updated:	2016-02-16

It should be deferred, no?

**Comment by GigabyteProductions** [comment] 2017-05-24 19:17
In the case of some of my users, this XEP implementation is necessary. I hate the idea of push notifications, despite the resource advantages. However, as far as I understand, users of ChatSecure on iOS cannot make the app maintain a background connection.

**Comment by zinid** [comment] 2017-05-24 19:18
JFYI, I asked [here](https://mail.jabber.org/pipermail/standards/2017-May/032659.html) about the XEP's state.

**Comment by stevenlivz** [comment] 2017-05-24 19:21
It suggests at the top that it can be used experimentally ... I would also be of the opinion it would be a huge advantage to try this now .... Irrespective of the specifics, the mobile iOS architecture in particular will mean some form of notification will be required.

**Comment by MattRiddell** [comment] 2017-05-24 19:25
Yeah, it was a client wanting to use ChatSecure that brought me to it too.

**Comment by zinid** [comment] 2017-05-24 19:27
Do ChatSecure developers maintain their push service? What's its XMPP address?

**Comment by MattRiddell** [comment] 2017-05-24 19:30
If you add an account that doesn't support XEP-0357 it says the server is incompatible and provides the following details:

https://push.chatsecure.org/api/v1
pubsub.chatsecure.org

**Comment by GigabyteProductions** [comment] 2017-05-24 19:30
Up-to-date ChatSecure clients claim ejabberd is "incompatible" and is vocal about it being due to Push Notifications (making me think the push server is up-to-date). The address presented to me in a screenshot is push.chatsecure.org/api/v1.

**Comment by GigabyteProductions** [comment] 2017-05-24 19:31
@MattRiddell: You beat me to it.

**Comment by MattRiddell** [comment] 2017-05-24 19:31
:-)

**Comment by zinid** [comment] 2017-05-24 19:33
Yeah, there is definitely something alive at that address.

**Comment by zinid** [comment] 2017-05-24 19:37
Looking at the XEP it will take a day or so of development. It's really simple if we don't need XMPP Push Service functionality.
@weiss, any pitfalls I don't see?

**Comment by GigabyteProductions** [comment] 2017-05-24 19:39
Not that I can see. All the vendor-specific or proprietary things are handled by each application's push server. ejabberd only needs to send the notification to that server (which the client provides over PubSub, if I understand the standard correctly).

**Comment by stevenlivz** [comment] 2017-05-24 19:42
I'm not using ChatSecure but my own client. I have written notification backends for Cordova a couple of years ago, so I was just going to plug something in to route messages to an external component (possibly via pubsub) but I suspect it would get complex ... How do you know when to send a notification if it is/is not received and so on. Can be done as in xep 0198 but not sure of all the detail of implementation.

**Comment by zinid** [comment] 2017-05-24 19:44
> How do you know when to send a notification if it is/is not received and so on. Can be done as in xep 0198 but not sure of all the detail of implementation.

This is the most tricky question for me. I'm thinking to do this in 'offline hook'. But having all the complexity of sm/MAM/carbons I'm not sure this will work as expected.

**Comment by GigabyteProductions** [comment] 2017-05-24 19:54
Not sure if this is the intention, but there is potential that a client is enabling/disabling push notifications as it comes online or goes offline (See: https://xmpp.org/extensions/xep-0357.html#disabling).

As far as I understand, push notifications simply hint at an application/device to come back online. Obtaining the messages is just the normal routine a client goes through when it comes online. If the client is already online and receives a push notification, the job of coming online is already done and there should be no interference expected.

**Comment by stevenlivz** [comment] 2017-05-24 19:54
I had considered that you could send if you never got a reply before the "timeout" config setting but you could opt to set the resume_timeout if you'd rather use that. This is when using SM with resumption.

Course this may not work in other scenarios.

**Comment by stevenlivz** [comment] 2017-05-24 19:58
@gigabyteproductions yes, it behaves a lot like pubsub where you just get an id but you can send a small amount of data (such as an id to look up) to the mobile apps but mostly it acts as a ping.

**Comment by MattRiddell** [comment] 2017-07-26 17:51
Hi,

How would one go about testing this?

**Comment by zinid** [comment] 2017-07-26 19:12
@MattRiddell there are tests in the PR.

**Comment by MattRiddell** [comment] 2017-07-27 21:22
How do I checkout a version with these changes in it?

**Comment by MattRiddell** [comment] 2017-07-28 15:12
Ok, so I got the pull request and compiled and installed it.

It now says XEP 357 is supported in server info, but when chatsecure gets pushed to the background it doesn't get any push notifications.

I didn't notice any debug information - is there anything that needs to be done other than the mod_push stanza?

The error I got back from Adium was:

`Message delivery to xxx@xxx/chatsecure50001 failed: User session terminated (Code 503)`

**Comment by weiss** [comment] 2017-07-28 15:22
> It now says XEP 357 is supported in server info

ChatSecure says that?

> when chatsecure gets pushed to the background it doesn't get any push notifications.

Please enable `[debug]` output (`ejabberdctl set-loglevel 5`), send a message to the disconnected ChatSecure client, and then grep your `ejabberd.log` file like this:

    egrep 'mod_push|pubsub.chatsecure.org' ejabberd.log

**Comment by MattRiddell** [comment] 2017-07-28 15:43
```2017-07-28 15:42:50.333 [debug] <0.489.0>@mod_push:offline_message:357 Notifying admin1@xx.myserver.com of offline message
        {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
            <<"pubsub.chatsecure.org">>,<<>>},
        {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
            <<"pubsub.chatsecure.org">>,<<>>},
2017-07-28 15:42:50.335 [debug] <0.489.0>@ejabberd_s2s:start_connection:394 Finding connection for {<<"xx.myserver.com">>,<<"pubsub.chatsecure.org">>}
2017-07-28 15:42:50.335 [debug] <0.495.0>@ejabberd_socket:send:216 (tls|<0.496.0>) Send XML on stream = <<"<iq to='pubsub.chatsecure.org' from='xx.myserver.com' type='set' id='15713308906823514013'><pubsub xmlns='http://jabber.org/protocol/pubsub'><publish node='FBF1152E-D770-4275-A9D5-2F583796C17D'><item><notification xmlns='urn:xmpp:push:0'/></item></publish><publish-options><x type='submit' xmlns='jabber:x:data'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='token'><value>89587e091056a158248d2b50165f987bb85294a5</value></field><field var='endpoint'><value>https://push.chatsecure.org/api/v1/messages/</value></field></x></publish-options></pubsub></iq>">>
2017-07-28 15:42:50.379 [debug] <0.497.0>@ejabberd_receiver:process_data:284 Received XML on stream = <<"<iq from=\"pubsub.chatsecure.org\" to=\"xx.myserver.com\" id=\"15713308906823514013\" type=\"result\"/>">>
    from = {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
                <<"pubsub.chatsecure.org">>,<<>>},
    from = {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
                <<"pubsub.chatsecure.org">>,<<>>},
2017-07-28 15:42:51.765 [debug] <0.489.0>@mod_push:offline_message:357 Notifying admin1@xx.myserver.com of offline message
        {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
            <<"pubsub.chatsecure.org">>,<<>>},
        {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
            <<"pubsub.chatsecure.org">>,<<>>},
2017-07-28 15:42:51.767 [debug] <0.489.0>@ejabberd_s2s:start_connection:394 Finding connection for {<<"xx.myserver.com">>,<<"pubsub.chatsecure.org">>}
2017-07-28 15:42:51.767 [debug] <0.495.0>@ejabberd_socket:send:216 (tls|<0.496.0>) Send XML on stream = <<"<iq to='pubsub.chatsecure.org' from='xx.myserver.com' type='set' id='17304543133720921266'><pubsub xmlns='http://jabber.org/protocol/pubsub'><publish node='FBF1152E-D770-4275-A9D5-2F583796C17D'><item><notification xmlns='urn:xmpp:push:0'/></item></publish><publish-options><x type='submit' xmlns='jabber:x:data'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='token'><value>89587e091056a158248d2b50165f987bb85294a5</value></field><field var='endpoint'><value>https://push.chatsecure.org/api/v1/messages/</value></field></x></publish-options></pubsub></iq>">>
2017-07-28 15:42:51.810 [debug] <0.497.0>@ejabberd_receiver:process_data:284 Received XML on stream = <<"<iq from=\"pubsub.chatsecure.org\" to=\"xx.myserver.com\" id=\"17304543133720921266\" type=\"result\"/>">>
    from = {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
                <<"pubsub.chatsecure.org">>,<<>>},
    from = {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
                <<"pubsub.chatsecure.org">>,<<>>},
2017-07-28 15:42:51.898 [debug] <0.489.0>@mod_push:offline_message:357 Notifying admin1@xx.myserver.com of offline message
        {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
            <<"pubsub.chatsecure.org">>,<<>>},
        {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
            <<"pubsub.chatsecure.org">>,<<>>},
2017-07-28 15:42:51.900 [debug] <0.489.0>@ejabberd_s2s:start_connection:394 Finding connection for {<<"xx.myserver.com">>,<<"pubsub.chatsecure.org">>}
2017-07-28 15:42:51.901 [debug] <0.495.0>@ejabberd_socket:send:216 (tls|<0.496.0>) Send XML on stream = <<"<iq to='pubsub.chatsecure.org' from='xx.myserver.com' type='set' id='16674502085422866324'><pubsub xmlns='http://jabber.org/protocol/pubsub'><publish node='FBF1152E-D770-4275-A9D5-2F583796C17D'><item><notification xmlns='urn:xmpp:push:0'/></item></publish><publish-options><x type='submit' xmlns='jabber:x:data'><field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var='token'><value>89587e091056a158248d2b50165f987bb85294a5</value></field><field var='endpoint'><value>https://push.chatsecure.org/api/v1/messages/</value></field></x></publish-options></pubsub></iq>">>
2017-07-28 15:42:51.945 [debug] <0.497.0>@ejabberd_receiver:process_data:284 Received XML on stream = <<"<iq from=\"pubsub.chatsecure.org\" to=\"xx.myserver.com\" id=\"16674502085422866324\" type=\"result\"/>">>
    from = {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
                <<"pubsub.chatsecure.org">>,<<>>},
    from = {jid,<<>>,<<"pubsub.chatsecure.org">>,<<>>,<<>>,
                <<"pubsub.chatsecure.org">>,<<>>},```

**Comment by MattRiddell** [comment] 2017-07-28 15:47
Actually it might have been that I didn't have an s2s cert installed.

If I don't force quit ChatSecure, but do load up a few other apps (theoretically pushing it into the background) it appears to work.

Will try again in another few hours to be sure.

**Comment by weiss** [comment] 2017-07-28 16:17
> Actually it might have been that I didn't have an s2s cert installed.

Hm yes, I think `pubsub.chatsecure.org` insisted on a trusted certificate in the past.  Then again, in your log snippet it's actually acknowledging the notification:

> `Received XML on stream = <<"<iq from=\"pubsub.chatsecure.org\" to=\"xx.myserver.com\" id=\"16674502085422866324\" type=\"result\"/>">>`

So `mod_push` seems to be working fine, here.

**Comment by weiss** [comment] 2017-07-28 16:22
> just tried again now after a couple of minutes and no push again.

The issue is probably on ChatSecure's side.  See https://github.com/ChatSecure/ChatSecure-iOS/issues/770 and various other push notification issues in the [ChatSecure tracker][1].  At least people seem to be [working on it][2].

[1]: https://github.com/ChatSecure/ChatSecure-iOS/issues
[2]: https://github.com/ChatSecure/ChatSecure-iOS/issues/770#issuecomment-314782754

**Comment by MattRiddell** [comment] 2017-07-28 16:23
Ah ok, cool thanks for that :-)

**Comment by MattRiddell** [comment] 2017-07-29 17:58
Once I applied this [patch](https://groups.google.com/forum/#!topic/prosody-dev/Ge3USXmuMIc) to prosody it works fine in ChatSecure, but not with ejabberd

**Comment by weiss** [comment] 2017-07-29 21:00
> Once I applied this [patch](https://groups.google.com/forum/#!topic/prosody-dev/Ge3USXmuMIc) to prosody it works fine in ChatSecure

Sounds good.

> but not with ejabberd

Chris' [proposal][1] is just one or two days old, and [other solutions][2] to the same problem were suggested as well.  Let's wait a bit to see whether people agree on something.

Either way, I'm fine with the general idea, and I'll be happy to implement whatever solution Chris ends up with.

[1]: https://mail.jabber.org/pipermail/standards/2017-July/033085.html
[2]: https://github.com/ChatSecure/ChatSecure-iOS/issues/637#issuecomment-285828038

**Comment by cromain** [comment] 2017-08-02 13:54
closing this thread, follow xep-0357 on PR #1881

**Closed by cromain** 2017-08-02 13:54 UTC
Labels: Kind:Enhancement
