### ISSUE TITLE
ejabberd_c2s:process_info: got unexpected info

### ISSUE THREAD

**Issue by dhiru1602** [processone/ejabberd#1846] opened 2017-07-09 12:33 UTC
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Debian Jessie

> How did you install ejabberd (source, package, distribution)?

https://apt.jabber.at

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I have a shared roster group setup so that every registered user will have every other registered user in their roster. I have followed the guide from the link: https://www.ejabberd.im/shared-roster-all (Example 1: everybody can see everybody else)

The roster group works fine and every registered user is able to see every other registered user and their online status. However, In the server logs I see the following spam.

`[warning] <0.9062.4>@ejabberd_c2s:process_info:247 got unexpected info: {item,{<<"user1">>,<<"example.com">>,<<>>},both}`
`[warning] <0.9062.4>@ejabberd_c2s:process_info:247 got unexpected info: {item,{<<"user2">>,<<"example.com">>,<<>>},both}`
`[warning] <0.9062.4>@ejabberd_c2s:process_info:247 got unexpected info: {item,{<<"user3">>,<<"example.com">>,<<>>},both}`

Everytime a user logs in, the above warning is printed repeatedly with the names of all the other registered users. This causes the ejabberd.log file to grow very big. Is there any way I can fix or prevent the warning from being logged?

**Comment by zinid** [comment] 2017-07-10 05:44
This is a bug in `mod_shared_roster`. I mark it as to be fixed by 17.08

**Comment by cromain** [comment] 2017-08-08 08:57
mod_shared_roster needs complete rewrite, so we change schedule for this to be correctly done

**Comment by genodeftest** [comment] 2017-08-18 08:24
Looks like a duplicate of #1651 to me.

**Comment by zinid** [comment] 2017-08-18 08:36
@genodeftest yes, definitely

**Comment by cC-Xx** [comment] 2017-10-10 07:32
hi 
we have a loop here, #1651 linked to #1846 and #1846 linked to #1651. what to do to avoid this error?

**Comment by m1cka** [comment] 2017-10-29 16:08
hi,
i updated  ejabberd 17.06 to 17.09.
OS centos 7.4
backend: mysql 5.7
php: 7.1
same problem:
[warning] <0.767.0>@ejabberd_c2s:process_info:254 got unexpected info: {item,{<<"username">>,<<"hostname.com">>,<<>>},both}
  
 mod_roster:
    db_type: sql
  mod_shared_roster:
    db_type: sql

**Comment by acrixl** [comment] 2017-11-06 09:05
ejabberd-17.09
debian 9.1
backend: mnesia
[warning] <0.1289.0>@ejabberd_c2s:process_info:254 got unexpected info: {item,{<<"user">>,<<"domain.com">>,<<>>},both}

**Comment by cromain** [comment] 2017-11-22 10:28
added #1706 for resolution, which should fix this issue.

**Comment by iprok** [comment] 2018-01-24 16:57
Just have updated to 18.01. The issue is still here

**Comment by miniskipper** [comment] 2018-02-16 15:07
Can also confirm that the issue is still there in 18.01.

**Comment by zinid** [comment] 2018-03-19 09:36
It would be great if someone can test the fix.

**Closed** 2018-03-19 09:35 UTC
Labels: Kind:Bug

**Comment by cC-Xx** [comment] 2018-03-19 09:39
fix not tested yet, but already closed? nice ...

**Comment by cC-Xx** [comment] 2018-03-19 15:28
didn't understand why you deleted my message ... 

server refused to start with your patch against FreeBSD's port ... 

2018-03-19 18:25:31.946 [error] <0.244.0> Supervisor ejabberd_sup had child ejabberd_gen_mod_sup started with gen_mod:start_link() at undefined exit with reason {'EXIT',{function_clause,[{mod_roster,mod_opt_type,[''],[{file,"src/mod_roster.erl"},{line,1186}]},{gen_mod,get_validators,3,[{file,"src/gen_mod.erl"},{line,461}]},{gen_mod,validate_opts,3,[{file,"src/gen_mod.erl"},{line,502}]},{gen_mod,start_module,4,[{file,"src/gen_mod.erl"},{line,195}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{gen_mod,start_link,0,[{file,"src/gen_mod.erl"},{line,79}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,...}]}} in context start_error

**Comment by zinid** [comment] 2018-03-19 15:31
> server refused to start with your patch against FreeBSD's port

Because you cannot simply apply the patch to some random ejabberd version.

**Comment by cC-Xx** [comment] 2018-03-19 15:32
it's not random

**Comment by zinid** [comment] 2018-03-19 15:33
> it's not random

Who knows, from your comment it's unclear.

**Comment by cC-Xx** [comment] 2018-03-19 15:34
https://www.freshports.org/net-im/ejabberd

**Comment by zinid** [comment] 2018-03-19 15:39
You cannot apply the patch to 18.01

**Comment by cC-Xx** [comment] 2018-03-19 15:41
hm ... ok ... how to fix error mentioned in subject in version 18.01? is it possible?

**Comment by zinid** [comment] 2018-03-19 15:42
> is it possible?

Most likely not.

**Comment by cC-Xx** [comment] 2018-03-19 15:46
it's not bug, it's a feature? how to fix it? fetch fresh sources (with your patches) from github and try to use it in production? or how?

**Comment by zinid** [comment] 2018-03-19 15:50
> it's not bug, it's a feature? how to fix it? fetch fresh sources (with your patches) from github and try to use it in production? or how?

I don't think it's a terribly great idea to test this in production. What I really asked to test is only the stuff that didn't work for you and only in the case when it's easy to reproduce the bug in testing environment.

**Comment by cC-Xx** [comment] 2018-03-19 15:53
yes, server refused to start ...

**Comment by zinid** [comment] 2018-03-19 15:54
Whatever, seems like there are people willing to test it. Also, the stuff I test myself works: roster gets populated, presences get routed, `@all@` works correctly, no "unexpected info" in the log.

**Comment by Akasch** [comment] 2018-03-19 18:26
For me it seems to work, the errors after login are fixed. Using extauth_program and mod_shared_roster. I think I will test tomorrow with more users.

**Comment by Neustradamus** [comment] 2018-03-21 00:19
@Akasch it is good?

**Comment by Akasch** [comment] 2018-03-23 13:27
@Neustradamus it works, but if your groups are very big (we had ~1700 jids in some) the Database is swamped with a very height load. For our Server the 40.000 Selects per second there not enough to not fall behind on message processing
