### ISSUE TITLE
Fetch Muc occupants from SQL

### ISSUE THREAD

**Issue by axcl** [processone/ejabberd#3210] opened 2020-04-03 20:42 UTC
Hi,

I am wondering where occupants are stored of the server. And how can they be stored in sql or fetch from command line.

Actually i want to sort room list on basis of occupants and other factors too such as paid rooms.

Any pointers to how to start snd achieve this will be great

**Comment by licaon-kter** [comment] 2020-04-03 23:23
/close this as not a bug


Join xmpp:ejabberd@conference.process-one.net?join instead

**Comment by prefiks** [comment] 2020-04-06 05:44
Current occupants aren't stored in db, they are kept in process state responsible for handling given muc room. You probably could use some command from mod_muc_admin to get that info, like get_room_occupants.

**Closed by prefiks** 2020-04-06 05:44 UTC
