### ISSUE TITLE
modules->mod_http_upload->thumbnail: ejabberd is built without image converter support

### ISSUE THREAD

**Issue by Escloupe** [processone/ejabberd#3514] opened 2021-02-04 10:03 UTC
## Environment

- ejabberd version: 21.01
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.3.4
- OS: Linux (CentOS8)
- Installed from:  official deb/rpm 

## Bug description

Hi, it's seems that jabbed isn't compiled with GD Library in RPM package and we can't use "thumbnail: true" in "mod_http_upload"

## Log : 

2021-02-04 10:45:44.749 [critical] <0.107.0>@ejabberd_app:start:72 Failed to start ejabberd application: Invalid value of option modules->mod_http_upload->thumbnail: ejabberd is built without image converter support

**Comment by badlop** [comment] 2021-02-04 12:53
Quick way to check if thumbnail option will work: start with "ejabberdctl live" and check:
```erlang
eimp:supported_formats().
```
If it returns `[]` then thumbnail conversion won't work.

Related tickets: https://github.com/processone/ejabberd/issues/2716 https://github.com/processone/ejabberd/issues/2898

**Comment by Escloupe** [comment] 2021-02-04 13:01
When I start ejabberd with "thumbnail: false", like you say I get : 

(ejabberd@localhost)1> eimp:supported_formats().
[]

When I start ejabberd with "thumbnail: true", it crash and I get :

(ejabberd@localhost)1> 13:58:35.694 [critical] Failed to start ejabberd application: Invalid value of option modules->mod_http_upload->thumbnail: ejabberd is built without image converter support

**Comment by ravermeister** [comment] 2021-03-14 10:13
I get the same error and installed via the [installer script](https://www.process-one.net/downloads/downloads-action.php?file=/21.01/ejabberd-21.01-linux-x64.run)

**Comment by badlop** [comment] 2021-03-16 15:54
Umm, did that feature work ever in the installers? I tried older versions, hoping that it worked before and got broken in the meantime... but it seems that never worked. Can anybody confirm this?

**Comment by tacerus** [comment] 2021-08-21 11:42
It'd be cool to have the packaged version (in my case the official .rpm) built with the necessary options in order to be able to use the option out of the box. :)

**Comment by badlop** [comment] 2022-05-23 13:19
Since ejabberd 22.05, there are new installers, built using a different method. However, it seems this problem still appears, at least in my test:

```
$HOME/opt/ejabberd-22.05/bin/ejabberdctl live
...
2022-05-23 15:18:04.255849+02:00 [info] ejabberd 22.5.0 is started in the node ejabberd@localhost in 2.78s
...
(ejabberd@localhost)1> eimp:supported_formats().
[]
```

After some changes applied to Makefile.in for #3823, the new installers (available in https://github.com/processone/ejabberd/actions/runs/2371098801) provide this result:

```
$HOME/opt/ejabberd-22.05.28/bin/ejabberdctl live
...
22-05-23 15:15:58.466144+02:00 [info] ejabberd 22.5.28 is started in the node ejabberd@localhost in 1.25s
...
(ejabberd@localhost)1> eimp:supported_formats().
[gif]
```

**Comment by badlop** [comment] 2022-05-23 15:27
@weiss when you have spare time, can you take a look?

**Comment by badlop** [comment] 2022-05-26 09:54
It works great now!

1. Download new installers from https://github.com/processone/ejabberd/actions/runs/2386498239
2. Install
```
sudo dpkg -i ejabberd_22.05.32-1_amd64.deb
```
3. Start ejabberd:
```
sudo /opt/ejabberd-22.05.32/bin/ejabberdctl live
```
4. In that erlang shell:
```
(ejabberd@localhost)1> eimp:supported_formats().
[webp,jpeg,png,gif]
```

**Comment by LB-Aurochs** [comment] 2022-06-13 12:25
@badlop Hi
I'm a beginner and I have the same problem on version 22.05. I'm trying to figure out how to fix this without success.
On Debian 11 ejaberred configured OK, no thumbnail. If activation of the option has "true" ejaberred failed.

Exactly the same in Ubuntu 20.04.

I would like to make the correction, but I am completely skating on the manipulations to be done. Also is the link expired?

**Comment by weiss** [comment] 2022-06-13 12:33
@LB-Aurochs, please mention:

* What package you installed. E.g., an official distribution package or an upstream DEB package and which version exactly.  You could show the output `dpkg -l ejabberd`, for example.

* How did ejabberd "fail". Do you see an error message on startup and/or in the logs? What error exactly?

* Just out of curiosity, why do you need that feature? You're building a custom client?

**Comment by LB-Aurochs** [comment] 2022-06-13 12:42
>  sorry.
No personalized client, but I'm testing yaml service for an association.

Yes Deb packet -> ejabberd_22.05-2_amd64.deb

![image](https://user-images.githubusercontent.com/107409151/173355536-f28cf705-43c1-45d8-ba4a-3e0d006cdad0.png)


@weiss

**Comment by weiss** [comment] 2022-06-13 13:24
> ejabberd_22.05-2_amd64.deb

I can indeed reproduce the issue with that package.  It will be fixed for the next ejabberd release.  If you need this feature immediately, you could try the binary packages auto-published for the current Git code, e.g.:

https://github.com/processone/ejabberd/actions/runs/2483263104

**Closed by weiss** 2022-06-13 13:24 UTC
Labels: Packaging:Installer
