### ISSUE TITLE
ejabberd mod_mam archive and archive_prefs tables are missed when exporting mnesia database to SQL file via ejabberdctl export2sql command

### ISSUE THREAD

**Issue by MurzNN** [processone/ejabberd#1510] opened 2017-02-01 13:27 UTC
I moving database of working ejabberd 16.09 server from mnesia to mysql format. So at first - I export mnesia database to file via command:
```
ejabberdctl export2sql my.jabberdomain.com /tmp/db_dump.sql
```
Seems all exports normally without errors and warning messages. But after importing I see that mod_mam tables "archive" and "archive_prefs" totally missed in sql dump file. But in mnesia I see archive_msg.DAT and archive_prefs.DAT files with many records.

How can I dump or export ejabberd mod_mam table "archive" and "archive_prefs" data to SQL file, for importing to MySQL database?

**Comment by MurzNN** [comment] 2017-02-01 13:34
Maybe I can set exact table name that I want to export to SQL in `ejabberdctl export2sql` command?

**Comment by badlop** [comment] 2017-02-02 20:25
Looking at the source code this is not a bug. mod_mam does not implement Mnesia export.

**Comment by MurzNN** [comment] 2017-02-03 05:49
@badlop, thanks for the quick reply! Will wait for fixes in new versions. At now maybe I can manually extract data from Mnesia database for mod_mam module? Is there any command line scripts for export Mnesia database exist in ejabberd?

**Comment by badlop** [comment] 2017-02-03 10:03
You can try "ejabberdctl dump ejabberd.dump", which dumps internal Mnesia database to a text file dump, written in the erlang data format.

**Comment by MurzNN** [comment] 2017-02-06 09:54
@badlop thanks, I got this in xml format, so how can parse and import to mysql by hands.
Will wait when mod_mam implement Mnesia export to sql.

**Comment by themaverik** [comment] 2017-05-02 05:25
@MurzNN Did you find any tool, I was looking for the same, but I could not find any, so I wrote a module [here](https://github.com/themaverik/mod_mam_export) only for the MAM archives.

**Comment by badlop** [comment] 2017-05-03 10:36
@themaverik From what I see, you almost have it! You just have to add an export/1 function to mod_mam_sql.erl and reuse the code you wrote for mysql_store. See mod_roster_sql.erl for example. If you can implement and submit a patch or Pull Request, I'll be happy to review and commit.

**Comment by themaverik** [comment] 2017-05-03 20:17
Thanks @badlop. I'm also thinking the same. I will try as soon as I get time.

**Comment by themaverik** [comment] 2017-05-07 13:07
@badlop I've added export function in this commit [bcc9b65](https://github.com/themaverik/ejabberd/commit/bcc9b6540a750595e5145f8fe8c8c9ee8afe3d77). I hope this feature will be included in the future release.

**Comment by badlop** [comment] 2017-05-10 08:44
Thanks, I'll review it now.

**Comment by badlop** [comment] 2017-05-10 09:23
Great, I've pushed your commit, also your other fix, and a minor function calling fix.

**Closed** 2017-05-10 09:23 UTC
Labels: Component:Databases, Component:MAM, Kind:Feature

**Comment by themaverik** [comment] 2017-06-24 19:54
@badlop There is a bug which I found after testing the export for mam archives. It requires a small fix for mod_mam_sql. Please compare it [here](https://github.com/themaverik/ejabberd/commit/5b97509082da90069728ce1417884842133fd942). When referencing the username it should not refer to the peers username.
