### ISSUE TITLE
Mysql driver leaking connections

### ISSUE THREAD

**Issue by mgpld** [processone/ejabberd#64] opened 2013-04-20 17:47 UTC
Mysql_conn.erl tries to close a socket 

``` erlang
init(Host, Port, User, Password, Database, LogFun, Parent) ->
    case mysql_recv:start_link(Host, Port, LogFun, self()) of
        {ok, RecvPid, Sock} ->
            case mysql_init(Sock, RecvPid, User, Password, LogFun) of
                {ok, Version} ->
                    case do_query(Sock, RecvPid, LogFun, "use " ++ Database,
                                  Version, [{result_type, binary}]) of
                        {error, MySQLRes} ->
                            mysql:log(LogFun, error,
                                      "mysql_conn: Failed changing"
                                      " to database ~p : ~p",
                                      [Database,
                                       mysql:get_result_reason(MySQLRes)]),

                            gen_tcp:close(Sock), % THIS SOCKET BELONGS TO mysql_recv process

                            Parent ! {mysql_conn, self(),
                                      {error, failed_changing_database}};
                        %% ResultType: data | updated
```

Similarly when the close message is sent the code tries to access this socket:

``` erlang
        close ->
            mysql:log(State#state.log_fun, error, "mysql_conn: "
                      "Received close signal, exiting.", []),
            close_connection(State);
```

``` erlang
close_connection(State) ->

    Result = gen_tcp:close(State#state.socket), %% THIS SOCKET BELONGS TO mysql_recv

    mysql:log(State#state.log_fun,  normal, "Closing connection ~p: ~p~n",
              [State#state.socket, Result]),
    Result. 
```

gen_tcp:set_controlling_process or sending the stop signal to mysql_recv are a possible fix.

**Comment by cromain** [comment] 2016-12-21 15:08
investigations and fix can be planed in January

**Comment by cromain** [comment] 2017-01-13 09:55
We want a clean/stable 17.01
As we can reproduce error conditions in a test environment, possible fix will be injected in next beta, to come right after 17.01 release.

**Comment by cromain** [comment] 2017-04-06 11:48
We'll need more time to validate possible fix works and does not break things, this will be delayed...

**Comment by Neustradamus** [comment] 2021-04-13 12:41
@mgpld: It has been solved?

**Comment by badlop** [comment] 2021-05-07 14:37
> Mysql driver leaking connections

I cannot reproduce that problem... or maybe I don't understand what exactly is the problem.

1. I setup ejabberd with two vhosts, one uses mnesia and the seconf vhost uses a mysql database for auth.

2. When ejabberd starts, it creates:
 A) an erlang process with `p1_mysql_conn`
 B) another  erlang process with `p1_mysql_recv`, linked to A)
 C) a `gen_tcp` port linked to B)

3. Then I modify ejabberd configuration, so the second vhost no longer uses mysql database. And run: `ejabberdctl reload_config`

4. Then I check using erlang's Observer that A, B, and C are immediately closed.

**Closed** 2021-07-06 18:12 UTC
Labels: Component:Databases, Note:Cannot reproduce
