### ISSUE TITLE
muc offline messages

### ISSUE THREAD

**Issue by dirkmoors** [processone/ejabberd#697] opened 2015-08-04 20:11 UTC
What is the recommended way to implement push notifications (e.g. trigger some webservice) to offline users? In my use case, I've got members-only rooms where I want to be able to send messages, and if the message is not delivered right away (because the user is offline, network flaky, etc), Ejabberd should trigger a webservice that dispatches the message as a push notification (Android, iOS, ...).

How would I approach this?

p.s. I don't know any Erlang, otherwise I would have attempted to write a plugin or something....

**Comment by dirkmoors** [comment] 2015-08-04 20:32
Also, this might be interesting approach, what do you guys think?

https://github.com/ChatSecure/ChatSecure-Push-Server/blob/master/docs/v3/README.md

**Comment by nunohorta** [comment] 2015-08-06 14:27
Why don't you use a hook to listen for offline messages and to call a script that sends notifications using any library of your choice?

**Comment by dirkmoors** [comment] 2015-08-06 14:45
@nunohorta I've worked with an offline message hook already, but it doesn't work with MUC afaik. In an open MUC room, where there are no 'fixed members', I understand the irrelevance of offline messages, but in my scenario, I only have rooms where there are specific members, that need to be notified if they're not online.

**Comment by mremond** [comment] 2015-08-06 14:54
@dirkmoors MUC are indeed presence based. It is indeed not designed to care of offline users.
The XMPP Standards Foundation started thinking about what is call MUC2, that would make it possible in a clean way.

To be frank, we have done thing for customers but nothing we have the right to share yet.
However, we are willing to work actively on the MUC2 approach.

**Comment by dirkmoors** [comment] 2015-08-06 15:04
@mremond Aren't there any plugins available that are able to trigger a webservice, when a message is delivered into a muc room, and not all members are online?

**Comment by mremond** [comment] 2015-08-06 15:22
Not that I know of. However, it should be easier to write with the new `muc_message_filter` API. However, this trigger is unrelated to the fact that members in the member list are online or not. You would have to do the check in the code before triggering any remote call if you wish to.

**Comment by nunohorta** [comment] 2015-08-07 10:22
@dirkmoors Okay now I understand what you need. I'm actually working on something similar. I've barely started but my idea is to use the new muc_message_filter like @mremond said above. I will also be listening for presence changes on chat rooms(https://github.com/processone/ejabberd/commit/6e61932765f9ae8e290b88cce5c2ed574fb4bbe7), thank you @zinid ! This will work, I hope, because I do all the management of users and chat rooms on my server using php and the ejabberd_xmlrpc module, meaning that when a message is sent to a group, I call a script that checks offline users "in" that group and sends push notifications. This will be used in groups with around 50 people max. I believe more then that could cause performance issues depending on the server.

**Comment by dirkmoors** [comment] 2015-08-07 10:44
@nunohorta that is probably what I need too. My use case is similar, but I'll be managing the users from within a Django (python) application, via XMLRPC (actually, I've written an open source python library for that purpose: https://github.com/dirkmoors/pyejabberd). Are you implementing an erlang-based plugin? Or how do you anticipate implementing this feature?

**Comment by nunohorta** [comment] 2015-08-07 13:01
@dirkmoors That looks really good! I'm using a php library that I developed myself but can't share unfortunately because it's part of a software that is not mine. To be more specific I'll listen to presence changes and chat room messages with modules that I developed. Those modules send a post request to a url in my system that caches online/offline users and sends notifications to their devices when offline. The other data I have it stored on a database because I developed a backend to manage user connections and chat rooms with a nice interface. This also runs on php and uses the xmlrpc API to call Ejabberd methods

**Comment by dirkmoors** [comment] 2015-08-07 14:06
@nunohorta Yeah I did something similar: the exact approach I tried was running a 'bot' (I've used SleekXMPP, a Python library) that connects to all the rooms to listen to the messages and presence, and updates the local database accordingly, sending push notifications to offline room members. I'm afraid that this approach is not scalable (I have no idea how much MUC rooms this 'bot' can process simultaneously)

**Comment by EugeneNews** [comment] 2015-08-07 16:45
@nunohorta it might be easier for you to read `StateData` right from `muc_message_filter` - which will give you online occupants for "right now". So that list of online users + <message> = is what you use to generate push on your PHP server - but just for other/offline users.
at least, this is how i do that))

**Comment by nunohorta** [comment] 2015-08-10 08:30
thanks @EugeneNews ! I hope to start this over the week. It seems like a good solution!

**Comment by nunohorta** [comment] 2015-08-13 10:25
@EugeneNews  could you help using the muc_message_filter? How can I read the body from Stanza argument? This is what I have so far https://gist.github.com/nunohorta/fd8ecf46267deef16d86 . If you could help that would be great.

**Comment by EugeneNews** [comment] 2015-08-13 12:33
@nunohorta i'm doing it with mapping list of users 
```
  _LISTUSERS = lists:map(
    fun({_LJID, Info}) ->
      binary_to_list(Info#user.jid#jid.luser) ++ ".."
    end,
    dict:to_list(MUCState#state.users)),
  ?DEBUG(" #########    GROUPCHAT _LISTUSERS = ~p~n  #######   ", [_LISTUSERS])
```
you see, I'm using ".." as a separator in the string, because i like to send all users as just 1 parametor in POST request. But if advance fun() you may get LIST/array to convert it to smthn you need...

**Comment by FlowerWrong** [comment] 2015-08-25 08:20
:8ball: I have the same question.

**Comment by dirkmoors** [comment] 2015-09-03 10:59
Is there anyone willing to implement an (open source) Ejabberd plugin that -once a MUC room has MEMBER affiliations- simply triggers a REST/webservice, notifying which MEMBERS are offline, and which message did not get to them. I think a lot of developers would benefit from such a plugin?

**Comment by zinid** [comment] 2015-09-03 11:25
@dirkmoors I think better approach is never to go offline. Client developers should be encouraged to implement XEP-0198.
I also do not understand the dance around affiliations. Have you ever seen MUC rooms with 1000 members in the list? Your REST/webservice will die during notifications.

**Comment by dirkmoors** [comment] 2015-09-03 11:35
@zinid In many usecases, you're talking of less members. Think intranet chat application, friend-groups, etc. In those usecases, I think it would make perfect sense to notify a webservice?

Moreover, never going offline seems hard in mobile environments, which by nature do not provide stable connectivity?

**Comment by zinid** [comment] 2015-09-03 11:47
> Moreover, never going offline seems hard in mobile environments, which by nature do not provide stable connectivity?

Actually with XEP-0198 you can be always online. XEP-0198 will transparently resume your session during re-login.

**Comment by dirkmoors** [comment] 2015-09-03 11:52
That sounds very interesting! I'm going to look into that XEP definitely.

Nevertheless; triggering a webservice to notify about offline room members would make (mobile) push notifications to mobile devices very straightforward to implement. Or would you suggest another approach to achieve this?

**Comment by zinid** [comment] 2015-09-03 12:01
> Nevertheless; triggering a webservice to notify about offline room members would make (mobile) push notifications to mobile devices very straightforward to implement. Or would you suggest another approach to achieve this?

I think push notifications should be triggerd when a client is disconnected from the server, but its session is alive (due to XEP-0198 "hibernation").

**Comment by weiss** [comment] 2015-09-03 12:48
> triggering a webservice to notify about offline room members would make (mobile) push notifications to mobile devices very straightforward to implement.

Is this about making room messages available to offline members, or about generating push notifications to mobile clients, or both?  These are somewhat unrelated topics which require separate solutions.

Anyway, it's not quite obvious to me how a web service would be specifically useful to solve either of these things, as opposed to having an ejabberd module do whatever the web service would do.  But yes, it could be done this way, just as a web service could handle any other event within ejabberd, of course.

**Comment by dirkmoors** [comment] 2015-09-03 12:49
@zinid That might be a good 'trigger to send a push notification' yes, but there still needs to be a party responsible for sending the actual push notification. In my mind, the simple solution would be to offload that responsibility to a seperate (web)service.

**Comment by joaoffm** [comment] 2015-09-23 15:32
Don't know much about erlang, just what I learned in the past week and taking into account all the links and feedback posted I've been able to "build" a mod for what's requested

https://github.com/diamondbybold/ejabberd_mod_offline_post

**Comment by cisiqo** [comment] 2015-11-09 03:01
I also  have the same question. Finally i have update 3 files to realize. The module are ejabberd_sm、mod_muc_room、mod_offline.

https://github.com/cisiqo/ejabberd-module-dev

**Comment by Hiren701** [comment] 2015-12-28 13:34
i have same issue , let me give some more detail.
i have implimented ejabberd 15.11,  i have used mod_http_offline module to send offline notification.
i am able to start and complile my module. but when user send offline message i got below error in my error log,  can anyone  please suggest whare i am wrong .

         2015-12-28 21:13:28.971 [error] <0.37.0>@ejabberd_config:validate_opts:794 unknown option 'loopback' will be likely ignored
         2015-12-28 21:13:28.971 [error] <0.37.0>@ejabberd_config:validate_opts:794 unknown option 'local' will be likely ignored
         [error] <0.524.0>@ejabberd_hooks:run1:332 {function_clause,[{lists,thing_to_list,[<<>>],[{file,"lists.erl"},{line,601}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1248}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1248}]},{mod_http_offline,post_offline_message,2,[{file,"mod_http_offline.erl"},{line,43}]},{ejabberd_hooks,safe_apply,3,[{file,"src/ejabberd_hooks.erl"},{line,382}]},{ejabberd_hooks,run1,3,[{file,"src/ejabberd_hooks.erl"},{line,329}]},{ejabberd_sm,route,3,[{file,"src/ejabberd_sm.erl"},{line,111}]},{ejabberd_local,route,3,[{file,"src/ejabberd_local.erl"},{line,112}]}]}

       running hook: {offline_message_hook,[{jid,<<"911234567891">>,<<"xyz.com">>,<<"42629891761451308446954821">>,<<"111111111111">>,<<"xyz.com">>,<<"42629891761451308446954821">>},{jid,<<"33333333">>,<<"xyz.com">>,<<>>,<<"111111111">>,<<"xyz.com">>,<<>>},{xmlel,<<"message">>,[{<<"id">>,<<"Ge62DNXY">>},{<<"type">>,<<"One2One">>},{<<"to">>,<<"121212121@xyz.com">>}],[{xmlel,<<"msgtype">>,[],[{xmlcdata<<"chat">>}]},{xmlel,<<"body">>,[],[{xmlcdata,<<"T2s=">>}]},{xmlel,<<"FrontParterPic">>,[],[{xmlcdata,<<"57_1447745086.jpg">>}]},{xmlel,<<<"x">>,[{<<"xmlns">>,<<"jabber:x:event">>}],[{xmlel,<<"offline">>,[],[]},{xmlel,<<"delivered">>,[],[]}]}]}]}

**Comment by mremond** [comment] 2015-12-28 13:54
@Hiren701 The problem is in https://github.com/raelmax/mod_http_offline/ not in ejabberd. That module is not compliant with latest ejabberd apparently.

**Comment by bangarharshit** [comment] 2016-01-16 05:09
@zinid , I am using session resumption with large resumption time - 24 hours. I have a  doubt about muc, if I am in group and my client rejoin, do I need to leave and rejoin the group to get the new messages.  For non muc stanzas, they are kept in offline storage and delivered as soon as I reconnect. But I am not sure about muc. 

If it is not so the case I don't think there is any advantage of being online - except to fetch occupants list. Again I am not sure if I will get occupant joined event if my client was offline.

**Comment by weiss** [comment] 2016-01-16 22:08
> I am using session resumption with large resumption time - 24 hours. I have a doubt about muc, if I am in group and my client rejoin, do I need to leave and rejoin the group to get the new messages.

No.  If your client is resuming the stream management session, then you never left the room and there's no reason to rejoin it.  You would receive the missing room messages during resumption.

**Comment by sh-al** [comment] 2016-01-21 10:42
what i did:
1. all rooms created with members_by_default: true options
2. modified mod_muc room so it would route incoming packets for all room members, except banned one
3. modified ejabberd sm module, so it would call offline_message_hook for messages with type = groupchat.
4. when offline_message_hook is called, i send push notification When user connects, he receives all messages from muc room as usual offline messages

I have some doubts that this is the best way to do it

**Comment by rubenjavier** [comment] 2016-02-04 08:04
Hello sh-al,
could you please share the code you used for steps 2 and 3?

"2. modified mod_muc room so it would route incoming packets for all room members, except the banned one
3. modified ejabberd sm module so it would call offline_message_hook for messages with type = groupchat."

This sound like a good solution for many of my scenarios
Thanks in Advance,

Best Regards

**Comment by Everhusk** [comment] 2016-02-08 08:26
+1

**Comment by mremond** [comment] 2016-06-29 08:25
Closing, we are preparing some extension that could help with this in the future.

**Closed by mremond** 2016-06-29 08:25 UTC

**Comment by dirkmoors** [comment] 2016-06-29 08:37
@mremond Do you have more info about that extension? Where can I learn more about it?

**Comment by mremond** [comment] 2016-07-08 14:33
Here is MUC Sub extension: https://blog.process-one.net/xmpp-mobile-groupchat-introducing-muc-subscription/

**Comment by MurzNN** [comment] 2017-05-11 07:49
@mremond, can you describe some examples how to use this extension and implement in ejabberd server some multi-user Group chat with offline message delivery to each member in any Jabber client?

**Comment by MurzNN** [comment] 2017-05-11 07:50
At now our company use Jabber Bot based on https://github.com/punchagan/childrens-park that emulate group chat with offline messages, and it works well for 100+ users with massive every day talks. But bad site is that all chatrooms must be configured manually on server side.

**Comment by ismailmohammed** [comment] 2018-10-04 08:59
> Don't know much about erlang, just what I learned in the past week and taking into account all the links and feedback posted I've been able to "build" a mod for what's requested
> 
> https://github.com/diamondbybold/ejabberd_mod_offline_post

Hi,

I want to send offline message to one-to-one user as well as groups. 
when I tried compiling the module from above github url getting below errors can you help me on this. I am using ejabbered 18.01 version.

c:/Program Files/ejabberd-18.01/lib/ejabberd-18.01/include/mod_muc_room.hrl:96: type message() undefined
c:/Program Files/ejabberd-18.01/lib/ejabberd-18.01/include/mod_muc_room.hrl:97: type presence() undefined
c:/Program Files/ejabberd-18.01/lib/ejabberd-18.01/include/mod_muc_room.hrl:116: type text() undefined
c:/Program Files/ejabberd-18.01/lib/ejabberd-18.01/include/mod_offline_post.erl:4: Warning: undefined callback function depends/2 (behaviour 'gen_mod')
c:/Program Files/ejabberd-18.01/lib/ejabberd-18.01/include/mod_offline_post.erl:4: Warning: undefined callback function mod_opt_type/1 (behaviour 'gen_mod')

Thanks in Advance.

**Comment by licaon-kter** [comment] 2018-10-04 09:13
@ismailmohammed Why would you use a 3 years old module? You already have `mod_offline` included, that and MAM modules should take care of stuff.

If you compile your own do UPDATE to 18.09 and use the [config template](https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example) (that has all the good stuff enabled already) to setup your server.

**Comment by licaon-kter** [comment] 2018-10-04 09:31
Ignore this old useless module and _UPDATE to 18.09 and use the config template (that has all the good stuff enabled already) to setup your server._

**Comment by weiss** [comment] 2018-10-04 09:31
> 1:1 or group chat when user is offline i want a send a message as notification to the user.

As @mremond mentioned above, using [MUC/Sub][1] solves this issue.

For standard clients that don't use this extension, [`mod_push_keepalive`][2] tries to work around the problem by keeping the [XEP-0198][3] session online until at least one push notification was sent.

[1]: https://blog.process-one.net/xmpp-mobile-groupchat-introducing-muc-subscription/
[2]: https://docs.ejabberd.im/admin/configuration/#mod-push-keepalive
[3]: https://xmpp.org/extensions/xep-0198.html

**Comment by ismailmohammed** [comment] 2018-10-04 10:29
thanks for the update.

you mean to say once upgrade to 18.09 version with given configration user will be able to get 1:1 and group offline notifications to mobile(andriod\IOS)?

Thanks,
Ismail

**Comment by licaon-kter** [comment] 2018-10-04 10:36
@ismailmohammed Yes, of course.

After you're done with the setup, run it through https://compliance.conversations.im/ and see if everything works ok ;)

**Comment by ismailmohammed** [comment] 2018-10-04 11:31
I have uninstalled the previous version and installed 18.09 version and changed some configurations settings. Need to test it.

but still, I have doubt how ejabbered will send mobile push notifications to Andriod and IOS mobiles without any configurations like APNS,FCM etc?

Thanks in advance
Ismail.

**Comment by licaon-kter** [comment] 2018-10-04 11:37
Push config is done in the client application (Conversations on Android from Play store or ChatSecure on iOS)

**Comment by ismailmohammed** [comment] 2018-10-04 14:34
Hi,

I have started 18.09 with configuration shared.

one of my colleague who's developing IOS app he is trying to enable push notification from his code and he is getting below error can you please suggest me on this error.

<iq xmlns="jabber:client" lang="en" to="ksrinivas@2ry27h2-l/40AFC2A6-DD77-47C9-A38D-7417BAEC16DA" from="ksrinivas@2ry27h2-l" type="error" id="2333CC7D-38CE-4A95-A93E-187A996FC39E"><enable xmlns="urn:xmpp:push:0" jid="admin@2ry27h2-l" node="40AFC2A6-DD77-47C9-A38D-7417BAEC16DA"><x xmlns="jabber:x:data" type="submit"><field var="FORM_TYPE"><value>http://jabber.org/protocol/pubsub#publish-options</value></field><field var="device_id"><value>4dd9a938d9d7376dba04295a63a6a15b508058d81e0dfaa8cb267130d2765af2</value></field><field var="topic"><value>com.audlink.KConnect</value></field><field var="service"><value>apns</value></field><field var="mode"><value>dev</value></field></x></enable><delay xmlns="urn:xmpp:delay" stamp="2018-10-04T13:25:38Z">Retransmission</delay><error code="400" type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" lang="en">Too many child elements</text></error></iq>


Thanks,
Md.Ismail.

**Comment by lakmalniranga** [comment] 2019-02-15 11:40
@ismailmohammed Have you figure it out a way to trigger HTTP request for group offline messages?

**Comment by ismailmohammed** [comment] 2019-02-16 06:12
Yes I did.

Thank you.
