### ISSUE TITLE
Compile Error 17.09 

### ISSUE THREAD

**Issue by RamzyVirani** [processone/ejabberd#2032] opened 2017-10-04 15:33 UTC
> What version of ejabberd are you using?
17.09

> What operating system (version) are you using?
CentOS 7

> How did you install ejabberd (source, package, distribution)?
Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?
I am getting below error when executing `make` 

```
Compiled src/xep0280.erl
/opt/ejabberd/deps/xmpp/xmpp_codec: function get_mod/2+2689:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_test_tail2,{f,862},[{x,5},0]}
  Error:       {no_bsm_context,{x,5}}:

Compiling /opt/ejabberd/deps/xmpp/src/xmpp_codec.erl failed:
ERROR: compile failed while processing /opt/ejabberd/deps/xmpp: rebar_abort
make: *** [deps/.built] Error 1
```

**Comment by erdna1982** [comment] 2017-10-04 15:45
same on Debian:Jessie! But I also have this problem on Version 17.08 since 28.09. 

I spend two days on this issue but didn't find any solution. Please help!

It happens from one moment to another on the last thursday (28-09). Can't build the docker container anymore...

**Comment by zinid** [comment] 2017-10-04 15:46
This is related to OTP20.1 I guess.

**Comment by zinid** [comment] 2017-10-04 15:46
Downgrade to OTP20.0

**Comment by erdna1982** [comment] 2017-10-04 15:49
Maybe can you please tell me how? I always receive the latest version from the repository.

cheers

**Comment by zinid** [comment] 2017-10-04 15:53
There is OTP20.0 in Debian SID, you can get it from that repo.

**Comment by RamzyVirani** [comment] 2017-10-04 16:15
Thank you very much. Fixed by downgrading. `yum downgrade erlang erlang-*` did the trick.
But now, I am getting another error. Apparently, downgrading erlang uninstalled gd, I installed gd by executing `yum install gd gd-devel` then got an error about `libwebp`. So, I installed libwebp via `yum install libwebp libwebp-devel`. Now, I am getting below error

```
checking for library containing gdImageCreateFromWebpPtr, gdImageWebpPtr... no
configure: error: libgd library is not compiled with WebP support
ERROR: Command [compile] failed!
make: *** [deps/.built] Error 1
```

**Comment by zinid** [comment] 2017-10-04 16:20
Seems like your gd is built without WebP support. If you don't need `mod_avatar` you can build ejabberd without graphics (`./configure --disable-graphics ...`).

**Comment by zinid** [comment] 2017-10-04 17:20
For tracking, the bug is reported here: https://bugs.erlang.org/browse/ERL-493

**Comment by RamzyVirani** [comment] 2017-10-04 17:23
Got New Error
```
==> rel (pre_compile)
ERROR: No Elixir compiler found
==> rel (compile)
==> ejabberd (compile)
ERROR: compile failed while processing /opt/ejabberd: {'EXIT',{undef,[{asn1ct,compile,
                        ["asn1/XmppAddr.asn1",[{outdir,"src"},noobj]],
                        []},
                {rebar_asn1_compiler,compile_asn1,3,
                                     [{file,"src/rebar_asn1_compiler.erl"},
                                      {line,77}]},
                {rebar_base_compiler,compile_each,3,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,135}]},
                {rebar_base_compiler,run,4,
                                     [{file,"src/rebar_base_compiler.erl"},
                                      {line,44}]},
                {rebar_core,run_modules,4,
                            [{file,"src/rebar_core.erl"},{line,493}]},
                {rebar_core,execute,6,
                            [{file,"src/rebar_core.erl"},{line,418}]},
                {rebar_core,maybe_execute,8,
                            [{file,"src/rebar_core.erl"},{line,302}]},
                {rebar_core,process_dir1,7,
                            [{file,"src/rebar_core.erl"},{line,261}]}]}}
make: *** [deps/.built] Error 1
```
and various warnings like 
`warning: Dict.put/3 is deprecated, use the Map module for working with maps or the Keyword module for working with keyword lists`
`src/elixir_errors.erl:303: Warning: erlang:get_stacktrace/0 used following a 'try' expression may stop working in a future release. (Use it inside 'try'.)`
and
`warning: behaviour String.Chars is undefined`

**Comment by zinid** [comment] 2017-10-04 17:25
This is unrelated, nobody will be concerned if you post different issues in a single issue.

**Comment by erdna1982** [comment] 2017-10-05 10:42
the debian sid installs the 20.1 and i can't figure out how can i install a espacially OTP release like OTP20. 

if i want build the docker container the following packages have unmet dependencies:

 erlang-percept : Depends: erlang-base (= 1:17.3-dfsg-4+deb8u1) but 1:20.1.1+dfsg-1 is to be installed or
                           erlang-base-hipe (= 1:17.3-dfsg-4+deb8u1) but it is not going to be installed
                  Depends: erlang-inets (= 1:17.3-dfsg-4+deb8u1) but 1:20.1.1+dfsg-1 is to be installed
                  Depends: erlang-runtime-tools (= 1:17.3-dfsg-4+deb8u1) but 1:20.1.1+dfsg-1 is to be installed
 erlang-typer : Depends: erlang-base (= 1:17.3-dfsg-4+deb8u1) but 1:20.1.1+dfsg-1 is to be installed or
                         erlang-base-hipe (= 1:17.3-dfsg-4+deb8u1) but it is not going to be installed
                Depends: erlang-dialyzer (= 1:17.3-dfsg-4+deb8u1) but 1:20.1.1+dfsg-1 is to be installed
 erlang-webtool : Depends: erlang-base (= 1:17.3-dfsg-4+deb8u1) but 1:20.1.1+dfsg-1 is to be installed or
                           erlang-base-hipe (= 1:17.3-dfsg-4+deb8u1) but it is not going to be installed
                  Depends: erlang-inets (= 1:17.3-dfsg-4+deb8u1) but 1:20.1.1+dfsg-1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by zinid** [comment] 2017-10-05 11:12
Why don't you ask on Debian forums/trackers about how to manage packages in Debian?
This is `ejabberd issue tracker` after all.

**Comment by erdna1982** [comment] 2017-10-05 11:41
This problem occurs if the DOCKERFILE will be build. I thought that will be relevant for here!?

**Comment by jacksgt** [comment] 2017-11-10 14:50
Hi, I am also encountering the same issue on `armhf`:
```
WARN:  Missing plugins: [rebar_elixir_compiler,rebar_exunit]
==> xmpp (compile)
Compiled src/xmpp_codec_external.erl
...
Compiled src/xep0158.erl
/tmp/ejabberd/deps/xmpp/xmpp_codec: function get_mod/2+2689:
  Internal consistency check failed - please report this bug.
  Instruction: {test,bs_test_tail2,{f,862},[{x,5},0]}
  Error:       {no_bsm_context,{x,5}}:

Compiling /tmp/ejabberd/deps/xmpp/src/xmpp_codec.erl failed:
ERROR: compile failed while processing /tmp/ejabberd/deps/xmpp: rebar_abort
Makefile:90: recipe for target 'deps/.built' failed
```

**Comment by zinid** [comment] 2017-11-10 15:12
@jacksgt just don't use OTP 20.1

**Comment by jacksgt** [comment] 2017-11-10 15:45
@zinid Sorry, forgot to mention that I'm using this Dockerfile from @rroemhild https://github.com/rroemhild/docker-ejabberd/blob/master/Dockerfile which uses the official repos at http://packages.erlang-solutions.com/debian

Is this repo broken then?

**Comment by zinid** [comment] 2017-11-10 15:55
I have no idea

**Comment by cromain** [comment] 2017-11-16 14:57
we have several issues with erlang version from erlang-solutions packages.
example: https://github.com/processone/xmpp/issues/17
we can't reproduce issue just using standard erlang, or from your main distro manager.
example https://packages.debian.org/search?keywords=erlang&searchon=names&suite=stable&section=all

**Comment by cromain** [comment] 2017-12-20 13:46
Fixed in next 17.12, by using OTP 20.2.

**Closed by cromain** 2017-12-20 13:46 UTC

**Comment by jacksgt** [comment] 2017-12-28 14:01
Sooo, when will 17.12 be released?

https://blog.process-one.net/tag/ejabberd/

https://github.com/processone/ejabberd/releases

**Comment by prefiks** [comment] 2017-12-28 14:02
Probably today.

**Comment by zinid** [comment] 2017-12-28 14:14
@jacksgt we're on it at the moment, have several minor problems to solve.

**Comment by jacksgt** [comment] 2017-12-29 13:34
Awesome, thank you!
