### ISSUE TITLE
mod_mam doesn't work with some configurations

### ISSUE THREAD

**Issue by zinid** [processone/ejabberd#1529] opened 2017-02-09 19:29 UTC
mod_mam doesn't work if option `default: always` is combined with `request_activates_archiving: true` and `assume_mam_usage: true`.
Related issue from StackOverflow: http://stackoverflow.com/questions/42111932/ejabberd-mod-mam-error/42131955

**Comment by weiss** [comment] 2017-02-09 20:01
I can't reproduce the problem.  Maybe the `request_activates_archiving` option is simply doing it's job?  It tells ejabberd to not start archiving until the user issued a MAM request.

**Comment by zinid** [comment] 2017-02-09 20:53
Well, yes, if the request is done, it starts working, however, this is in conflict with `default: always`.

**Comment by weiss** [comment] 2017-02-09 21:37
The option tells ejabberd to follow the `default` storage policy as soon as a MAM request was issued. It's working as intended, but I see how this can be confusing. Maybe it would be better to turn this into additional `default` values rather than having a separate option?

Then again, I haven't seen this complaint before. `request_activates_archiving` is disabled by default, and the [docs][1] explain exactly what happens if you enable it:

> If this option is enabled, no messages are stored for a user until his client issued a MAM request, regardless of the value of the `default` option. Once the server received a request, that user's messages are archived as usual.

[1]: https://docs.ejabberd.im/admin/configuration/#modmam

**Comment by zinid** [comment] 2017-02-09 21:43
According to the documentation, the option should be called `only_request_activates_archiving` ;)

**Comment by weiss** [comment] 2017-07-03 09:43
I've unassigned myself, as I'm not sure how to address this.  The `request_activates_archiving` option is confusing.  It's disabled by default, and I think the proper solution is removing it in the long run.  If all clients would support MAM, the option would make no sense anyway.  It's just a useful hack to save storage space as long as most of your clients don't support MAM.

However, if you think it's *too* confusing, I'd be fine with removing this option right away.

**Comment by cromain** [comment] 2018-04-12 15:43
@weiss is there anything required for this old issue ? should I close it ?

**Comment by weiss** [comment] 2018-04-12 15:53
I would just close it, but I'm not sure @zinid agrees :smile:

**Closed** 2018-04-12 19:18 UTC
Labels: Component:MAM, Kind:Bug, Note:Pending
