### ISSUE TITLE
X-OAUTH2 authentication failed

### ISSUE THREAD

**Issue by algore** [processone/ejabberd#1627] opened 2017-03-21 12:45 UTC
> What version of ejabberd are you using?

17.03.beta

> What operating system (version) are you using?

CentOS ( Amazon AMI )

> How did you install ejabberd (source, package, distribution)?

package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm saving oauth tokens in mysql database **oauth_token**, then i issue a token with
`$ ejabberdctl oauth_issue_token "admin@example.org" 10000 "sasl_auth"`
I'm using strophejs to implmente X-OAUTH2 but ejabberd gives this error after sending

`<body rid='2560774034' xmlns='http://jabber.org/protocol/httpbind' sid='54dfa773c209e8c10fd9f9a8431ecb3b06afa54a'><auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='X-OAUTH2'>AGJydW5vQGlwLTE3Mi0zMS01My0yNTAuZWMyLmludGVybmFsAFFVRFRHcHVXN1ZGNzFVQ3I4TE1scWtnaGxCOW4xWVJP</auth></body>`

I encoding the token as documentation

```
<auth mechanism='X-OAUTH2'
      xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
  base64("\0" + user_name + "\0" + oauth_token)
</auth>
```
```
2017-03-21 11:54:52.965 [error] <0.448.0> gen_server <0.448.0> terminated with reason: no function clause matching lists:any(#Fun<ejabberd_oauth.5.55120481>, <<"sasl_auth">>) line 1223
2017-03-21 11:54:52.966 [error] <0.448.0> CRASH REPORT Process <0.448.0> with 0 neighbours exited with reason: no function clause matching lists:any(#Fun<ejabberd_oauth.5.55120481>, <<"sasl_auth">>) line 1223 in p1_server:terminate/7 line 878
2017-03-21 11:54:52.966 [error] <0.386.0> Supervisor ejabberd_c2s_sup had child undefined started with {ejabberd_c2s,start_link,undefined} at <0.448.0> exit with reason no function clause matching lists:any(#Fun<ejabberd_oauth.5.55120481>, <<"sasl_auth">>) line 1223 in context child_terminated
```

**Comment by zinid** [comment] 2017-03-21 14:08
Duplicate of #1581

**Closed by zinid** 2017-03-21 14:08 UTC
