### ISSUE TITLE
Issue with Yaml parser and ejabberd yml configuration file

### ISSUE THREAD

**Issue by nunohorta** [processone/ejabberd#825] opened 2015-11-06 11:47 UTC
I'm using a Yaml component(http://api.symfony.com/2.7/Symfony/Component/Yaml/Yaml.html) to read the ejabberd yml file, change some settings and save it again.

The problem is that this component will remove all double quotes. Example:
`log_rotate_date: ""` 
this is the default but using Yaml component and dumping the data back to the file will result in:
`log_rotate_date: ''`
which causes ejabberd to not work. Looking at Yaml component no double quotes will be added in this case since there are no special characters to escape. I'm not sure what I'm missing here, is it an Ejabberd issue? Is there a better way to change this yml file?

**Comment by prefiks** [comment] 2015-11-06 11:57
The problem is that ejabberd uses "" and '' string to describe different things internally ("" are converted to erlang strings where '' and just bare words are used as erlang atoms). So if you change all "" strings to '', even if possible from yaml side, will make config file totally different for ejabberd.

**Comment by nunohorta** [comment] 2015-11-06 14:05
hm that kinda makes things difficult here since ejabberd uses this yaml file but doesn't quite respect its documentation. Is there any other way around? I mean, to edit this file easily using php and not going through the file manually changing all single quotes to doubles quotes etc. Thanks

**Comment by mremond** [comment] 2015-11-06 16:24
As said, this is not related to yaml but Erlang distinction between atom and string, which is different data types. Atom do not exist in Yaml.

We could imagine implicit conversion of config file when you use the wrong type. However it would take time and most user are simply using text editor to edit it.

You can always use .cfg syntax format if your prefer it (erlang tuple syntax).

**Comment by nunohorta** [comment] 2015-11-06 17:00
ok thanks! I found this fixed issue(https://github.com/processone/ejabberd/issues/803). Is it fixed on 15.10 release or should I just use the current branch?

**Comment by mremond** [comment] 2015-11-06 17:40
#803 will be included in ejabberd 15.12, but you can checkout current master HEAD to use it now.

**Comment by nunohorta** [comment] 2015-11-09 09:32
Thanks! Is there any way to use the .cfg file by itself or do I need to convert it to yaml using convert_to_yaml?

**Comment by weiss** [comment] 2015-11-09 09:59
> Is there any way to use the .cfg file by itself

You can just set `EJABBERD_CONFIG_PATH=/path/to/ejabberd.cfg` in your `ejabberdctl.cfg` and ejabberd should use that file.

**Comment by nunohorta** [comment] 2015-11-09 11:09
thank you very much!

**Closed** 2015-11-09 11:10 UTC
