### ISSUE TITLE
mam in MUC rooms not working

### ISSUE THREAD

**Issue by Natureshadow** [processone/ejabberd#890] opened 2016-01-02 15:18 UTC
I have trouble setting the mam option in a MUC room.

First, it cannot be set with ejabberdctl change_room_option, because of:

    Problem 'error {case_clause,mam}' occurred executing the command.

Second, when I get mam set to true through the default room options before creating the room, then it is indeed created with mam set to true, but the moment I join the room the mam option is reset to false.

How do I get mam working in MUC rooms?

**Comment by zinid** [comment] 2016-01-02 19:48
The first problem you described is due to this fragment of code: https://github.com/processone/ejabberd/blob/master/src/mod_muc_admin.erl#L786 (the function change_option() is incomplete and should be fixed).
Regarding the second problem: I'm not sure what you mean by the "moment you join the room". If you change default room options in the config, it is only applied to newly created rooms. In existing rooms you can change the option via room's configuration (if your client supports this).

**Comment by weiss** [comment] 2016-01-02 20:01
> First, it cannot be set with ejabberdctl change_room_option, because of:
> 
>     Problem 'error {case_clause,mam}' occurred executing the command

This is fixed, now.

> Second, when I get mam set to true through the default room options before creating the room, then it is indeed created with mam set to true, but the moment I join the room the mam option is reset to false

I can't reproduce this.  What ejabberd version and what client are you
using?  Are you running the standard mod_mam module shipped with
ejabberd?  Have you tried enabling MAM in the room configuration using a
client such as Gajim or Psi?

**Closed** 2016-01-02 20:00 UTC
