### ISSUE TITLE
bosh: stream features only sent on the first connection attempt after restarting

### ISSUE THREAD

**Issue by eloff** [processone/ejabberd#2545] opened 2018-07-26 03:17 UTC
> What version of ejabberd are you using?

ejabberd_18.06-0_amd64.deb

> What operating system (version) are you using?

Ubuntu 16.04 64bit

> How did you install ejabberd (source, package, distribution)?

from deb package

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

When I connect to bosh with Strophe.js no stream features are sent, so authentication fails. I discovered this can be remedied by setting starttls: false in the listen section of the yml config.

However, now the stream features are only sent on the first connection attempt, which succeeds. After disconnecting, refreshing the browser and trying again it will fail continuously because no stream features are sent. Issuing a ejabberdctl stop followed by ejabberdctl start fixes the problem, but only for the first connection attempt.

There are no errors in error.log, here's a log-level=5 snapshot of me alternating connecting and restarting. You can clearly see the pattern that the first attempt succeeds and subsequent ones do not until the next restart.

[tail-ejabberd.log](https://github.com/processone/ejabberd/files/2230315/tail-ejabberd.log)

**Comment by prefiks** [comment] 2018-07-26 16:19
Hello,

I seen similar trace before, but i am not able to reproduce this. What happens here is c2s process sends service header before bosh process starts processing incoming data, and when that happens because it have something queued to send it just sends it.

Let see if i can add workaround for that.

**Comment by prefiks** [comment] 2018-07-26 16:56
Should be fixed by commit: 1af2cf37ea36bb4064aeb8dd87a12a3e8a291595

**Closed by prefiks** 2018-07-26 16:56 UTC

**Comment by eloff** [comment] 2018-07-26 19:14
@prefiks  thanks you're awesome! I've verified that it solves the problem for me. If only I could get paid support that good! Can I send you a beer or something?
