### ISSUE TITLE
ejabberd-15.06 first run find many Configuration checking errors!

### ISSUE THREAD

**Issue by langzi88** [processone/ejabberd#630] opened 2015-07-01 02:23 UTC
My OS is ubuntu server 12.04 64bit. When I download ejabberd binary install packet (ejabberd-15.06-linux-x86_64-installer.run.run orejabberd_15.06-0_amd64.deb),then run ejabberdctl live in my command line,then find some   Configuration checking errors! The ejabberd.yml file is the new file install packet file.
the errors is these:
09:59:53.990 [info] Application mnesia started on node ejabberd@localhost
09:59:55.578 [error] unknown option 'shaper' will be likely ignored
09:59:55.578 [error] unknown option 'modules' will be likely ignored
09:59:55.578 [error] unknown option 'max_fsm_queue' will be likely ignored
09:59:55.578 [error] unknown option 'loglevel' will be likely ignored
09:59:55.578 [error] unknown option 'log_rotate_size' will be likely ignored
09:59:55.578 [error] unknown option 'log_rotate_date' will be likely ignored
09:59:55.578 [error] unknown option 'log_rotate_count' will be likely ignored
09:59:55.579 [error] unknown option 'log_rate_limit' will be likely ignored
09:59:55.579 [error] unknown option 'listen' will be likely ignored
09:59:55.579 [error] unknown option 'auth_method' will be likely ignored
09:59:55.579 [error] unknown option 'allow_contrib_modules' will be likely ignored
09:59:55.579 [error] unknown option 'acl' will be likely ignored
09:59:55.579 [error] unknown option 'access' will be likely ignored

**Comment by mremond** [comment] 2015-07-01 07:02
This is a duplicate of #616 
This is an harmless issue, with binary installer packaging. It will be fixed in 15.07.
However, please note that the errors are harmless. It means you can ignore the errors and your software will run without issues.

**Closed by mremond** 2015-07-01 07:02 UTC
Labels: Component:Configuration
