### ISSUE TITLE
EJA 16.03 Mod_MAM Just 1 client receive message with archived tag when login in multi resource (same priority)

### ISSUE THREAD

**Issue by bvhoang91** [processone/ejabberd#1537] opened 2017-02-13 03:50 UTC
Hi all,

I have a problem when using Mod_mam for storing message. (Ejabberd 16.03)
- User B login in multi resource (same priority).
- User A send a message to B (without resource in TO attribute).
- In server side, mod_mam check and store receive_packet for just 1 resource. So, others can't get archived info.

 So, how can I add archived info for all resources of B?
Tks.

**Comment by zinid** [comment] 2017-02-13 05:35
Message archive is "resource-independent", you can query it from any resource of the same JID. Probably what you need is message forking on all resources? In this case you need XEP-280 (implemented in `mod_carboncopy`).

**Comment by bvhoang91** [comment] 2017-02-13 06:24
I want to get archivedID in new coming msg (not case query) in client, all resource is same priority and "To" is bare JID, so mod_carbon is skipped. Now, just 1 resource receive msg with archived tag. May be I will set full-JID in "To" attribute in message delivered by sender for using mod_carbon.

**Comment by zinid** [comment] 2017-02-13 06:33
> all resource is same priority and "To" is bare JID, so mod_carbon is skipped
Why is it skipped? `ejabberd_sm` should find an available resource and append to `to` JID, so it will be forked by `mod_carboncopy` eventually, from what I understand.

**Comment by zinid** [comment] 2017-02-13 07:00
Also, isn't this something you want: #1480? (and the corresponding PR: #1499)

**Comment by bvhoang91** [comment] 2017-02-13 07:21
My problem in hook user_receive_packet.
This hook forked on all resource but just add achivedID for one (selected by is_bare_copy).
ejabberd_sm:get_user_presence_resources(U, S) return list online-resource (same priority), so MaxRes is first element in list (only this resource receive msg with archved tag).

**Comment by bvhoang91** [comment] 2017-02-13 07:46
> Why is it skipped? ejabberd_sm should find an available resource and append to to JID, so it will be forked by mod_carboncopy eventually, from what I  understand.

Yes, but TargetJIDs is empty

**Comment by zinid** [comment] 2017-02-13 08:36
OK, I'm lost

**Comment by weiss** [comment] 2017-05-12 13:21
This is a duplicate of #1344.

**Closed by weiss** 2017-05-12 13:21 UTC
