### ISSUE TITLE
Unable to Register SIP client with IPv6

### ISSUE THREAD

**Issue by Andy-2639** [processone/ejabberd#1668] opened 2017-04-09 09:51 UTC
> What version of ejabberd are you using?
> How did you install ejabberd (source, package, distribution)?

https://www.process-one.net/downloads/downloads-action.php?file=/ejabberd/17.03/ejabberd-17.03-windows-installer.exe

> What operating system (version) are you using?

Windows 10 Pro x64 Anniversary Update (Version 1607 Build 14393.969)

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

My SIP client (Phoner Lite 2.47, http://www.phonerlite.de/ ) can register to my ejabberd SIP server via IPv4 (TCP and UDP) without problems.
When I try to use IPv6, the register fails and PhonerLite says a timeout occurred. This happens with TCP and UDP.

SIP client and ejabberd are running on different maschines in the same LAN. No firewall is enabled on either maschine.

I attached the logs of the connections (ejabberd log, PhonerLite debug output and wireshark packet captures) zipped. Wireshark ran on the same maschine on which ejabberd runs.
[logs_pcaps.zip](https://github.com/processone/ejabberd/files/908101/logs_pcaps.zip)

SIP configuration in my ejabberd.yml:
```yaml
listen: 
  - 
    ip: "0.0.0.0"
    port: 65060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "0.0.0.0"
    port: 65060
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    module: ejabberd_sip
modules: 
  mod_sip: []
```

**Comment by zinid** [comment] 2017-05-05 10:02
Don't you have any errors in the log? It's not always possible to define the same port globally to both IP protocols. Do you see the ports are opened on all IP interfaces?

**Comment by Andy-2639** [comment] 2017-05-07 06:16
> Don't you have any errors in the log?

No, there are no errors in the log.
The ejabberd logs are in logs_pcaps.zip "ejabberd [tcp/udp] v[4/6].log". For every protocol combination, I deleted the old logs and started a fresh ejabberd instance.

> It's not always possible to define the same port globally to both IP protocols. Do you see the ports are opened on all IP interfaces?

I tested it again with port 5060 for IPv4 TCP/UDP and port 65060 for IPv6 TCP/UDP. This gives the same behavior. I also testes the bahavior of Phoner Lite 2.47: when the SIP server is not reacheable I get an connection error message instead of an timeout.
Also wireshark indicates that the ports are open: no TCP RST packets. In the ejabberd logs, I can see the REGISTER messages from Phoner Lite, too (ejabberd tcp v6.log, line 327; ejabbers udp v6.log, 326 - 509).
XMPP works fine with IPv4 and IPv6 on the same port number.

**Comment by zinid** [comment] 2017-05-07 06:51
> I tested it again with port 5060 for IPv4 TCP/UDP and port 65060 for IPv6 TCP/UDP.

Do you mean to say you disabled ipv4 listener and still don't have it working with ipv6 listener?

**Comment by Andy-2639** [comment] 2017-05-07 08:52
Neighter
```yaml
listen: 
  - 
    ip: "0.0.0.0"
    port: 5060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "0.0.0.0"
    port: 5060
    module: ejabberd_sip
  - 
    ip: "::"
    port: 65060
    module: ejabberd_sip
```

nor

```yaml
listen: 
  - 
    ip: "::"
    port: 5060
    transport: udp
    module: ejabberd_sip
  - 
    ip: "::"
    port: 5060
    module: ejabberd_sip
```

works on my system.

**Comment by Andy-2639** [comment] 2017-08-27 08:57
I tested SIP with IPv6 again with ejabberd 17.08. It still fails.
The logs of phonerlite and ejabberd and the complete ejabberd configuration is in the zip:
[logs_config.zip](https://github.com/processone/ejabberd/files/1254233/logs_config.zip)

SIP with IPv4 works fine. I enabled listening only on one IP version at a time.

It seems that ejabberd is receiving the requests vom the SIP client but just does not send a reply.

The test ran in a VM with a newly installed Windows 10 Pro x64 and a newly installed ejabberd 17.08. The windows firewall was deactivated and phonelite and ejabberd ran on the same VM.

**Comment by zinid** [comment] 2017-09-20 08:37
I'm not sure I can help because I don't have windows installed and IPv6 works fine for me on Linux.

**Comment by aylesm** [comment] 2017-11-10 14:33
Any progress with this?  I'm running centos and have enabled IPv6.  I can see from the logs the server receives the SIP REGISTER message.  But never responds.

**Comment by zinid** [comment] 2017-11-14 07:56
I still have it working:
```
$ telnet ::1 5060
Trying ::1...
Connected to ::1.
Escape character is '^]'.
REGISTER sip:zinid.ru SIP/2.0
Via: SIP/2.0/TCP 198.211.126.52:43403;branch=z9hG4bK.23e5441e;rport;alias
From: sip:xram@zinid.ru;tag=4cc1fd1f
To: sip:xram@zinid.ru
Call-ID: 1287781663@198.211.126.52
CSeq: 1 REGISTER
Content-Length: 0
Max-Forwards: 70
User-Agent: sipsak 0.9.7pre
Expires: 15
Contact: sip:xram@198.211.126.52:43403;transport=TCP

SIP/2.0 401 Unauthorized
Via: SIP/2.0/TCP 198.211.126.52:43403;branch=z9hG4bK.23e5441e;alias;received=[::1];rport=54724
From: <sip:xram@zinid.ru>;tag=4cc1fd1f
Call-ID: 1287781663@198.211.126.52
CSeq: 1 REGISTER
Max-Forwards: 70
To: <sip:xram@zinid.ru>;tag=2332915767-1429473788
Server: ejabberd 17.09.121
WWW-Authenticate: Digest realm="zinid.ru", qop="auth", nonce="8aa552d7fd797fec03f613ef91f856859d72ec97"
Content-Length: 0

```

**Comment by zinid** [comment] 2017-11-14 07:56
I have tried on two Linux machines, btw.

**Comment by aylesm** [comment] 2017-11-14 08:38
Have you tested over TLS?

**Comment by zinid** [comment] 2017-11-14 08:53
Yes, it works as well.

**Comment by zinid** [comment] 2017-11-14 09:11
Have you enabled debug (`loglevel: 5`)? What do you see there?

**Comment by aylesm** [comment] 2017-11-14 09:45
I see the incoming request in the logs.  But I don't see the response.  So it feels like this is an outbound issue in my setup.  Not sure if I've waited long enough to see a timeout or other relevant log msg.

**Comment by zinid** [comment] 2017-11-14 09:49
This is strange because you should see `data_out` log message within 32 seconds max.

**Comment by zinid** [comment] 2017-11-14 10:01
Also, what if you don't use TLS? Does plain TCP or UDP work with IPv6?

**Comment by aylesm** [comment] 2017-11-14 10:09
Same result with UDP.  Haven't tried TCP at this point.

**Comment by aylesm** [comment] 2017-11-15 09:38
@zinid do you have a sample ejabberd.yml I can take a look at to see if I've setup my instance correctly for IPv6?

**Comment by aylesm** [comment] 2017-11-15 09:40
I've also reproduced this same behaviour on MacOS.  Which by default has IPv6 switched on.  So the only thing I can think of is that my yml is wrong.  The only other thing I can think of is trying to setup the same type of linux box as you to see if that's the issue.

**Comment by zinid** [comment] 2017-11-15 09:43
> do you have a sample ejabberd.yml

Sure, here is the listening section
```yaml
listen:
  - 
    port: 3478
    module: ejabberd_stun
    transport: udp
    use_turn: true
    auth_type: user
    turn_ip: "198.211.126.52"
  - 
    port: 5060
    ip: "::"
    module: ejabberd_sip
    transport: udp
  - 
    port: 5060
    ip: "::"
    module: ejabberd_sip
  -
    port: 5061
    ip: "::"
    module: ejabberd_sip
    tls: true
    certfile: "/path/to/cert.pem"
```

And modules section:
```yaml
modules:
  mod_sip: {}
```

**Comment by sbourji** [comment] 2018-01-06 13:51
I 'm having the same issue, able to register from my iPhone to android using IPV4, but unable to register using IPV6 using baresip

**Comment by zinid** [comment] 2018-01-06 16:12
@sbourji This is not enough to just say "I don't have this working". This doesn't help us. You're better off intercepting the SIP traffic to see what happens.

**Comment by sbourji** [comment] 2018-01-06 22:38
Ok. What you need me to supply. The is nothing going thru the wire
 Wireshark show nothing. I can register with ipv4 and I do, but not with ipv6?



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by zinid** [comment] 2018-01-06 22:57
If there is nothing on the wire, how is it supposed to work? Packets don't arrive at server, of course nothing would work.

**Comment by sbourji** [comment] 2018-01-06 23:16
Don't get it? What are you saying.?
This not about ejabbered, the issue is about baresip and ipv6. Maybe I am in the wrong discussion group. If it's the case, then, my mistake.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by aylesm** [comment] 2018-01-06 23:16
The network traffic that I saw was from ejabberd 17.01. Traffic was received and there was no response. The logs did Not indicate an error condition. The request went into a black hole. The latest release seams to have fixed this issue for me.

**Comment by aylesm** [comment] 2018-01-06 23:37
I see packets arrive at ejabberd and they are logged. I don’t see a response on the client or even in the server logs. The latest ejabberd config example seems to be more IPv6 compatible. For me I just updated and incorporated the new config and it worked for me.

**Comment by zinid** [comment] 2018-01-07 08:06
OK, I close the issue then

**Closed** 2018-01-07 08:08 UTC

**Comment by Andy-2639** [comment] 2018-01-07 10:01
@aylesm

I don't really understand your answer.

> I see packets arrive at ejabberd and they are logged. I don’t see a response on the client or even in the server logs.

Is this the behavior before your configuration change?

What exactly did you change? I still cannot register using IPv6 - IPv4 works fine.
ejabberd 17.12 on Windows 10 x64 Fall Creators Update.

**Comment by aylesm** [comment] 2018-11-08 07:57
@zinid Your test is also incorrect.  You are testing an IPv4 client on an IPv6 connection.  The CONTACT and VIA headers should represent an IPv6 address.  Are you sure the server is parse these header fields correctly for IPv6?

**Comment by aylesm** [comment] 2018-11-09 16:53
@zinid any update on this?  Is there anything I can do to help?

**Comment by GrahamW** [comment] 2018-11-14 12:09
HI @zinid ... can you give us a pointer as to where in the code this is failing please? I might be able to submit a PR, but any help getting started would be great.

**Comment by aylesm** [comment] 2018-11-16 18:48
@zinid More info, I've managed to track down the issue.  You're not parsing IPv6 addresses at all it seems.

This function is wrong (esip_codec.hrl):
```
decode_uri_host(Data, URI) ->
    case split(Data, $;, 1) of
        [_] ->
            case split(Data, $?, 1) of
                [HostPort, Tail] ->
                    Headers = decode_param_hdrs(Tail),
                    Params = [];
                [HostPort] ->
                    Headers = Params = []
            end;
        [HostPort, Tail] ->
            case split(Tail, $?, 1) of
                [Ps, Hs] ->
                    Headers = decode_param_hdrs(Hs),
                    Params = decode_params(Ps);
                [Ps] ->
                    Headers = [],
                    Params = decode_params(Ps)
            end
    end,
    case split(HostPort, $:, 1) of
        [Host, Port] ->
            case to_integer(Port, 0, 65535) of
                {ok, PortInt} ->
                    URI#uri{host = to_lower(Host), port = PortInt,
                            params = Params, hdrs = Headers};
                _ ->
                    error
            end;
        [Host] ->
            URI#uri{host = to_lower(Host), params = Params, hdrs = Headers}
    end.
 ```
Results in values:
Host ==  `< Host = <<"[2a01">>`
Port == `< Port = <<"4c8:1c:51fe:bc0c:bff9:b11b:cfcf]:57363">>`

From input of:
HostPort == `< HostPort = <<"[2a01:4c8:1c:51fe:bc0c:bff9:b11b:cfcf]:57363">>`

**Comment by aylesm** [comment] 2018-12-19 16:58
@zinid Looks like there is an internal server error with a IPv6 -> IPv6 call.  My assumption is that the record for the remote peer is incorrectly formatted.  So when you come to lookup and route the request it fails causing a 500 internal server error.  

Any tips about where to look for this one?

**Comment by aylesm** [comment] 2019-05-03 06:45
Any movement on this?

**Comment by zinid** [comment] 2019-05-03 07:49
Yes, sorry for the delay, I'll fix it ASAP (by upcoming ejabberd 19.05).

**Comment by oksjd** [comment] 2019-08-31 09:40
Any updates? I also tried to connect to ejabberd SIP service over IPv6 using both a Windows computer and an android phone without success. With debug log level, the registering requests are received by the server but are also never answered. Using Debian buster official native package (18.12.1).

**Comment by oksjd** [comment] 2019-08-31 10:21
Still no luck with 19.08 release. With android native client the registering process times out as ever before.
[log.txt](https://github.com/processone/ejabberd/files/3562326/log.txt)

**Comment by licaon-kter** [comment] 2019-08-31 10:30
@oksjd whah client is this? Tried Baresip or Linphone yet?

**Comment by oksjd** [comment] 2019-08-31 10:51
@licaon-kter That's android bulit-in SIP, in the native phone app.
Just tried Linphone from F-Droid, stuck at "connection in progress"
[linphone.txt](https://github.com/processone/ejabberd/files/3562344/linphone.txt)
Baresip has no log on server at all.

**Comment by licaon-kter** [comment] 2019-08-31 11:09
@oksjd this is my config that works ok on IPv4, maybe it helps: https://gist.github.com/edbc6629722fa1651d47924e15472bf0

**Comment by oksjd** [comment] 2019-08-31 11:14
@licaon-kter Thanks for your config, however without explicitly specifying the listening port as :: for sip module as your config, the module won't even listen on ipv6. I can only test ipv6 since this ejabberd instance is set up at home, where the fibre optics has carrier grade NAT. The xmpp domain has only one AAAA record and several SRV and TLSA records.

**Comment by licaon-kter** [comment] 2019-08-31 11:42
@oksjd Add `::` as needed, right.

**Comment by aylesm** [comment] 2019-09-01 16:21
There is a bug in ejabberd. The SIP module fails to parse IPv6 addresses properly. I’ve forked the sip module and patched this. Still waiting for processOne to merge.

**Comment by mremond** [comment] 2019-09-02 10:49
@aylesm Which PR is it ?

**Comment by aylesm** [comment] 2019-09-02 12:07
@mremond https://github.com/processone/esip/pull/8

**Comment by mremond** [comment] 2019-09-06 12:46
From what I understand the PR cannot be applied as is as it is said to not be working for all cases and should probably have tests.
We had not time yet to work on it to make a proper fix.

**Comment by Neustradamus** [comment] 2020-01-27 13:14
At this date (20-01-27), any news about this problem?
Several ISP now give only IPv6 address...

**Comment by Neustradamus** [comment] 2020-04-19 12:29
Linked to:
- https://github.com/processone/stun/issues/25
- https://github.com/processone/ejabberd/issues/2917
- https://github.com/processone/ejabberd/issues/3229
- https://github.com/processone/esip/pull/8

**Comment by aylesm** [comment] 2020-04-19 14:37
The PR I submitted for this removed the poor logic to use the first “:” as the delimiter to split out the port number from the address. There were no tests for this module in place when I submitted. I am no erlang developer and didn’t have the time to figure it out. Not sure why this hasn’t been worked on as it’s clearly very wrong. I guess limited people are using the sip module so it’s not being prioritised. However as many said it’s becoming an increasing important issue as many ISPs are no longer supporting IPv4. Also Apple will reject apps that don’t support ipv6.

**Comment by badlop** [comment] 2022-06-06 20:59
I reworked your initial esip PR, added support for `[ ]` and some tests, see https://github.com/processone/esip/pull/14

If you or anybody else can try it, or is interested in testing the patch in real circumstances, please ask any doubt or report any problem... or success.

**Comment by Neustradamus** [comment] 2022-07-23 22:48
@ all: Have you tested the @badlop improvements?

**Comment by kuon** [comment] 2023-10-27 22:42
I just started using ejabberd and hit this issue as our network is IPv6 only.

Is there anything else to be done to be able to fix this?

**Comment by Neustradamus** [comment] 2025-02-13 04:23
@kuon (or others): What is the situation in 2025?

**Comment by kuon** [comment] 2025-02-13 08:51
As far as I know (through the issue I am monitoring) it is still not working, but I have not tried recently.
