### ISSUE TITLE
API send_message internal error

### ISSUE THREAD

**Issue by pierreavn** [processone/ejabberd#3581] opened 2021-04-19 16:25 UTC
## Environment

- ejabberd version: 21.1.0
- Erlang version: 10.5
- OS: Linux (Ubuntu)
- Installed from: docker ejabberd/ecs

## Errors from error.log/crash.log

```
2021-04-19 15:17:26.752692+00:00 [error] <0.1384.0>@mod_http_api:handle/4:258 REST API Error: send_message([{<<"type">>,<<"normal">>},
                              {<<"from">>,<<"user1@localhost">>},
                              {<<"to">>,
                               <<"user2@localhost">>},
                              {<<"subject">>,<<"Hello">>},
                              {<<"body">>,<<"world">>}]) -> error:{try_clause,
                                                                   {message,
                                                                    <<"4977454225270036420">>,
                                                                    normal,
                                                                    <<>>,
                                                                    {jid,
                                                                     <<"user1">>,
                                                                     <<"localhost">>,
                                                                     <<>>,
                                                                     <<"user1">>,
                                                                     <<"localhost">>,
                                                                     <<>>},
                                                                    {jid,
                                                                     <<"user2">>,
                                                                     <<"localhost">>,
                                                                     <<>>,
                                                                     <<"user2">>,
                                                                     <<"localhost">>,
                                                                     <<>>},
                                                                    [{text,
                                                                      <<>>,
                                                                      <<"Hello">>}],
                                                                    [{text,
                                                                      <<>>,
                                                                      <<"world">>}],
                                                                    undefined,
                                                                    [],#{}}} [{mod_admin_extra,
                                                                               send_message,
                                                                               5,
                                                                               [{file,
                                                                                 "src/mod_admin_extra.erl"},
                                                                                {line,
                                                                                 1485}]},
                                                                              {mod_http_api,
                                                                               handle2,
                                                                               4,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 268}]},
                                                                              {mod_http_api,
                                                                               handle,
                                                                               4,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 229}]},
                                                                              {mod_http_api,
                                                                               perform_call,
                                                                               4,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 189}]},
                                                                              {mod_http_api,
                                                                               process,
                                                                               2,
                                                                               [{file,
                                                                                 "src/mod_http_api.erl"},
                                                                                {line,
                                                                                 142}]},
                                                                              {ejabberd_http,
                                                                               process,
                                                                               2,
                                                                               [{file,
                                                                                 "src/ejabberd_http.erl"},
                                                                                {line,
                                                                                 373}]},
                                                                              {ejabberd_http,
                                                                               process_request,
                                                                               1,
                                                                               [{file,
                                                                                 "src/ejabberd_http.erl"},
                                                                                {line,
                                                                                 496}]},
                                                                              {ejabberd_http,
                                                                               process_header,
                                                                               2,
                                                                               [{file,
                                                                                 "src/ejabberd_http.erl"},
                                                                                {line,
                                                                                 293}]}]
```

## Bug description

I'm trying to send message from `user1@localhost` to `user2@localhost` through REST API, but I have a 500 "internal_error" response (all other API endpoints are working well and as expected). Above error message found in `error.log` (the same is in `ejabberd.log`).  
  
Below the exact request:

```
curl --location --request POST 'http://localhost:5280/api/send_message' \
--header 'X-Admin: true' \
--header 'Authorization: Bearer ...token...' \
--header 'Content-Type: application/json' \
--data-raw '{
    "type": "normal",
    "from": "user1@localhost",
    "to": "user2@localhost",
    "subject": "Hello",
    "body": "world"
}'
```
  
This is failing with all message types (normal, chat, ...), and `user1@localhost` & `user2@localhost` are registered.

Thank you for your help!

**Comment by badlop** [comment] 2021-04-20 08:37
Duplicate of https://github.com/processone/ejabberd/issues/3485 and https://github.com/processone/ejabberd/issues/3555 .

It's a bug introduced in ejabberd 21.01. It was fixed in b3d9c0d, and the fix was included in ejabberd 21.04. You can use a previous ejabberd version, update to 21.04, or apply that small patch yourself.

**Closed** 2021-04-20 08:38 UTC
