### ISSUE TITLE
Ejabberd Crash with no logs

### ISSUE THREAD

**Issue by mkl262** [processone/ejabberd#3104] opened 2019-12-02 15:46 UTC
## Environment

- ejabberd version: 19.02
- Erlang version: Erlang (SMP,ASYNC_THREADS,HIPE) (BEAM) emulator version 10.1
- OS: Linux Debian Stretch
- Installed from: official binary installer

## Errors from error.log/crash.log

No errors

## Bug description

Ejabberd services crashes and stops writing any logs, but outputs a dump file.
[erl_crash_20191116-090132.dump.tar.gz](https://github.com/processone/ejabberd/files/3912006/erl_crash_20191116-090132.dump.tar.gz)

**Comment by zinid** [comment] 2019-12-02 15:52
Your ejabberd ran out of atoms due to #2977.

**Comment by zinid** [comment] 2019-12-02 15:52
Duplicate of #2977

**Closed by zinid** 2019-12-02 15:52 UTC
