### ISSUE TITLE
can't set acl database to on RAM&disk or disk , 16.01

### ISSUE THREAD

**Issue by slesru** [processone/ejabberd#1206] opened 2016-07-22 04:39 UTC
> What version of ejabberd are you using?

16.01

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

from distribution

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Just installed fresh ubuntu 16.04 and ejabberd 16.01 from it.

I configured (yml) ldap authentication and declared myself as admin:
```
acl:
  ##
  ## The 'admin' ACL grants administrative privileges to XMPP accounts.
  ## You can put here as many accounts as you want.
  ##
  admin:
     user:
         - "dm": "jabber.mydomain"
```

Then started ejabberd and login through web interface.

I see that in host config  acl database is in RAM (I'm back translating from russian).

If I set it to RAM & disk then acl database file appears, but if I restart ejabberd it removes file and
I see RAM in database config via web interface.

If I set only disk, then ejabberd dies with errors:

```
2016-07-21 13:02:43 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.920.0>
    registered_name: []
    exception error: bad argument: 
[{ets,lookup,[acl,{admin,global}],[]},
{acl,get_aclspecs,2,[{file,"src/acl.erl"},{line,349}]},
{acl,match_acl,3,[{file,"src/acl.erl"},{line,346}]},
{acl,match_acls,3,[{file,"src/acl.erl"},{line,276}]},
{ejabberd_web_admin,'-is_acl_match/3-fun-0-',3,[{file,"src/ejabberd_web_admin.erl"},{line,88}]},
{lists,any,2,[{file,"lists.erl"},{line,1224}]},
{ejabberd_web_admin,'-make_server_menu/4-lc$^0/1-0-',3,[{file,"src/ejabberd_web_admin.erl"},{line,2890}]},
{ejabberd_web_admin,make_server_menu,4,[{file,"src/ejabberd_web_admin.erl"},{line,2888}]}]
    ancestors: [<0.472.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.8866>,#Port<0.8865>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 28690
    stack_size: 27
    reductions: 53249
  neighbours:
2016-07-21 13:02:43 =CRASH REPORT====
  crasher:
    initial call: ejabberd_http:init/2
    pid: <0.1344.0>
    registered_name: []
    exception error: bad argument: [{ets,lookup,[acl,{admin,global}],[]},
{acl,get_aclspecs,2,[{file,"src/acl.erl"},{line,349}]},
{acl,match_acl,3,[{file,"src/acl.erl"},{line,346}]},
{acl,match_acls,3,[{file,"src/acl.erl"},{line,276}]},
{ejabberd_web_admin,'-is_acl_match/3-fun-0-',3,[{file,"src/ejabberd_web_admin.erl"},{line,88}]},
{lists,any,2,[{file,"lists.erl"},{line,1224}]},
{ejabberd_web_admin,get_auth_account,5,[{file,"src/ejabberd_web_admin.erl"},{line,269}]},
{ejabberd_web_admin,process,2,[{file,"src/ejabberd_web_admin.erl"},{line,222}]}]
    ancestors: [<0.472.0>,ejabberd_listeners,ejabberd_sup,<0.38.0>]
    messages: []
    links: [#Port<0.8879>,#Port<0.8880>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 3836
  neighbours:
```

And
```
2016-07-21 13:02:43.963 [error] <0.1344.0> CRASH REPORT Process <0.1344.0>
 with 0 neighbours crashed with reason:
 bad argument in call to ets:lookup(acl, {admin,global})
 in acl:get_aclspecs/2 line 349
```

btw, I have ejabberd 2 on ubuntu 12.04 and it runs just fine with almost the same config.

**Comment by badlop** [comment] 2016-07-22 11:42
Right, the Mnesia ACL table must be stored in RAM. In fact there's source code to ensure that, see https://github.com/processone/ejabberd/blob/master/src/acl.erl#L77
So, whatever you planned to do with acl.DAT, you will have to find another way to do it.

**Comment by slesru** [comment] 2016-07-22 12:09
oops, so _only_ way to store acls are in config file now.
right?
any suggestions how to change them dynamically, but have them stored?

thank you!

**Comment by badlop** [comment] 2016-07-22 13:40
ACL and Access are read from the config file at server start.
They can be changed at runtime using webadmin or a Jabber client, but those changes will be lost and overwritten by the config file in the next server start.

Alternatively, you can make the changes in the config file, and run this command which reads and loads it in runtime:
```
$ ejabberdctl help reload_config                                                                        
  Command Name: reload_config                                                                           
  Arguments:                                                                                            
  Returns: res::rescode                                                                                 
  Tags:  server                                                                                         
  Description:  Reload config file in memory (only affects ACL and Access)   
```

**Comment by cromain** [comment] 2016-07-22 14:54
badlop explain how it works. i think we can close this now.

**Comment by slesru** [comment] 2016-07-22 15:55
I guess that close was too early- I'd like to know is web interface fixed to remove acl database disk option it latest version? if not, it is better to fix this, because this is misleading and may results in ejabberd crash.
Thank you!

**Comment by badlop** [comment] 2016-07-25 10:59
ACL will not support that. And the Webadmin provides a way to configure tables for ejabberd internal code and any other added modules. So, there is no way to guarantee that all the possibilities offered in that page are "safe", as new modules may be added from other sources, or their combination, or their usage in your particular installation may be different. In summary, you should know what you are doing when you make such a change. To prevent such problems, the only good solution is to delete that Webadmin page.

On the other hand, I can add code to hide some storage options for some tables, for example hide "disc only" in "acl" table. If you try all the tables created in the standard ejabberd and tell me which storage types are problematic for which tables, I'll add code to hide them.

**Comment by slesru** [comment] 2016-07-26 05:17
I guess the best way is to have some table attribute, which describes it's storage options, so it can be correctly displayed and managed via web.

**Comment by mremond** [comment] 2016-07-26 06:50
I think this function is advanced. Describing all the implications for each storage change is not the role of the webadmin. Easy change of table was intended for developers, so I am not sure turning this into a Mnesia / Erlang tutorial is a good idea.

**Comment by slesru** [comment] 2016-07-26 07:46
no, I mean that web interface should be built accroding to database desciptions, if acls can't be stored on disk ( really, don't know why , because it's way I used for years) then there should be no option set it to disk in web admin, because in this case ejabberd hangs, i.e. web admin should not allow admin to kill application by mistake.

**Comment by mremond** [comment] 2016-07-26 07:49
Well, what I mean is that normal users should not at all be able to change any Mnesia table. If you do so, you can break the behaviour of ejabberd. I tend to think then we should just make this page read-only.

**Comment by slesru** [comment] 2016-07-26 08:01
I guess that normal users have no access their, only ejabberd administrators have access.
Read-only... well, you can just remove it- result is the same.

**Comment by mremond** [comment] 2016-07-26 08:04
No, read-only has a different effect. You can still read the settings. However, the default set by ejabberd are ok, and there should not be a need to change them.

**Comment by slesru** [comment] 2016-07-26 08:11
but why I need to read them if they are good and there is no need to change them?

**Comment by mremond** [comment] 2016-07-26 08:18
You may need to read them to be able to help reporting possible issues.

**Comment by slesru** [comment] 2016-07-27 07:44
why?  I can't change them => they are always known :-)

**Comment by mremond** [comment] 2016-07-27 07:53
You can always change them by typing command. You can even install a plugin that may change them without you knowing it.

**Comment by slesru** [comment] 2016-07-27 10:03
OK, problem is not in web interface then, if acls can be only stored in RAM, then ejabberd should prevent change this on all levels, IMHO.

**Comment by mremond** [comment] 2016-07-27 10:11
@slesru you cannot. There is no way to prevent a user to type Erlang code in the VM or an installed module to run any Erlang code.

**Comment by slesru** [comment] 2016-07-27 10:38
well, then at least this crash- when I set acl database to be stored only on disk and  ejabberd crashes,- should be fixed. I guess this will prevent ejabberd from crash if this changed by any other method and will allow to revert change via web interface.

and, I guess, it is good idea to have friendly web interface, i.e. disable options which can't be used.

**Comment by slesru** [comment] 2016-07-28 04:13
I mean, if ejabberd detects database configuration it can't use, why not try to change it?

**Closed** 2016-09-19 09:57 UTC
Labels: Component:Admin Tools
