### ISSUE TITLE
ejabberd 17.07 Hook c2s_copy_session crashed when running mod_privacy:c2s_copy_session

### ISSUE THREAD

**Issue by moJ090** [processone/ejabberd#1892] opened 2017-07-28 09:33 UTC
> What version of ejabberd are you using?

17.07

> What operating system (version) are you using?

Centos 7.3

> How did you install ejabberd (source, package, distribution)?

rpm 

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I dont know why Iam getting this errors. Can you help me?

```
[error] <0.584.0>@ejabberd_hooks:safe_apply:383 Hook c2s_copy_session crashed when running mod_privacy:c2s_copy_session/2:
** Reason = {error,function_clause,[{mod_privacy,c2s_copy_session,[{file,"src/mod_privacy.erl"},{line,414}],[#{mod => ejabberd_c2s,conn => c2s_tls,mgmt_resend => false,socket_monitor => #Ref<0.0.1.4862>,stream_encrypted => true,stream_id => <<"11826324493439784451">>,lserver => <<"example.com">>,mgmt_queue_type => ram,socket => {socket_state,fast_tls,{tlssock,#Port<0.21076>,<<>>},<0.583.0>},auth_module => ejabberd_auth_mnesia,mgmt_stanzas_in => 0,tls_options => [compression_none,{ciphers,<<"ECDH:DH:!3DES:!aNULL:!eNULL:!MEDIUM@STRENGTH">>},{dhfile,<<"/opt/ejabberd-17.07/conf/dhparams.pem">>},{protocol_options,<<"no_sslv3|no_tlsv1|cipher_server_preference|no_compression">>},{certfile,<<"/opt/ejabberd-17.07/conf/server.pem">>}],mgmt_ack_timeout => 60000,mgmt_max_timeout => 300,tls_verify => false,sid => {{1501,230170,1},<0.584.0>},jid => {jid,<<"exampleuser">>,<<"example.com">>,<<"mobile">>,<<"exampleuser">>,<<"example.com">>,<<"mobile">>},stream_authenticated => true,user => <<"exampleuser">>,stream_timeout => {30000,-576459210313},mgmt_max_queue => 1000,lang => <<"en">>,csi_state => active,ip => {{0,0,0,0,0,65535,21105,25424},38523},tls_enabled => true,pres_a => {1,{{<<"f7kfd38icpt">>,<<"conference.example.com">>,<<"exampleuser">>},nil,nil}},pres_timestamp => {1501,231414,873343},stream_compressed => false,csi_queue => {4,#{{{<<"exampleuser">>,<<"example.com">>,<<"mobile">>},presence} => {{4,{1501,231414,873664}},{presence,<<>>,available,<<"en">>,{jid,<<"exampleuser">>,<<"example.com">>,<<"mobile">>,<<"exampleuser">>,<<"example.com">>,<<"mobile">>},{jid,<<"exampleuser">>,<<"example.com">>,<<"mobile">>,<<"exampleuser">>,<<"example.com">>,<<"mobile">>},undefined,[],undefined,[{xmlel,<<"c">>,[{<<"xmlns">>,<<"http://jabber.org/protocol/caps">>},{<<"ver">>,<<"IEVmk80YcxrC26oK20fBKhyGaZA=">>},{<<"node">>,<<"http://conversations.im">>},{<<"hash">>,<<"sha-1">>}],[]},{xmlel,<<"idle">>,[{<<"xmlns">>,<<"urn:xmpp:idle:1">>},{<<"since">>,<<"2017-07-28T08:42:14.439Z">>}],[]}],#{ip => {0,0,0,0,0,65535,22400,...}}}}}},...},...]},...]}
```

**Comment by zinid** [comment] 2017-07-28 09:55
Duplicate of #1842

**Closed by zinid** 2017-07-28 09:55 UTC
