### ISSUE TITLE
ejabberd-15.06 configuration checking errors!

### ISSUE THREAD

**Issue by langzi88** [processone/ejabberd#631] opened 2015-07-01 07:46 UTC
when I download ejabberd_15.06-0_amd64.deb or ejabberd-15.06-linux-x86_64-installer.run packet and install ejabberd.Then run ejabberdctl live to run ejabberd server.I find some configuration checking errors:
(ejabberd@localhost)1> 09:59:53.662 [info] Application lager started on node ejabberd@localhost
09:59:53.672 [info] Application crypto started on node ejabberd@localhost
09:59:53.688 [info] Application sasl started on node ejabberd@localhost
09:59:53.706 [info] Application asn1 started on node ejabberd@localhost
09:59:53.707 [info] Application public_key started on node ejabberd@localhost
09:59:53.718 [info] Application ssl started on node ejabberd@localhost
09:59:53.726 [info] Application p1_yaml started on node ejabberd@localhost
09:59:53.743 [info] Application p1_tls started on node ejabberd@localhost
09:59:53.754 [info] Application p1_xml started on node ejabberd@localhost
09:59:53.761 [info] Application p1_stringprep started on node ejabberd@localhost
09:59:53.768 [info] Application p1_zlib started on node ejabberd@localhost
09:59:53.772 [info] Application p1_cache_tab started on node ejabberd@localhost
09:59:53.990 [info] Application mnesia started on node ejabberd@localhost
09:59:55.578 [error] unknown option 'shaper' will be likely ignored
09:59:55.578 [error] unknown option 'modules' will be likely ignored
09:59:55.578 [error] unknown option 'max_fsm_queue' will be likely ignored
09:59:55.578 [error] unknown option 'loglevel' will be likely ignored
09:59:55.578 [error] unknown option 'log_rotate_size' will be likely ignored
09:59:55.578 [error] unknown option 'log_rotate_date' will be likely ignored
09:59:55.578 [error] unknown option 'log_rotate_count' will be likely ignored
09:59:55.579 [error] unknown option 'log_rate_limit' will be likely ignored
09:59:55.579 [error] unknown option 'listen' will be likely ignored
09:59:55.579 [error] unknown option 'auth_method' will be likely ignored
09:59:55.579 [error] unknown option 'allow_contrib_modules' will be likely ignored
09:59:55.579 [error] unknown option 'acl' will be likely ignored
09:59:55.579 [error] unknown option 'access' will be likely ignored
09:59:55.648 [info] FQDN used to check DIGEST-MD5 SASL authentication: ubuntu
09:59:55.700 [info] Application inets started on node ejabberd@localhost
09:59:55.751 [info] Reusing listening port for 5222
09:59:55.752 [info] Reusing listening port for 5269
09:59:55.753 [info] Reusing listening port for 5280
09:59:55.753 [info] ejabberd 15.06 is started in the node ejabberd@localhost
09:59:55.754 [info] Application ejabberd started on node ejabberd@localhost

I have not changed the configuration file ejabberd.yml.

**Comment by cromain** [comment] 2015-07-01 08:52
This is a duplicate of #616 
This is an harmless issue, with binary installer packaging. It will be fixed in 15.07.
However, please note that the errors are harmless. It means you can ignore the errors and your software will run without issues.

**Closed by cromain** 2015-07-01 08:52 UTC
