### ISSUE TITLE
Problem installing ejabberd on Linux

### ISSUE THREAD

**Issue by Bahaatya** [processone/ejabberd#2973] opened 2019-08-02 16:15 UTC
Hi,
First, thanks for this great software (as I read about and didn't try it yet).
Second, in order to try it, I logged into myserver's WHM _Terminal_ as a **root** user, 
then I made the following commands:

`wget https://www.process-one.net/downloads/ejabberd/19.05/ejabberd-19.05-linux-x64.run`
then followed the instructions mentioned here: https://docs.ejabberd.im/admin/installation/#install-on-linux
as the following:
```
chmod +x ejabberd-19.05-linux-x64.run
./ejabberd-19.05-linux-x64.run
```

and went into the installation process... till it completed, then I made the following commands:
```
cd /opt/ejabberd-19.05
./bin/ejabberdctl live
```

and here comes the problem that 3 days now I can't solve, I get this error in the terminal:

`--------------------------------------------------------------------

IMPORTANT: ejabberd is going to start in LIVE (interactive) mode.
All log messages will be shown in the command shell.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.

To exit this LIVE mode and stop ejabberd, press:
  q().  and press the Enter key

`--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press return to continue

Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V10.3.4  (abort with ^G)
(ejabberd@localhost)1> 17:21:41.774 [notice] Changed loghwm of /opt/ejabberd/logs/error.log to 100
17:21:41.774 [notice] Changed loghwm of /opt/ejabberd/logs/ejabberd.log to 100
17:21:41.851 [info] Loading configuration from /opt/ejabberd/conf/ejabberd.yml
17:21:42.456 [error] Failed to open socket at [::]:1883 for mod_mqtt: address family not supported by protocol family
17:21:42.456 [error] Supervisor ejabberd_listener had child {1883,{0,0,0,0,0,0,0,0},tcp} started with ejabberd_listener:start({1883,{0,0,0,0,0,0,0,0},tcp}, mod_mqtt, [{ip,{0,0,0,0,0,0,0,0}},{backlog,1000}]) at undefined exit with reason eafnosupport in context start_error
17:21:42.456 [error] Supervisor ejabberd_sup had child ejabberd_listener started with ejabberd_listener:start_link() atundefined exit with reason {shutdown,{failed_to_start_child,{1883,{0,0,0,0,0,0,0,0},tcp},eafnosupport}} in context start_error
17:21:42.460 [critical] Failed to start ejabberd application: {error,{shutdown,{failed_to_start_child,ejabberd_listener,{shutdown,{failed_to_start_child,{1883,{0,0,0,0,0,0,0,0},tcp},eafnosupport}}}}}`

I searched a lot during the 3 days on the internet for anything related to this error, but in vain...
I also searched on ejabberd.im community, but also in vain... seems like my problem is unique?

I tried restarting the server, hoping the ejabberd would automatically start, but in vain...
then tried a lot removing ejabberd then reinstalling it from scratch, with different domain, admin and username, but still without any new!

My server hosts 3 domains, and I tried each of them during the installation process, as well as localhost and several times I left the auto-detected server name the ejabberd got during the installation.

---------
_All the process is done on a dedicated server that runs on Linux, CENTOS 6.10 virtuozzo, WHM 82.0.6_

- **Total processors:** 4
Each Processor is: 
    Vendor: GenuineIntel
    Name: **Intel(R) Xeon(R) CPU E3-1220 v3 @ 3.10GHz**
    Speed: 3101.000 MHz
    Cache: 8192 KB

- **Memory:** 16GB RAM
- **Hard-Disk:** 2TB

-------
**Here you are the log files produced by ejabberd itself:**

[ejabberd.log](https://github.com/processone/ejabberd/files/3462073/ejabberd.log)
[error.log](https://github.com/processone/ejabberd/files/3462075/error.log)
[crash.log](https://github.com/processone/ejabberd/files/3462076/crash.log)

Thanks in advance.

**Comment by licaon-kter** [comment] 2019-08-02 16:32
Gist of your config?

**Comment by Bahaatya** [comment] 2019-08-02 16:39
hi licaon-kter

> Gist of your config?

I don't know the location of that file, and how to open/modify it in the terminal, I kept reading the the guide, especially that link: https://docs.ejabberd.im/admin/configuration/
and it's not clear where should the conf file be located, so I hoped there will be a default configuration file installed with ejabberd that will match the most cases, especially after I read this line in the above link:

> Do not let this complexity scare you. Most of you will be fine with default config file (or light changes).

**Comment by licaon-kter** [comment] 2019-08-02 17:24
I don't know how the installer works, maybe you've setup your hosts with it(!?), anyway `locate ejabberd.yml`


But, this sounds more like a network setup issue, eg. Your stack says you have IPv6 but you don't or the other way around.

Edit that config to only your real network, be in 4 or 6.

**Comment by Bahaatya** [comment] 2019-08-02 17:39
Hi licaon-kter,

> But, this sounds more like a network setup issue, eg. Your stack says you have IPv6 but you don't or the other way around.

I were doubting this point, but as I told you I don't know where's that file is, neither the official website mentions it.
Anyway I would try to look for that file, but you know working from the Terminal is not that easy, you have to browse each folder with command...

if I'm lucky to find that file, I will modify it, an come back with the result...

thanks for your tries and care!

Regards;

**Comment by zinid** [comment] 2019-08-02 20:12
I close the issue: this is not a bug: ejabberd clearly says the problem is that OS doesn't support IPv6 stack.

**Closed by zinid** 2019-08-02 20:12 UTC

**Comment by Bahaatya** [comment] 2019-08-02 21:34
> I close the issue: this is not a bug: ejabberd clearly says the problem is that OS doesn't support IPv6 stack.

Hi zinid, at least tell us what to do in order to change this setting to IPv4, what commands, where to find ejabberd conf file, the easiest thing is to close the issue and avoid the "bug" title, I understand your concern, but nobody decided it's certainly a bug, I posted the issue here to either find a solution to me and maybe some other people or at least to fix the bug in the "ejabber.im" guide that's totally not clear.

thanks anyway.
Regards;

**Comment by Bahaatya** [comment] 2019-08-02 21:52
I finally found the cinfiguration files, please anybody may look at it, and tell me what needs to be changed?

[ejabberd.txt](https://github.com/processone/ejabberd/files/3462995/ejabberd.txt)
[ejabberdctl.txt](https://github.com/processone/ejabberd/files/3462996/ejabberdctl.txt)


P.N. I have no options but to change the extensions of the files here to be .txt because github doesn't accept yml not conf files.

Thanks in advance

**Comment by licaon-kter** [comment] 2019-08-03 06:25
@Bahaatya https://docs.ejabberd.im/admin/configuration/#port-number-ip-address-and-transport-protocol

**Comment by Bahaatya** [comment] 2019-08-03 08:35
Good morning @licaon-kter
Thanks for your efforts, according to the link you mentioned, I changed the ejabberd.yml file to be like this:
[ejabberd.txt](https://github.com/processone/ejabberd/files/3463528/ejabberd.txt)

but when I run the commands:
`cd /opt/ejabberd-19.05
./bin/ejabberdctl live`

I still get that error in the Terminal:

`--------------------------------------------------------------------

IMPORTANT: ejabberd is going to start in LIVE (interactive) mode.
All log messages will be shown in the command shell.
You can interact with the ejabberd node if you know how to use it.
Please be extremely cautious with your actions,
and exit immediately if you are not completely sure.

To exit this LIVE mode and stop ejabberd, press:
  q().  and press the Enter key

--------------------------------------------------------------------
To bypass permanently this warning, add to ejabberdctl.cfg the line:
  EJABBERD_BYPASS_WARNINGS=true
Press return to continue


Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V10.3.4  (abort with ^G)
(ejabberd@localhost)1> 10:25:14.998 [notice] Changed loghwm of /opt/ejabberd/logs/error.log to 100
10:25:14.998 [notice] Changed loghwm of /opt/ejabberd/logs/ejabberd.log to 100
10:25:15.075 [info] Loading configuration from /opt/ejabberd/conf/ejabberd.yml
10:25:15.669 [error] Failed to open socket at [::]:1883 for mod_mqtt: address family not supported by protocol family
10:25:15.669 [error] Supervisor ejabberd_listener had child {1883,{0,0,0,0,0,0,0,0},tcp} started with ejabberd_listener:start({1883,{0,0,0,0,0,0,0,0},tcp}, mod_mqtt, [{ip,{0,0,0,0,0,0,0,0}},{backlog,1000}]) at undefined exit with reason eafnosupport in context start_error
10:25:15.669 [error] Supervisor ejabberd_sup had child ejabberd_listener started with ejabberd_listener:start_link() atundefined exit with reason {shutdown,{failed_to_start_child,{1883,{0,0,0,0,0,0,0,0},tcp},eafnosupport}} in context start_error
10:25:15.673 [critical] Failed to start ejabberd application: {error,{shutdown,{failed_to_start_child,ejabberd_listener,{shutdown,{failed_to_start_child,{1883,{0,0,0,0,0,0,0,0},tcp},eafnosupport}}}}}`

**_Here you're the log files:_**

[crash.log](https://github.com/processone/ejabberd/files/3463531/crash.log)
[ejabberd.log](https://github.com/processone/ejabberd/files/3463532/ejabberd.log)
[error.log](https://github.com/processone/ejabberd/files/3463533/error.log)


the strange thing that the logs still mention [::]:1883 after the modifications I've made in ejabberd.yml conf file.

Any idea?

thanks in advance;
Regards;

**Comment by licaon-kter** [comment] 2019-08-03 08:41
Do join xmpp:ejabberd@conference.process-one.net?join maybe someone can help you troubleshoot.

**Comment by Bahaatya** [comment] 2019-08-03 08:58
Thanks @licaon-kter 

> Do join xmpp:[ejabberd@conference.process-one.net](mailto:ejabberd@conference.process-one.net)?join maybe someone can help you troubleshoot.

is it an email address I should send my issue to?
