### ISSUE TITLE
Extauth caching not working correct

### ISSUE THREAD

**Issue by 4ichpich** [processone/ejabberd#2349] opened 2018-03-28 13:46 UTC
> What version of ejabberd are you using?
18.01-3

> What operating system (version) are you using?
docker

> What did not work as expected? Are there error messages in the log? What

I'm using ext auth to check my OAuth2 token against our OryHydra.
I use the username as a check and the token as password
It seems like Ejabbed is caching the successful user:password and doesn't calls the auth module for the Token.

the config is

      - XMPP_DOMAIN=host.org
      - EJABBERD_ADMINS=admin@host.org
      - EJABBERD_STARTTLS=false
      - EJABBERD_S2S_SSL=false
      - EJABBERD_HTTPS=false
      - EJABBERD_LOGLEVEL=4
      - EJABBERD_CONFIGURE_ODBC=true
      - EJABBERD_ODBC_TYPE=mysql
      - EJABBERD_ODBC_SERVER=mysqld
      - EJABBERD_ODBC_DATABASE=ejabberd
      - EJABBERD_ODBC_USERNAME=root
      - EJABBERD_ODBC_PASSWORD=secret
      - EJABBERD_AUTH_METHOD=external
      - EJABBERD_EXTAUTH_PROGRAM=/opt/ejabberd/scripts/auth/ejabberd-hydra -debug
      - EJABBERD_MOD_ADMIN_EXTRA=true
      - EJABBERD_EXTAUTH_INSTANCES=4
      - EJABBERD_EXTAUTH_CACHE=false

**Comment by zinid** [comment] 2018-03-28 14:01
Looks like a duplicate of #2322

**Comment by 4ichpich** [comment] 2018-03-29 07:00
Ok, with "auth_use_cache: false" it works, BUT there is no env variable in docker to set auth_use_cache, only extauth_cache

**Comment by karbovskibg** [comment] 2018-04-07 14:08
4ichpich ejabberd will delete it: https://github.com/processone/ejabberd/issues/2370

Please don;t update to ejaberd 18.03.1 it will automatically convert your plain database to scram and you will lose sip and stun or turn. There is manual in the upper website that i put but they comment it will reset all database. 4ichpich share what i write ejabberd INDIRECT INSULT peoples.

**Closed** 2018-04-10 08:57 UTC
