### ISSUE TITLE
Errors in links in web admin

### ISSUE THREAD

**Issue by f055** [processone/ejabberd#3212] opened 2020-04-08 09:47 UTC
## Environment

- ejabberd version: 20.03
- OS: Linux (Debian 10)
- Installed from: official deb
## Bug description

Links in the main content area under `/admin/server/[hostname]/` have errors:

- left side menu links contain double slashes //
  ```
  https://example.net/admin//server/[hostname]/users/
  ```
- main content links are missing the `/server/[hostname]` part and lead to *Not Found*
  ```
  https://example.net/admin/users/
  ```

**Comment by licaon-kter** [comment] 2020-04-08 09:53
/duplicate of https://github.com/processone/ejabberd/issues/3200 and others linked there?

**Comment by f055** [comment] 2020-04-08 10:02
@licaon-kter yes, but I'm providing more details because looking at @prefiks patches I'm not entirely sure it will fix all issues I describe. If yes, this ticket will be a simple close after next release.

**Comment by Neustradamus** [comment] 2020-04-08 11:25
Patched after 20.03, it is for this I have requested a quickly 20.03.1.

**Comment by f055** [comment] 2020-04-08 11:27
@Neustradamus Ok, thanks! Well I guess it's April and now we will have 20.04.

**Comment by badlop** [comment] 2020-04-17 10:24
I've just confirmed those two problems, that were introduced in 20.03, are already fixed :)

**Closed** 2020-04-17 10:24 UTC

**Comment by Neustradamus** [comment] 2020-04-19 10:31
@badlop: a 20.04 will be here?
