### ISSUE TITLE
mod_block_strangers don't blocks messages by default

### ISSUE THREAD

**Issue by beherit** [processone/ejabberd#1713] opened 2017-05-04 17:07 UTC
> What version of ejabberd are you using?

17.04

> What operating system (version) are you using?

Debian 8.7

> How did you install ejabberd (source, package, distribution)?

From jabber.at repo

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

mod_block_strangers don't blocks messages if we configure this module as documentation says:
```
modules: 
  mod_block_strangers: {}
```
Module works only if we add:
```
modules: 
  mod_block_strangers:
    drop: true
```

**Comment by zinid** [comment] 2017-05-05 08:51
Well I cannot reproduce. Do you have any configuration errors in the log? Is indentation is correct? Can you reproduce easily?

**Comment by beherit** [comment] 2017-05-05 11:43
No, I don't have configuration errors or others errors in log file. Everything is configured as I said above. Yep I can reproduce it on my two ejabberd servers.

**Comment by beherit** [comment] 2017-05-07 05:58
I don't know how this module work - today I received many messages from strangers :/

**Comment by zinid** [comment] 2017-05-07 06:53
It works pretty much straightforward, I think the problem is in the configuration, most likely.

**Comment by beherit** [comment] 2017-05-07 15:35
@zinid I found that module doesn't block messages from strangers when I offline! Such messages goes to offline message and I receiving it after when I go online.

**Comment by zinid** [comment] 2017-06-01 11:53
@beherit sorry for the late response, but I cannot reproduce :/

**Comment by beherit** [comment] 2017-06-20 12:13
I can reproduce this issue on all my servers... What can I do now? mod_block_strangers works only when I online.

**Comment by zinid** [comment] 2017-06-20 15:26
Since the functions from `mod_block_strangers` are hooked on `user_receive_packet`, I can't see how this is possible, because even though a message gets stored in an offline queue, it will be dropped once a user is connected again.

**Comment by beherit** [comment] 2017-06-20 16:08
@zinid such message are saved in MAM? Maybe here is a problem...

**Comment by zinid** [comment] 2017-06-20 16:16
Yes, it's saved there. I'm gonna to remove this soon.

**Comment by cromain** [comment] 2017-08-03 12:56
moving to 17.09 as it needs hooks refactoring

**Comment by bluszcz** [comment] 2017-08-24 09:09
I am not sure if this is related with MAM, but this module seems does not work for me.

I tried also to send the message to online user and I have received it.

**Closed** 2017-09-02 19:56 UTC
Labels: Kind:Bug, Level:Advanced
