### ISSUE TITLE
€ Character in Password with external auth leads to timeout?

### ISSUE THREAD

**Issue by TheBigK02** [processone/ejabberd#2871] opened 2019-04-26 07:49 UTC
Hi,

I hope you guys can reproduce that in some way but I have a weird problem with external authentication script. I am using a self written perl script that authenticates against keycloak REST api. This works well when I dont have a € character in the password. When I pipe the password including € sign to my script it works fine, but when I use gajim as the client trying to authenticate this is the log. 

The script works still fine even tho I run into timeout. After the timeout ends, the script authenticates with the correct password, but it does that after the timeout ends.

So I am hopeful that this is not a problem of my script rather than ejabberd doing some weird things when theres this character in the password.

Oh my script is adapted from the debian backports example extauth plugin. I needed to do some URL-Encoding and also set the character set encoding for the script to utf8 but after that pretty much all character (didnt test them all obviously) work except the euro sign.

2019-04-26 08:59:57.724 [error] <0.32532.0>@ejabberd_auth_external:failure:103 External authentication program failed when calling 'check_password' for USER@DOMAIN: timeout
2019-04-26 08:59:57.725 [warning] <0.32532.0>@ejabberd_c2s:handle_auth_failure:452 (tls|<0.32532.0>) Failed c2s PLAIN authentication for USER@DOMAIN from ::FFFF:192.168.12.227: Invalid username or password
2019-04-26 08:59:57.726 [error] <0.650.0> Supervisor 'extauth_pool_domain' had child 'extauth_pool_domain_2' started with extauth:start_link('extauth_pool_domain_2', "/etc/ejabberd/check_keycloak.pl") at <0.652.0> exit with reason normal in context child_terminated

**Comment by TheBigK02** [comment] 2019-04-26 08:10
I forgot about those:

What version of ejabberd are you using?

18.12.1-2~bpo9+1

What operating system (version) are you using?

Debian 9.8

How did you install ejabberd (source, package, distribution)?

Package

**Comment by badlop** [comment] 2019-05-08 11:05
I've installed Gajim 1.1.2 from debian package and ejabberd 18.12 from source code, configured with the example perl extauth script:
```yaml
auth_method: external
extauth_program: "/home/ejabberd/check_pass_null.pl"
```
Gajim and Tkabber can login correctly to any account providing passwords that contain €.
```
13:01:50.460 [info] (<0.533.0>) Accepted connection ::ffff:127.0.0.1:60612 -> ::ffff:127.0.0.1:5222
13:01:51.999 [info] (tls|<0.533.0>) Accepted c2s PLAIN authentication for aa2@localhost by external backend from ::ffff:127.0.0.1
13:01:52.037 [info] (tls|<0.533.0>) Opened c2s session for aa2@localhost/gajim.D4WV8WIM
```
Can you try with that example script, to see if the problem is reproducible with other well-known script or only with your own?

**Comment by TheBigK02** [comment] 2019-05-09 09:04
Hi,

first of all thanks for looking into it. I agree that the example script itself does work.

I wonder now how the script works when i pipe the credentials to my custom auth script and it works... but it runs into timeout when pass the credentials over with a jabber client over to ejabberd.

The weird part is that i can actually see that the login is successfull in the syslog... after the timeout is reached... 

I do some more testing and try to get back to u asap !
Any suggestions are appreciated :)

**Comment by mremond** [comment] 2020-02-26 14:16
It seems like an encoding management issue in your code.

Closing it as we did not get more feedback.

**Closed by mremond** 2020-02-26 14:16 UTC
Labels: Note:Needs more info
