### ISSUE TITLE
mod-bosh issue

### ISSUE THREAD

**Issue by kishoreacesurf** [processone/ejabberd#2334] opened 2018-03-22 07:52 UTC
> What version of ejabberd are you using?

18.01

> What operating system (version) are you using?

Centos 7.4

> How did you install ejabberd (source, package, distribution)?
Package

2018-03-22 06:53:45 =ERROR REPORT====
** State machine <0.24376.5> terminating
** Last message in was {'$gen_sync_event',{<30302.14594.6>,#Ref<30302.3330603039.123994113.241137>},{body,<<>>,[{sid,<<"ae2bd93da79d254128feb6f354009851
90e4b905">>},{rid,0}],[{xmlstreamelement,{xmlel,<<"presence">>,[{<<"xmlns">>,<<"jabber:client">>}],[]}},{xmlstreamelement,{xmlel,<<"presence">>,[{<<"xml
ns">>,<<"jabber:client">>}],[]}}],178}}
** When State == active
** Data == {state,<<"xmpp.yellowmssngr.com">>,<<"ae2bd93da79d254128feb6f35400985190e4b905">>,{{[],[]},0,unlimited},{{[{xmlstreamelement,{xmlel,<<"
stream:features">>,[],[{xmlel,<<"mechanisms">>,[{<<"xmlns">>,<<"urn:ietf:params:xml:ns:xmpp-sasl">>}],[{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"PLAIN">>}]},{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"X-OAUTH2">>}]},{xmlel,<<"mechanism">>,[],[{xmlcdata,<<"ANONYMOUS">>}]}]},{xmlel,<<"register">>,[{<<"xmlns">>,<<"http://jabber.org/features/iq-register">>}],[]}]}}],[]},1,unlimited},{maxrate,1000,80.4600493083472,1521701624099852},<0.24377.5>,<<"1.0">>,undefined,#Ref<0.1917408050.3880517635.216191>,60,3600,2346807549,<<>>,undefined,unlimited,{1,{2346807549,{body,<<>>,[{sid,<<"ae2bd93da79d254128feb6f35400985190e4b905">>},{wait,60},{ver,<<"1.11">>},{polling,2},{inactivity,3600},{hold,1},{'xmpp:restartlogic',true},{requests,2},{secure,true},{maxpause,120},{'xmlns:xmpp',<<"urn:xmpp:xbosh">>},{'xmlns:stream',<<"http://etherx.jabber.org/streams">>},{from,<<"xmpp.yellowmssngr.com">>}],[{xmlstreamstart,<<"stream:stream">>,[{<<"id">>,<<"289158546763508795">>},{<<"version">>,<<"1.0">>},{<<"xml:lang">>,<<"en">>},{<<"xmlns:stream">>,<<"http://etherx.jabber.org/streams">>},{<<"from">>,<<"xmpp.yellowmssngr.com">>},{<<"xmlns">>,<<"jabber:client">>}]}],0},nil,nil}},{1,{0,{{<30321.31959.5>,#Ref<30321.1438874428.3613130753.22086>},{body,<<>>,[{sid,<<"ae2bd93da79d254128feb6f35400985190e4b905">>},{rid,0}],[],106}},nil,nil}},{{[],[]},0,1000},{{0,0,0,0,0,65535,2564,25},58170},2}
** Reason for termination =
** {{key_exists,0},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,465}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-22 06:53:45 =CRASH REPORT====
crasher:
initial call: ejabberd_bosh:init/1
pid: <0.24376.5>
registered_name: []
exception exit: {{{key_exists,0},[{gb_trees,insert_1,4,[{file,"gb_trees.erl"},{line,319}]},{gb_trees,insert,3,[{file,"gb_trees.erl"},{line,278}]},{ejabberd_bosh,active1,3,[{file,"src/ejabberd_bosh.erl"},{line,465}]},{p1_fsm,handle_msg,10,[{file,"src/p1_fsm.erl"},{line,582}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},[{p1_fsm,terminate,8,[{file,"src/p1_fsm.erl"},{line,760}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
ancestors: ['mod_bosh_xmpp.yellowmssngr.com',ejabberd_gen_mod_sup,ejabberd_sup,<0.20648.0>]
message_queue_len: 0
messages: []
links: [<0.21031.0>]
dictionary: [{'$internal_queue_len',0}]
trap_exit: false
status: running
heap_size: 1598
stack_size: 27
reductions: 1168
neighbours:

**Comment by zinid** [comment] 2018-03-22 08:31
This is a duplicate of some existing issue.

**Closed by zinid** 2018-03-22 08:31 UTC

**Comment by kishoreacesurf** [comment] 2018-03-23 09:27
Can you point to the duplicate issue. The other one I have created is related to mnesia overload. Please reopen otherwise

**Comment by zinid** [comment] 2018-03-23 10:33
It's #2277
