### ISSUE TITLE
Adding Occupants to a Room

### ISSUE THREAD

**Issue by CreativeWolf** [processone/ejabberd#2611] opened 2018-09-20 15:27 UTC
> What version of ejabberd are you using?

ejabberd 18.06

> What operating system (version) are you using?

Ubuntu 16.04

> How did you install ejabberd (source, package, distribution)?

Source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

At first I tried subscribing a user to a group and expected them to be "in" the group by default (or become occupant of the group) then after some searching stumbled upon this https://stackoverflow.com/questions/50581641/how-to-add-occupants-users-to-a-muc-room?rq=1 response by @badlop 

Now, how do I make a user become occupant of a room so that when they log in, they by default get to be part of the room?

Appreciate any pointers on this please.

Thanks!

**Comment by zinid** [comment] 2018-09-20 15:33
I close the issue as this is not a bug report.

**Closed by zinid** 2018-09-20 15:33 UTC

**Comment by CreativeWolf** [comment] 2018-09-20 15:48
Heya @zinid I understand it's not a bug report, only after searching through earlier issues, both closed and open, googling, skimming through the documentation, I had to ask here. I'd really appreciate if you can even point me to some resource that I have missed looking at.

Thanks!
