### ISSUE TITLE
Ejabberd stopped after join_cluster

### ISSUE THREAD

**Issue by dlameri** [processone/ejabberd#2079] opened 2017-10-31 17:58 UTC
> What version of ejabberd are you using?

17.09, but i also tried with 17.06

> What operating system (version) are you using?

Ubuntu 16.04.2 LTS

> How did you install ejabberd (source, package, distribution)?

Embedded on an Elixir Application.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

I'm trying to call join_cluster over http ($host:5281/api/join_cluster), and every time i do that, the application just stop, without any log explicitly telling why.

Both instances are on AWS EC2, on the same VPC and SecurityGroup configured to allow everything, even ping. I explicitly configured /etc/hosts of each machine to know each others DNS name.

I'm not 100% sure that it's a bug, but If it's not a bug, it should, at least, be a little more specific about the error that is happening.

```
2017-10-31 17:51:43.542 [debug] <0.1636.0>@ejabberd_commands:do_execute_command:495 Executing command ejabberd_admin:join_cluster with Args=[<<"mercurio@ip-10-60-0-61">>]
2017-10-31 17:51:43.547 [info] <0.1299.0>@ejabberd_listener:stop_listener:387 Stop accepting TCP connections at 0.0.0.0:5222 for ejabberd_c2s
2017-10-31 17:51:43.547 [info] <0.1299.0>@ejabberd_listener:stop_listener:387 Stop accepting TCP connections at 0.0.0.0:5269 for ejabberd_s2s_in
2017-10-31 17:51:43.547 [info] <0.1299.0>@ejabberd_listener:stop_listener:387 Stop accepting TCP connections at 0.0.0.0:5280 for ejabberd_http
2017-10-31 17:51:43.547 [info] <0.1299.0>@ejabberd_listener:stop_listener:387 Stop accepting TCP connections at 0.0.0.0:5281 for ejabberd_http
2017-10-31 17:51:43.549 [info] <0.1573.0>@mod_muc_room:terminate:667 Stopping MUC room aaa@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1574.0>@mod_muc_room:terminate:667 Stopping MUC room bbb@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1569.0>@mod_muc_room:terminate:667 Stopping MUC room room1@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1575.0>@mod_muc_room:terminate:667 Stopping MUC room room2@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1576.0>@mod_muc_room:terminate:667 Stopping MUC room room3@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1568.0>@mod_muc_room:terminate:667 Stopping MUC room room33@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1571.0>@mod_muc_room:terminate:667 Stopping MUC room room34@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1577.0>@mod_muc_room:terminate:667 Stopping MUC room room7@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1578.0>@mod_muc_room:terminate:667 Stopping MUC room room9@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1579.0>@mod_muc_room:terminate:667 Stopping MUC room room9999999999@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1572.0>@mod_muc_room:terminate:667 Stopping MUC room test_room_1bd@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1570.0>@mod_muc_room:terminate:667 Stopping MUC room testroom@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1566.0>@mod_muc_room:terminate:667 Stopping MUC room testroom65412@conference.localhost
2017-10-31 17:51:43.549 [info] <0.1567.0>@mod_muc_room:terminate:667 Stopping MUC room testroom899899898@conference.localhost
2017-10-31 17:51:43.551 [debug] <0.1564.0>@ejabberd_router:unregister_route:188 Route unregistered: conference.localhost
2017-10-31 17:51:43.552 [debug] <0.1580.0>@mod_pubsub:terminate_plugins:388 ** terminate flat plugin
2017-10-31 17:51:43.552 [debug] <0.1580.0>@mod_pubsub:terminate_plugins:388 ** terminate hometree plugin
2017-10-31 17:51:43.552 [debug] <0.1580.0>@ejabberd_router:unregister_route:188 Route unregistered: pubsub.localhost
2017-10-31 17:51:43.553 [debug] <0.1544.0>@ejabberd_router:unregister_route:188 Route unregistered: localhost
2017-10-31 17:51:43.561 [info] <0.1299.0>@ejabberd_app:stop:79 ejabberd 17.9.0 is stopped in the node 'mercurio@ip-10-60-0-92'
2017-10-31 17:51:43.562 [info] <0.1220.0> Application ejabberd exited with reason: stopped
```

**Comment by dlameri** [comment] 2017-10-31 20:01
Restarting the application seems to be the normal behaviour.

Testing locally, i noticed that if a call on iex :ejabberd_admin.join_cluster, it works, but on http api it stops at `2017-10-31 17:51:43.562 [info] <0.1220.0> Application ejabberd exited with reason: stopped`.

**Comment by badlop** [comment] 2017-11-01 12:56
Looking at the source code [1], ejabberd is stopped, then mnesia is configured for clustering, and finally ejabberd is started again.
In my test, it fails, but at least throws those errors in the node where I call join_cluster:
```
13:55:18.824 [error] failure on mnesia change_table_copy_type [ejabberd_commands,ejabberd2@localhost,ram_copies]: {aborted,{no_exists,ejabberd_commands}}
13:55:18.826 [error] CRASH REPORT Process <0.654.0> with 0 neighbours exited with reason: {aborted,{no_exists,ejabberd_commands}} in gen_server:init_it/6 line 352
13:55:18.827 [error] Supervisor ejabberd_sup had child ejabberd_commands started with ejabberd_commands:start_link() at undefined exit with reason {aborted,{no_exists,ejabberd_commands}} in context start_error
13:55:18.850 [error] CRASH REPORT Process <0.613.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,ejabberd_commands,{aborted,{no_exists,ejabberd_commands}}}},{ejabberd_app,start,[normal,[]]}} in application_master:init/4 line 134
13:55:18.851 [info] Application ejabberd exited with reason: {{shutdown,{failed_to_start_child,ejabberd_commands,{aborted,{no_exists,ejabberd_commands}}}},{ejabberd_app,start,[normal,[]]}}
```
[1] https://github.com/processone/ejabberd/blob/master/src/ejabberd_cluster_mnesia.erl#L54

**Comment by dlameri** [comment] 2017-11-01 13:35
That's odd.

But, supposing that we share the same error, what would be the solution for that?

**Comment by dlameri** [comment] 2017-11-03 19:04
I gave up on using http for join cluster and decided to use libcluster for that.

Now i got the same erros as badlop did.  

Is there a way to prevent it?

**Comment by badlop** [comment] 2017-11-13 10:05
I've tried it again, and the mnesia table clustering works correctly, even if those errors are shown in the node that is joining the cluster: the items in the cluster's tables get replicated in that joined node, and any new user registered in the master node or this new node get replicated to the other nodes.

**Comment by cromain** [comment] 2017-11-17 10:04
join_cluster process stops ejabberd.
As you are embedding ejabberd in an elixir app, maybe ejabberd is supervised and make your supervisor/application stop when ejabberd stops.
calling join_cluster with API is not tested and may not work, as http listeners are likely supervised by ejabberd... which is being stopped. ejabberdctl MUST be used for that command if you need kind of automated process.

@badlop i could not reproduce the error on ejabberd_commands (this table is local_content, no relation with cluster), do you have more details ?

**Comment by badlop** [comment] 2017-11-22 10:35
The problem is 100% reproducible for me. Install current git in two paths, configure one as ejabberd1@localhost, other as ejabberd2@localhost, and different listener ports (both nodes are in the  same machine). Start both nodes in live mode. In the first node register a new user. In the second node call:
> ejabberdctl join_cluster ejabberd1@localhost

This is shown in first node:
```
11:24:04.553 [error] unexpected info: {mnesia_system_event,{mnesia_up,ejabberd2@localhost}}
```

This is shown in second node:
```
11:24:04.383 [info] Stop accepting TCP connections at [::]:5222 for ejabberd_c2s
11:24:04.383 [info] Stop accepting TCP connections at [::]:5269 for ejabberd_s2s_in
11:24:04.383 [info] Stop accepting TCP connections at [::]:5280 for ejabberd_http
11:24:04.410 [info] ejabberd 17.11.1 is stopped in the node ejabberd2@localhost
11:24:04.414 [info] Application ejabberd exited with reason: stopped
11:24:04.420 [info] Application mnesia exited with reason: stopped
11:24:04.434 [info] Application mnesia started on node ejabberd2@localhost
11:24:04.817 [notice] Changed loghwm of /tmp/eja2/var/log/ejabberd/error.log to 100
11:24:04.817 [notice] Changed loghwm of /tmp/eja2/var/log/ejabberd/ejabberd.log to 100
11:24:04.819 [info] Loading configuration from /tmp/eja2/etc/ejabberd/ejabberd.yml
11:24:04.970 [info] FQDN used to check DIGEST-MD5 SASL authentication: localhost
11:24:05.732 [info] Changing Mnesia table 'route' from unknown to ram_copies
11:24:05.869 [error] failure on mnesia change_table_copy_type
 [route,ejabberd2@localhost,ram_copies]: {aborted,{already_exists,route,ejabberd2@localhost,ram_copies}}
11:24:05.873 [info] Changing Mnesia table 'session' from unknown to ram_copies
11:24:05.875 [error] failure on mnesia change_table_copy_type
 [session,ejabberd2@localhost,ram_copies]: {aborted,{badarg,session,unknown}}
11:24:05.875 [info] Changing Mnesia table 'session_counter' from unknown to ram_copies
11:24:05.876 [error] failure on mnesia change_table_copy_type
 [session_counter,ejabberd2@localhost,ram_copies]: {aborted,{badarg,session_counter,unknown}}
11:24:05.882 [warning] module 'mod_mam' is recommended for module 'mod_muc' but is not found in the config
11:24:05.883 [info] Changing Mnesia table 'sr_group' from unknown to disc_copies
11:24:06.026 [error] failure on mnesia change_table_copy_type
 [sr_group,ejabberd2@localhost,disc_copies]: {aborted,{badarg,sr_group,unknown}}
11:24:06.027 [info] Changing Mnesia table 'sr_user' from unknown to disc_copies
11:24:06.028 [error] failure on mnesia change_table_copy_type
 [sr_user,ejabberd2@localhost,disc_copies]: {aborted,{badarg,sr_user,unknown}}
11:24:06.033 [info] Changing Mnesia table 'muc_room' from unknown to disc_copies
11:24:06.358 [error] failure on mnesia change_table_copy_type
 [muc_room,ejabberd2@localhost,disc_copies]: {aborted,{badarg,muc_room,unknown}}
11:24:06.358 [info] Changing Mnesia table 'muc_registered' from unknown to disc_copies
11:24:06.360 [error] failure on mnesia change_table_copy_type
 [muc_registered,ejabberd2@localhost,disc_copies]: {aborted,{badarg,muc_registered,unknown}}
11:24:06.360 [info] Changing Mnesia table 'muc_online_room' from unknown to ram_copies
11:24:06.362 [error] failure on mnesia change_table_copy_type
 [muc_online_room,ejabberd2@localhost,ram_copies]: {aborted,{badarg,muc_online_room,unknown}}
11:24:06.378 [info] Changing Mnesia table 'private_storage' from unknown to disc_only_copies
11:24:06.579 [error] failure on mnesia change_table_copy_type
 [private_storage,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,private_storage,unknown}}
11:24:06.580 [info] Changing Mnesia table 'privacy' from unknown to disc_only_copies
11:24:06.835 [error] failure on mnesia change_table_copy_type
 [privacy,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,privacy,unknown}}
11:24:06.842 [info] Changing Mnesia table 'vcard' from unknown to disc_only_copies
11:24:07.124 [error] failure on mnesia change_table_copy_type
 [vcard,ejabberd2@localhost,disc_only_copies]: {aborted,{already_exists,vcard,ejabberd2@localhost,disc_only_copies}}
11:24:07.125 [info] Changing Mnesia table 'vcard_search' from unknown to disc_copies
11:24:07.126 [error] failure on mnesia change_table_copy_type
 [vcard_search,ejabberd2@localhost,disc_copies]: {aborted,{badarg,vcard_search,unknown}}
11:24:07.127 [info] Changing Mnesia table 'motd' from unknown to disc_only_copies
11:24:07.127 [error] failure on mnesia change_table_copy_type
 [motd,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,motd,unknown}}
11:24:07.128 [info] Changing Mnesia table 'motd_users' from unknown to disc_only_copies
11:24:07.128 [error] failure on mnesia change_table_copy_type
 [motd_users,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,motd_users,unknown}}
11:24:07.129 [info] Changing Mnesia table 'bosh' from unknown to ram_copies
11:24:07.130 [error] failure on mnesia change_table_copy_type
 [bosh,ejabberd2@localhost,ram_copies]: {aborted,{no_exists,bosh}}
11:24:07.131 [info] Changing Mnesia table 'push_session' from unknown to disc_only_copies
11:24:07.544 [error] failure on mnesia change_table_copy_type
 [push_session,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,push_session,unknown}}
11:24:07.546 [info] Changing Mnesia table 'roster' from unknown to disc_only_copies
11:24:07.547 [error] failure on mnesia change_table_copy_type
 [roster,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,roster,unknown}}
11:24:07.547 [info] Changing Mnesia table 'roster_version' from unknown to disc_only_copies
11:24:07.548 [error] failure on mnesia change_table_copy_type
 [roster_version,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,roster_version,unknown}}
11:24:07.550 [info] Changing Mnesia table 'last_activity' from unknown to disc_only_copies
11:24:07.552 [error] failure on mnesia change_table_copy_type
 [last_activity,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,last_activity,unknown}}
11:24:07.554 [info] Changing Mnesia table 'offline_msg' from unknown to disc_only_copies
11:24:07.909 [error] failure on mnesia change_table_copy_type
 [offline_msg,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,offline_msg,unknown}}
11:24:07.912 [info] Changing Mnesia table 'caps_features' from unknown to disc_only_copies
11:24:07.915 [error] failure on mnesia change_table_copy_type
 [caps_features,ejabberd2@localhost,disc_only_copies]: {aborted,{no_exists,caps_features}}
11:24:08.260 [info] Changing Mnesia table 'pubsub_last_item' from unknown to ram_copies
11:24:08.513 [error] failure on mnesia change_table_copy_type
 [pubsub_last_item,ejabberd2@localhost,ram_copies]: {aborted,{already_exists,pubsub_last_item,ejabberd2@localhost,ram_copies}}
11:24:08.517 [info] Changing Mnesia table 'pubsub_index' from unknown to disc_copies
11:24:08.519 [error] failure on mnesia change_table_copy_type
 [pubsub_index,ejabberd2@localhost,disc_copies]: {aborted,{badarg,pubsub_index,unknown}}
11:24:08.520 [info] Changing Mnesia table 'pubsub_node' from unknown to disc_copies
11:24:08.523 [error] failure on mnesia change_table_copy_type
 [pubsub_node,ejabberd2@localhost,disc_copies]: {aborted,{badarg,pubsub_node,unknown}}
11:24:08.523 [info] Changing Mnesia table 'pubsub_state' from unknown to disc_copies
11:24:08.758 [error] failure on mnesia change_table_copy_type
 [pubsub_state,ejabberd2@localhost,disc_copies]: {aborted,{badarg,pubsub_state,unknown}}
11:24:08.758 [info] Changing Mnesia table 'pubsub_item' from unknown to disc_only_copies
11:24:08.762 [error] failure on mnesia change_table_copy_type
 [pubsub_item,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,pubsub_item,unknown}}
11:24:08.763 [info] Changing Mnesia table 'pubsub_orphan' from unknown to disc_copies
11:24:08.764 [error] failure on mnesia change_table_copy_type
 [pubsub_orphan,ejabberd2@localhost,disc_copies]: {aborted,{badarg,pubsub_orphan,unknown}}
11:24:08.768 [info] Changing Mnesia table 'irc_custom' from unknown to disc_copies
11:24:09.108 [error] failure on mnesia change_table_copy_type
 [irc_custom,ejabberd2@localhost,disc_copies]: {aborted,{badarg,irc_custom,unknown}}
11:24:09.110 [info] Changing Mnesia table 'carboncopy' from unknown to ram_copies
11:24:09.111 [error] failure on mnesia change_table_copy_type
 [carboncopy,ejabberd2@localhost,ram_copies]: {aborted,{badarg,carboncopy,unknown}}
11:24:09.112 [info] Changing Mnesia table 'passwd' from unknown to disc_only_copies
11:24:09.113 [error] failure on mnesia change_table_copy_type
 [passwd,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,passwd,unknown}}
11:24:09.113 [info] Changing Mnesia table 'reg_users_counter' from unknown to ram_copies
11:24:09.115 [error] failure on mnesia change_table_copy_type
 [reg_users_counter,ejabberd2@localhost,ram_copies]: {aborted,{badarg,reg_users_counter,unknown}}
11:24:09.117 [info] Changing Mnesia table 'oauth_token' from unknown to disc_only_copies
11:24:09.118 [error] failure on mnesia change_table_copy_type
 [oauth_token,ejabberd2@localhost,disc_only_copies]: {aborted,{badarg,oauth_token,unknown}}
11:24:09.453 [info] Waiting for Mnesia synchronization to complete
11:24:09.455 [info] ejabberd 17.11.1 is started in the node ejabberd2@localhost in 4.64s
11:24:09.467 [info] Application ejabberd started on node ejabberd2@localhost
11:24:09.470 [info] Start accepting TCP connections at [::]:5280 for ejabberd_http
11:24:09.470 [info] Start accepting TCP connections at [::]:5269 for ejabberd_s2s_in
11:24:09.471 [info] Start accepting TCP connections at [::]:5222 for ejabberd_c2s
```
As I said, even if those warnings are shown in node2, user1  can login perfectly connecting to node2's port listeners, and that is shown in the logs. That means, the passwd table content from node1 was correctly replicated to node2.

**Comment by cromain** [comment] 2017-12-12 13:44
I confirm the error messages from change_table_copy_type on added node side, which are harmless as ejabberd is starting correctly and mnesia table then are all in correct state and type. Despite the logs, node is correctly added to debug.

I'm checking why we have those errors, and why they do not reflect effective mnesia state after ejabberd started.

**Comment by cromain** [comment] 2017-12-21 13:09
join_cluster did async copy, while ejabberd_mnesia:init was called.
this is now fixed.
side effect, when joining cluster with big mnesia database, --no-timeout parameter must be passed to ejabberdctl call.

**Closed by cromain** 2017-12-21 13:09 UTC
