### ISSUE TITLE
Crash when login with incorrect password using SASL

### ISSUE THREAD

**Issue by badlop** [processone/ejabberd#1440] opened 2016-12-29 17:33 UTC
> What version of ejabberd are you using?

Current git master

> What operating system (version) are you using?

Linux

> How did you install ejabberd (source, package, distribution)?

git source

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

Login to an existing account, but provide a bad password, using SASL auth. It doesn't return any error, and logs this problem:
```
18:26:20.414 [info] ({socket_state,fast_tls,{tlssock,#Port<0.18690>,#Port<0.18691>},<0.769.0>})
 Failed authentication for user221@localhost from 127.0.0.1
18:26:20.415 [error] gen_fsm <0.770.0> in state wait_for_sasl_response terminated with reason:
 no function clause matching xmpp_codec:'encode_sasl_failure_$reason'
 ('bad-auth', <<"urn:ietf:params:xml:ns:xmpp-sasl">>, []) line 29543
18:26:20.415 [error] CRASH REPORT Process <0.770.0> with 0 neighbours exited with reason:
 no function clause matching xmpp_codec:'encode_sasl_failure_$reason'
('bad-auth', <<"urn:ietf:params:xml:ns:xmpp-sasl">>, []) line 29543 in p1_fsm:terminate/8 line 760
```

**Comment by zinid** [comment] 2016-12-29 20:47
https://github.com/processone/ejabberd/issues/1427

**Comment by zinid** [comment] 2016-12-29 20:49
And this one comes from `cyrsasl_scram.erl` again.

**Comment by zinid** [comment] 2017-01-02 12:06
This is a duplicate of https://github.com/processone/ejabberd/issues/1427
I close.

**Closed by zinid** 2017-01-02 12:06 UTC
