### ISSUE TITLE
ejabberd doesn't send smack requests and closes connection

### ISSUE THREAD

**Issue by andreygursky** [processone/ejabberd#2159] opened 2017-12-10 18:24 UTC
> What version of ejabberd are you using?
> What operating system (version) are you using?
> How did you install ejabberd (source, package, distribution)?

I'm not a server admin, the server doesn't advertise it's version. It's jabber.ccc.de. I guess 17.08 or earlier on GNU/Linux.

> What did not work as expected? Are there error messages in the log? What
> was the unexpected behavior? What was the expected result?

During initial connection (with MUCs autojoin) server sends stanzas and on a regular basis smack requests, which are acked by client and connection remains. Instead I see many stanzas and no smack requests, then connection is reset.

This happens with 13 rooms. Disabling autojoin on the 3 most big one (~160, 120 and 60 participants) allows successful connection. This [looks so in Gajim](https://dev.gajim.org/gajim/gajim/issues/8758):
```
11/16/2017 19:16:00 (D) nbxmpp.smacks Got ack for outgoing stanzas (our h: 46, server h: 24), removing 1 messages from queue...
11/16/2017 19:16:00 (I) nbxmpp.transports_nb pollin called, state == CONNECTED
11/16/2017 19:16:00 (I) nbxmpp.client_nb raising event from transport: :::::DATA RECEIVED::::
_____________
<r xmlns='urn:xmpp:sm:2'/>
_____________

11/16/2017 19:16:00 (I) nbxmpp.transports_nb Plugging fd 26, W:False, R:True
11/16/2017 19:16:00 (I) nbxmpp.client_nb raising event from transport: :::::DATA SENT::::
_____________
<a xmlns="urn:xmpp:sm:2" h="25" />
_____________

[ --- snip: there is NO smacks requests from server in-between! --- ]

11/16/2017 19:16:14 (I) nbxmpp.transports_nb pollin called, state == CONNECTED
11/16/2017 19:16:14 (I) nbxmpp.client_nb raising event from transport: :::::DATA RECEIVED::::
_____________
<r xmlns='urn:xmpp:sm:2'/>
_____________

11/16/2017 19:16:14 (I) nbxmpp.transports_nb Plugging fd 26, W:True, R:True
11/16/2017 19:16:14 (I) nbxmpp.client_nb raising event from transport: :::::DATA SENT::::
_____________
<a xmlns="urn:xmpp:sm:2" h="997" />
_____________
```

Even after applying [a patch kindly proposed](https://dev.gajim.org/gajim/python-nbxmpp/issues/45) by Gajim lead developer @yann-l, which forces the client to send unrequested smacks, doesn't solve the issue.

P.S. @weiss, I've noticed: https://github.com/processone/ejabberd/commit/532aba993bf270604c2715773c3f668b5846c254 you've raised the limit, thanks! But I guess regardless of the limit, the behavior of ejabberd might be faulty.

**Comment by andreygursky** [comment] 2017-12-10 18:33
A question is, while putting stanzas into sending queue, how ejabberd decides to insert a smack request. And after requesting an ack would ejabberd throttle the sending awaiting an answer?

**Comment by weiss** [comment] 2017-12-10 23:16
> while putting stanzas into sending queue, how ejabberd decides to insert a smack request.

It requests an ACK for each and every queued stanza, but it won't request another ACK before the previous one was received and processed by the server.

> would ejabberd throttle the sending awaiting an answer?

No, that wouldn't make sense.

I see no solution other than using a queue size large enough to cope with such (legitimate) message bursts.

**Comment by andreygursky** [comment] 2017-12-11 11:31
> > would ejabberd throttle the sending awaiting an answer?
>
> No, that wouldn't make sense.

Yes, provided ejabberd uses default blocking access to TCP socket, since TCP will cope with different sender/receiver speeds. But if ejabberd uses a non-blocking access to TCP socket (ignoring delayed acks by not waiting for them), this will sabotage underlying TCP algorithms.

So if I understand correctly, ejabberd indeed kills the connection regardless of the client behavior, because it puts too many messages in a sending queue, doesn't ask the client to ack them but complains there are too many unacked stanzas. Making the queue size larger seems to be still a workaround.

Theoretically a properly solution would be to fix the function that puts data in a queue. This function should obviously flush the queue by sending smack request regardless of kind of data, just depending on the queue size. Due to how flushing works in SM, this should be done not when the queue is full but much earlier to not allow the queue to overflow immediately (1/10?..).

The issue with this is that actually the workaround with bigger queue size is now replaced by the again hard-coded coefficient, which I consider better but it still can fail. Ideally, using non-blocking sockets should not lead to bloated internal buffers. If the size of the socket sending queue grows, writing into the internal sending queue should be throttled.

**Comment by weiss** [comment] 2017-12-11 12:00
> Yes, provided ejabberd uses default blocking access to TCP socket, since TCP will cope with different sender/receiver speeds. But if ejabberd uses a non-blocking access to TCP socket (ignoring delayed acks by not waiting for them), this will sabotage underlying TCP algorithms.

I don't see how any of this is relevant to the problem.  Your complaint seems to be that ejabberd is flooding the client and thereby not giving it a fair chance to acknowledge stanzas in time.  Assume ejabberd could adapt to the client's processing speed by means of TCP or whatever.  What exactly should ejabberd do with incoming stanzas while the client fails to catch up?

> So if I understand correctly, ejabberd indeed kills the connection regardless of the client behavior, because it puts too many messages in a sending queue, doesn't ask the client to ack them but complains there are too many unacked stanzas.

Seems you misunderstood. ejabberd asks the client to acknowledge a stanza *immediately after sending it*. As I said above, it does so for each and every stanza sent to the client.  *Except* (and this is probably the case you're seeing) if the response to the previous ACK request wasn't reveived yet.  In this case, ejabberd will wait with sending the next request until the previous response was received.

> flush the queue by sending smack request

How would sending an ACK request flush the queue?!  The queue is flushed when receiving the *response*.  In the situation you described, ejabberd is waiting for such a response.  Issueing another ACK request won't help at all.

**Comment by andreygursky** [comment] 2017-12-11 12:00
> > No, that wouldn't make sense.
>
> Yes, provided

In sense of: agree, provided...

**Comment by andreygursky** [comment] 2017-12-11 12:20
> I don't see how any of this is relevant to the problem. Your complaint seems to be that ejabberd is flooding the client and thereby not giving it a fair chance to acknowledge stanzas in time. Assume ejabberd could adapt to the client's processing speed by means of TCP or whatever. What exactly should ejabberd do with incoming stanzas while the client fails to catch up?

Buffer them. If the buffer size (not the number of stanzas) exceeds some reasonable limit for one client connection, then the client is guilty: it must not request such a big number of stanzas at once. Is this avoidable during auto-join?

> Seems you misunderstood. ejabberd asks the client to acknowledge a stanza immediately after sending it. As I said above, it does so for each and every stanza sent to the client. Except (and this is probably the case you're seeing) if the response to the previous ACK request wasn't reveived yet. In this case, ejabberd will wait with sending the next request until the previous response was received.

Aha, so in the dump above server has sent smack request at 19:16:00, which has been instantly acked. At 19:16:14 the server has sent another request. And this means that it took 14 seconds for the server to see the ack from the client? Since it is a huge amount of time (that client doesn't send much data and latency is up to 100ms) I could not think of it and still cannot believe. Does ejabberd really insert an ack and not append it, if some function is filling the buffer and ack came in parallel?

> How would sending an ACK request flush the queue?! The queue is flushed when receiving the response. In the situation you described, ejabberd is waiting for such a response. Issueing another ACK request won't help at all.

Flushing in terms of the client would not send the response, which ejabberd awaits for real flushing, if it will not "flush" the queue with an ACK request. If ejabberd didn't send the next request just because the previous one response has not been yet received, I agree it won't help.

**Comment by andreygursky** [comment] 2017-12-11 12:36
> Buffer them.

Or better: not receive them on the speed that too much differs from the one the data will be forwarded.

> And this means that it took 14 seconds for the server to see the ack from the client?

I guess not...

>  Does ejabberd really insert an ack and not append it...

...but since all stanzas were already sent away it was not possible to insert anymore. On the other hand it could be possible using MSG_OOB flag.

**Comment by weiss** [comment] 2017-12-11 12:56
> > What exactly should ejabberd do with incoming stanzas while the client fails to catch up?
>
> Buffer them.

I'm asking you how to handle incoming stanzas when the buffer size limit is exceeded, and your response is to buffer them up to a "reasonable limit"?

> Or better: not receive them on the speed that too much differs from the one the data will be forwarded.

The incoming stanzas may be received from arbitrary sockets or generated from within ejabberd.  The same sources may also route stanzas to an arbitrary number of other destinations.  You can't let a single client throttle those sources.

> If the buffer size (not the number of stanzas) exceeds some reasonable limit for one client connection, then the client is guilty: it must not request such a big number of stanzas at once.

I disagree.  The client shouldn't have to worry about server-side buffers.  They should just be large enough to handle legitimate work loads.

> this means that it took 14 seconds for the server to see the ack from the client?

I have no idea.  If you can reproduce the issue, you could start tracking this down by enabling debug logging (`ejabberdctl set-loglevel 5`) and extracting the relevant traffic from your `ejabberd.log` file.

> still cannot believe.

I see no alternative to either believing me or reading [the code][1] yourself.

> Does ejabberd really insert an ack and not append it, if some function is filling the buffer and ack came in parallel?

As I said (twice), ejabberd sends an ACK requests immediately after sending a stanza, before the next stanza is enqueued and sent.  Once that happened, there's of course no guarantee regarding the ordering of ejabberd's processing of additional incoming stanzas vs. the processing of the client's ACK response.

> On the other hand it could be possible using MSG_OOB flag.

You're trying very hard to avoid coming to the conclusion that the queue size limit was exceed because the queue size limit is too small :smile:

[1]: https://github.com/processone/ejabberd/blob/17.11/src/mod_stream_mgmt.erl#L209

**Comment by weiss** [comment] 2017-12-11 13:49
> you could start tracking this down by enabling debug logging (`ejabberdctl set-loglevel 5`) and extracting the relevant traffic from your `ejabberd.log` file.

I'll close this issue for the moment.  Feel free to add a comment (or open a new one issue) if you see `[debug]` output that looks like ejabberd is *not* behaving the way I described above.

**Closed by weiss** 2017-12-11 13:49 UTC
