### ISSUE TITLE
Bug: import_prosody fails at importing MUCs

### ISSUE THREAD

**Issue by ThomasLeister** [processone/ejabberd#2874] opened 2019-04-30 16:48 UTC
Ejabberd version: **18.12.1**
Prosody version: **0.11.2**

## The issue: 

I've tried to import Prosody data using the ```ejabberdctl import_prosody``` command. All the users are imported and work fine. Unfortunately **all the conference rooms are missing** - my MUC related PostgreSQL tables are all empty after the import.

No errors are shown in the log file or console after import. 

Example data of the Prosody conference directory is available. Just let me know and I can provide that in a private conversation :-) 

I'd be very happy about a fix, because right now this is a "show stopper" for my migration to Ejabberd ;-)

**Comment by badlop** [comment] 2019-05-02 16:26
Can you provide some example Prosody files, so the problem can be reproduced? email to badlop@process-one.net

**Comment by ThomasLeister** [comment] 2019-05-02 16:52
I just sent you an email with example data. Data is anonymized, but I'm not sure if I forgot anything. That's why I didn't make it public ;-)

**Comment by badlop** [comment] 2019-05-02 17:38
Do you have several vhosts defined at the beginning of ejabberd.yml? Apparently, prosody2ejabberd imports the rooms into the first vhost defined, which may not be the right one. Surprisingly, in my tests with mnesia storage, after importing and ejabberd restart, the rooms are created.

**Comment by badlop** [comment] 2019-05-02 18:34
> Apparently, prosody2ejabberd imports the rooms into the first vhost defined, which may not be the right one.

That problem was crucial when using MySQL, even if it wasn't relevant when using Mnesia. I've fixed it in git, try it if you can.

> In any case, it is required a mod_muc (or whole ejabberd) restart for the rooms to be created

That is still true. So, after importing the database, it's a good idea to restart ejabberd.

**Comment by ThomasLeister** [comment] 2019-05-03 05:06
Thanks for your quick reply!

> Do you have several vhosts defined at the beginning of ejabberd.yml?

Yes, I do. I checked the database of my first virtual host and voi­là - there were all the tables, filled with the MUC data. *(despite the "new" database schema I keep databases for both vHosts separated from each other. That way it will be easier to migrate one of them to another machine in the future.)*

After re-arranging the vHost order in the config and setting the correct vHost as first item in ```hosts:```, the Prosody import still did not work as expected: The MUC data was still written to the wrong database / vHost. 

By removing the other vHost completely from config, I figured out that database / vHost choice might be related to the alphabet :-) My target vHost starts with "t" - the test vHost (which has been used for the import all the time) starts with "e". So my test vHost might have been chosen first, all the time.

After removing the test vHost, all the Prosody MUC data was imported correctly (tbh Ejabberd didn't have a choice then, right? ;-) )

Sooo, I got it working now and I'm able to continue my migration to Ejabberd. Thanks for your support and pointing out what the reason for failure might be. 

Still I guess it would be a good idea to introduce a ```--vhost``` flag for the importer to let the user choose where to import to. (or something similar to that).

**Comment by mremond** [comment] 2019-05-03 07:45
Thanks @ThomasLeister for the detailed report.

Yes, I think having an extra parameter with the target vhost is indeed needed.

**Comment by badlop** [comment] 2019-05-03 09:27
For testing, I've configured vhosts like this, so the target vhost is in the middle of the list in position and in alphabet:
```yaml
hosts:
  - "localhost"
  - "trashserver.net"
  - "zzserver.com"
```
With the fix I committed yesterday, the correct vhost is used because the list is traversed in search for the one that really handles the MUC service where the room wants to be stored.

**Closed by badlop** 2019-05-03 09:27 UTC
Labels: Component:Admin Tools, Kind:Bug, Kind:Feature
