### ISSUE TITLE
Functionality to send pings from server to client irrespective of client sends packets or not. 

### ISSUE THREAD

**Issue by shaggi7** [processone/ejabberd#3260] opened 2020-05-07 04:40 UTC
Hi Guys,
I am using Ejabberd(build from source) on server side for my chat application. I have enabled **mod_ping** module also .
I know the server will send client the ping only if server did not receive pings(or any packet) from the client within a specified time. There is no problem with that. 

But i need a functionality that server should send pings to client at regular interval by its own irrespective whether the user is sending something or not  . It's in the project's need. 

So How can i Implement that .

**Comment by badlop** [comment] 2020-05-07 11:07
When the client sends a stanza, mod_ping resets the timer. You want mod_ping to don't care about what the user sends, you want the timers to be kept always. Basically, it's like removing a feature, simply removing those lines:
```diff
diff --git a/src/mod_ping.erl b/src/mod_ping.erl
index c83f471d2..220ef6dfd 100644
--- a/src/mod_ping.erl
+++ b/src/mod_ping.erl
@@ -210,9 +210,7 @@ register_hooks(Host) ->
     ejabberd_hooks:add(sm_register_connection_hook, Host,
 		       ?MODULE, user_online, 100),
     ejabberd_hooks:add(sm_remove_connection_hook, Host,
-		       ?MODULE, user_offline, 100),
-    ejabberd_hooks:add(user_send_packet, Host, ?MODULE,
-		       user_send, 100).
+		       ?MODULE, user_offline, 100).
 
 unregister_hooks(Host) ->
     ejabberd_hooks:delete(sm_remove_connection_hook, Host,

```

And then pings are sent even if the client sends stanzas:
```yaml
  mod_ping: 
    send_pings: true
    ping_interval: 10 seconds
```

**Comment by mailtosagar** [comment] 2020-05-07 22:38
Thanks @badlop for the patch. 
On applying this patch i see 
1. If the c2s session is closed by me (logging out explicitly or Stream closed by peer) and i login again. I am able to receive ping.
2. If the c2s session is not closed by me and login again (refreshing the page or replaced by new connection). I am not receiving any pings from the server.

I need to sent pings to client in every case. Even if i resume session, end session and relogin, or relogin i need to send pings from server to client .  

Thanks.

**Comment by badlop** [comment] 2020-05-11 16:23
Aha, I can reproduce the problem, applying my configuration and the patch. When a client logins, it receives periodic pings. If another client logins to the same account and resource, the session gets closed, and the new client doesn't receive periodic pings.

This happens because mod_ping uses `sm_register_connection_hook` and `sm_remove_connection_hook` to detect when a client logins or logout, but those hooks are called first register, and later remove.

So, when a new session is established, it first creates the new ping timer for that {username, host, resource} overwritting any existing one. After that, the old session gets destroyed and it removes the ping timer, which happens to be the newly created one, because {username, host, resource} are identical in both cases.

I've committed a fix for that bug, and works for me.

**Comment by mailtosagar** [comment] 2020-05-12 11:55
Thanks @badlop It worked. This Issue can be closed now.

**Closed** 2020-05-15 18:31 UTC
Labels: Kind:Feature
